In [1]:
import pandas as pd

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (1.3.4)
Requirement already satisfied: numpy>=1.17.3 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [3]:
file1 = r"C:\meq\Personal\DataScience\OneCampusMaterials\02-Data Wrangling\workspace\Muskets_data.csv"

In [4]:
df_musket = pd.read_csv(file1)
df_musket

C:\Users\User\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (26,29,76) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85.0,92.0,91.0,95.0,38.0,65.0,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,High,Low,5 ★,89.0,93.0,81.0,89.0,35.0,77.0,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87.0,92.0,78.0,90.0,52.0,90.0,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,High,High,4 ★,76.0,86.0,93.0,88.0,64.0,78.0,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91.0,85.0,86.0,94.0,36.0,59.0,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64.0,28.0,26.0,38.0,48.0,51.0,NaN
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64.0,40.0,48.0,49.0,35.0,45.0,NaN
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63.0,39.0,44.0,46.0,40.0,53.0,NaN
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58.0,49.0,41.0,49.0,30.0,44.0,NaN
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62.0,22.0,39.0,42.0,45.0,55.0,NaN

In [5]:
df_musket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19021 entries, 0 to 19020
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19021 non-null  int64
 1   Name              19021 non-null  object
 2   LongName          19021 non-null  object
 3   photoUrl          19021 non-null  object
 4   playerUrl         19021 non-null  object
 5   Nationality       19021 non-null  object
 6   Age               19021 non-null  int64
 7   ↓OVA              19019 non-null  float64
 8   POT               19020 non-null  float64
 9   Club              19021 non-null  object
 10  Contract          19021 non-null  object
 11  Positions         19021 non-null  object
 12  Height            19021 non-null  object
 13  Weight            19020 non-null  object
 14  Preferred Foot    19021 non-null  object
 15  BOV               19021 non-null  int64
 16  Best Position     19021 non-null  object
 17  Joined            19021 non-null  object
 18  Loan Date End     1015 non-null   object
 19  Value             19021 non-null  object
 20  Wage              19021 non-null  object
 21  Release Clause    19018 non-null  object
 22  Attacking         19020 non-null  float64
 23  Crossing          19020 non-null  float64
 24  Finishing         19016 non-null  float64
 25  Heading Accuracy  19013 non-null  float64
 26  Short Passing     19012 non-null  object
 27  Volleys           19014 non-null  float64
 28  Skill             19015 non-null  float64
 29  Dribbling         19020 non-null  object
 30  Curve             19013 non-null  float64
 31  FK Accuracy       19015 non-null  float64
 32  Long Passing      19018 non-null  float64
 33  Ball Control      19018 non-null  float64
 34  Movement          19016 non-null  float64
 35  Acceleration      19017 non-null  float64
 36  Sprint Speed      19018 non-null  float64
 37  Agility           19019 non-null  float64
 38  Reactions         19017 non-null  float64
 39  Balance           19014 non-null  float64
 40  Power             19020 non-null  float64
 41  Shot Power        19019 non-null  float64
 42  Jumping           19017 non-null  float64
 43  Stamina           19020 non-null  float64
 44  Strength          19016 non-null  float64
 45  Long Shots        19014 non-null  float64
 46  Mentality         19015 non-null  float64
 47  Aggression        19021 non-null  int64
 48  Interceptions     19017 non-null  float64
 49  Positioning       19020 non-null  float64
 50  Vision            19021 non-null  int64
 51  Penalties         19020 non-null  float64
 52  Composure         19020 non-null  float64
 53  Defending         19020 non-null  float64
 54  Marking           19019 non-null  float64
 55  Standing Tackle   19018 non-null  float64
 56  Sliding Tackle    19020 non-null  float64
 57  Goalkeeping       19018 non-null  float64
 58  GK Diving         19020 non-null  float64
 59  GK Handling       19020 non-null  float64
 60  GK Kicking        19019 non-null  float64
 61  GK Positioning    19019 non-null  float64
 62  GK Reflexes       19021 non-null  int64
 63  Total Stats       19020 non-null  float64
 64  Base Stats        19021 non-null  int64
 65  W/F               19021 non-null  object
 66  SM                19021 non-null  object
 67  A/W               19021 non-null  object
 68  D/W               19020 non-null  object
 69  IR                19021 non-null  object
 70  PAC               19018 non-null  float64
 71  SHO               19018 non-null  float64
 72  PAS               19016 non-null  float64
 73  DRI               19019 non-null  float64
 74  DEF               19016 non-null  float64
 75  PHY               19020 non-null  float64
 76  Hits              16426 non-null  object
dtypes: float64(45), int64(7), object(25)
memory usage: 11.2+ MB

In [6]:
# data contains 19021 samples(rows) of 77 features (columns)
# There are 45 floating; 7 integer and 25 categorical/object data types
#There are several features with missing values

# Completing the subtasks

Sub Tasks
1. Extract the player names from the PlayerUrl column and create a new column name Player
Name from the extracts
2. Create a new column titled Player Status from the CONTRACT column with 3 labels ;
a. 'Active' If the player has an active contract
b. 'Free', if the player is free
c. 'On Loan' if the player is on loan
3. Unpack the POSITIONS column into as many columns as there are positions and assign Boolean
values in the columns for each player as appropriate. Name the columns the play position
4. Weight and Height, W/F, SM and IR Columns: convert to integers
5. Value, Wage and Release Clause columns: convert to Float
6. Inspect the HITS column and ensure its float
7. Create 5 new categorical columns for the Height, Weight, Release Clause, Value and Wage into
which you convert the respective values into clusters/labels as follows
a. Height: Bucket intervals of 10 years
b. Weight: Bucket intervals of 10 kg
c. Wage: bucket intervals of 50K
d. Value: bucket intervals of 50M
e. Release Clause: bucket intervals of 50M

A. BONUS: Build a prediction model to predict the number of Hits of each payer

#Task 1:
#Extracting the Player names from PlayerUrl

In [7]:
df_musket.playerUrl

0        http://sofifa.com/player/158023/lionel-messi/2...
1        http://sofifa.com/player/20801/c-ronaldo-dos-s...
2        http://sofifa.com/player/200389/jan-oblak/210006/
3        http://sofifa.com/player/192985/kevin-de-bruyn...
4        http://sofifa.com/player/190871/neymar-da-silv...
                               ...
19016       http://sofifa.com/player/247223/ao-xia/210006/
19017    http://sofifa.com/player/258760/ben-hough/210006/
19018    http://sofifa.com/player/252757/ronan-mckinley...
19019    http://sofifa.com/player/243790/zhenao-wang/21...
19020    http://sofifa.com/player/252520/xiao-zhou/210006/
Name: playerUrl, Length: 19021, dtype: object

#Spliting the Url into parts

In [8]:
df_musket.playerUrl.values[12500].split('/')

['http:', '', 'sofifa.com', 'player', '227446', 'kevin-van-veen', '210006', '']

In [9]:
df_musket.playerUrl.values[12500].split('/')[-3]

'kevin-van-veen'

In [10]:
playerList = []
for item in df_musket.playerUrl.values:
    player = item.split('/')[-3]
    player = player.replace('-',' ')
    playerList.append(player)
playerList

['lionel messi',
 'c ronaldo dos santos aveiro',
 'jan oblak',
 'kevin de bruyne',
 'neymar da silva santos jr',
 'robert lewandowski',
 'mohamed salah',
 'alisson ramses becker',
 'kylian mbappe',
 'marc andre ter stegen',
 'virgil van dijk',
 'sadio mane',
 'carlos henrique venancio casimiro',
 'thibaut courtois',
 'manuel neuer',
 'karim benzema',
 'sergio ramos garcia',
 'sergio aguero',
 'raheem sterling',
 'ngolo kante',
 'joshua kimmich',
 'paulo dybala',
 'ederson santana de moraes',
 'harry kane',
 'samir handanovic',
 'kalidou koulibaly',
 'eden hazard',
 'toni kroos',
 'antoine griezmann',
 'jadon sancho',
 'trent alexander arnold',
 'bernardo mota carvalho e silva',
 'andrew robertson',
 'aymeric laporte',
 'bruno miguel borges fernandes',
 'fabio henrique tavares',
 'heung min son',
 'roberto firmino barbosa de oliveira',
 'keylor navas',
 'giorgio chiellini',
 'sergio busquets burgos',
 'pierre emerick aubameyang',
 'wojciech szczesny',
 'angel di maria',
 'luka modric',
 'luis suarez',
 'hugo lloris',
 'ciro immobile',
 'thomas muller',
 'david de gea quintana',
 'daniel carvajal ramos',
 'raphael varane',
 'marco verratti',
 'paul pogba',
 'jamie vardy',
 'gerard pique bernabeu',
 'mats hummels',
 'yann sommer',
 'david josue jimenez silva',
 'alejandro gomez',
 'jordi alba ramos',
 'jordan henderson',
 'rodrigo hernandez cascante',
 'sergej milinkovic savic',
 'memphis depay',
 'kai havertz',
 'matthijs de ligt',
 'milan skriniar',
 'marcus rashford',
 'gianluigi donnarumma',
 'serge gnabry',
 'leroy sane',
 'hakim ziyech',
 'clement lenglet',
 'marcos aoas correa',
 'riyad mahrez',
 'ricardo barbosa pereira',
 'timo werner',
 'daniel parejo munoz',
 'mauro icardi',
 'frenkie de jong',
 'lorenzo insigne',
 'toby alderweireld',
 'thiago emiliano da silva',
 'jorge resurreccion',
 'bernd leno',
 'romelu lukaku',
 'alex sandro lobo silva',
 'thiago alcantara',
 'kyle walker',
 'christian eriksen',
 'peter gulacsi',
 'leonardo bonucci',
 'dries mertens',
 'luis alberto romero alconchel',
 'diego godin',
 'georginio wijnaldum',
 'miralem pjanic',
 'marco reus',
 'wilfred ndidi',
 'jose maria gimenez',
 'andre onana',
 'julian brandt',
 'mikel oyarzabal ugarte',
 'lautaro martinez',
 'erling haaland',
 'alex nicolao telles',
 'kingsley coman',
 'alejandro grimaldo garcia',
 'arthur henrique ramos oliveira melo',
 'niklas sule',
 'raphael guerreiro',
 'anthony martial',
 'felipe augusto de almeida monteiro',
 'leon goretzka',
 'saul niguez esclapez',
 'thomas partey',
 'wissam ben yedder',
 'nicolas tagliafico',
 'raul jimenez',
 'marcelo brozovic',
 'lucas digne',
 'roman burki',
 'josip ilicic',
 'jose maria callejon bueno',
 'luis miguel afonso fernandes',
 'francisco roman alarcon suarez',
 'david alaba',
 'idrissa gueye',
 'jesus corona',
 'iago aspas juncal',
 'douglas costa de souza',
 'stefan de vrij',
 'fernando luiz rosa',
 'lucas pezzini leiva',
 'cesar azpilicueta tanco',
 'salvatore sirigu',
 'kasper schmeichel',
 'axel witsel',
 'rui pedro dos santos patricio',
 'edinson cavani',
 'jesus navas gonzalez',
 'achraf hakimi',
 'ferland mendy',
 'ousmane dembele',
 'thorgan hazard',
 'ronaldo jailson cabrais petri',
 'aaron wan bissaka',
 'denis zakaria',
 'nabil fekir',
 'marcos acuna',
 'steven bergwijn',
 'joe gomez',
 'martin odegaard',
 'donny van de beek',
 'pau lopez sabata',
 'martin dubravka',
 'diego carlos santos silva',
 'federico valverde',
 'gerard moreno balaguero',
 'gabriel fernando de jesus',
 'rafael a ferreira silva',
 'lucas rodrigues m silva',
 'thomas strakosha',
 'filip kostic',
 'jose luis gaya pena',
 'dele alli',
 'joao pedro cavaco cancelo',
 'alessio romagnoli',
 'juan bernat velasco',
 'edin visca',
 'samuel umtiti',
 'luiz frello filho jorge',
 'cristian portugues manzanera',
 'marcel sabitzer',
 'duvan zapata',
 'mateo kovacic',
 'nelson cabral semedo',
 'fernando reges',
 'dusan tadic',
 'blaise matuidi',
 'kieran trippier',
 'sergio roberto carnicer',
 'anthony lopes',
 'charles aranguiz',
 'joel matip',
 'aitor fernandez',
 'alexandre lacazette',
 'wilfried zaha',
 'kostas manolas',
 'lukas hradecky',
 'iker muniain goni',
 'philippe coutinho correia',
 'oscar dos santos emboaba',
 'koen casteels',
 'francesco acerbi',
 'ilkay gundogan',
 'kevin trapp',
 'jose paulo bezerra m junior',
 'yuri berchiche izeta',
 'allan marques loureiro',
 'arturo vidal',
 'edin dzeko',
 'radja nainggolan',
 'marcelo vieira da silva',
 'gareth bale',
 'ever banega',
 'jan vertonghen',
 'steve mandanda',
 'zlatan ibrahimovic',
 'carlos vela',
 'joao filipe moutinho',
 'gonzalo higuain',
 'renato augusto',
 'lucas hernandez',
 'dakonam djene',
 'florian thauvin',
 'jiri pavlenka',
 'josue durval chiamulera vaz',
 'giovani lo celso',
 'marcos llorente moreno',
 'nicolas pepe',
 'konrad laimer',
 'ruben diogo da silva neves',
 'david soria solis',
 'robin gosens',
 'marco asensio willemsen',
 'yannick carrasco',
 'sergio reguilon rodriguez',
 'andrej kramaric',
 'quincy promes',
 'mike maignan',
 'lucas ocampos',
 'kepa arrizabalaga',
 'emre can',
 'matthias ginter',
 'fernando pacheco flores',
 'marcel halstenberg',
 'anderson souza conceicao',
 'angel correa',
 'geronimo rulli',
 'fabian ruiz pena',
 'tomas vaclik',
 'raphael william anjos rochedo',
 'harry maguire',
 'daley blind',
 'nick pope',
 'rodrigo moreno machado',
 'alphonse areola',
 'mario figueira fernandes',
 'norberto murara neto',
 'mattia perin',
 'agustin marchesin',
 'james rodriguez',
 'danilo luis helio pereira',
 'alvaro borja morata martin',
 'gabriel armando de abreu',
 'sergio canales madrazo',
 'karim bellarabi',
 'oliver baumann',
 'sergio asenjo andres',
 'lars bender',
 'gianluigi buffon',
 'aaron ramsey',
 'raul albiol tortajada',
 'mesut ozil',
 'dimitri payet',
 'ivan rakitic',
 'willian borges da silva',
 'marko arnautovic',
 'fernando muslera',
 'aleksandar kolarov',
 'jerome boateng',
 'ivan perisic',
 'houssem aouar',
 'manuel lazzari',
 'marc cucurella saseta',
 'ruben santos gato alves dias',
 'moussa diaby',
 'ferran torres garcia',
 'joao felix sequeira',
 'renan augusto lodi dos santos',
 'raphael dias belloli',
 'josef martinez',
 'alphonso davies',
 'rosberto j dourado santos',
 'richarlison de andrade',
 'marvin oswaldo rangel azevedo',
 'nuno ailton padrenda mendes',
 'welington kaue dano nascimento',
 'lourival adnan beretta barbosa',
 'adryan juliano zonta torres',
 'juan everton mestres de mesquita',
 'ben chilwell',
 'christian pulisic',
 'tomas soucek',
 'marko dmitrovic',
 'wout weghorst',
 'presnel kimpembe',
 'ander capa rodriguez',
 'luke shaw',
 'youri tielemans',
 'matteo politano',
 'james maddison',
 'naby keita',
 'everton sousa soares',
 'lucas torreira',
 'inaki williams arthuer',
 'davinson sanchez',
 'jonathan castro otto',
 'ignacio fernandez',
 'joaquin correa',
 'walter benitez',
 'thomas lemar',
 'odisseas vlachodimos',
 'moussa dembele',
 'adrien rabiot',
 'frederico de paula santos',
 'goncalo manuel ganchinho guedes',
 'marten de roon',
 'benjamin pavard',
 'thomas delaney',
 'jordi masip lopez',
 'xherdan shaqiri',
 'sebastian coates',
 'kevin kampl',
 'alessio cragno',
 'antonio rudiger',
 'arkadiusz milik',
 'jordan pickford',
 'stefan savic',
 'eran zahavi',
 'santiago arias',
 'alessandro florenzi',
 'jesus joaquin fernandez saez',
 'benjamin mendy',
 'felipe anderson pereira gomes',
 'matt doherty',
 'kevin volland',
 'francisco alcacer garcia',
 'steven berghuis',
 'jasper cillessen',
 'pablo sarabia garcia',
 'thomas meunier',
 'sebastien haller',
 'simon mignolet',
 'ismaily goncalves dos s',
 'jonathan viera ramos',
 'sven bender',
 'juan cuadrado',
 'andres iniesta lujan',
 'marcos alonso mendoza',
 'mario gotze',
 'eduardo salvio',
 'marlos romero bonfim',
 'max kruse',
 'sami khedira',
 'javier martinez aginaga',
 'taison barcellos freda',
 'ivan marcano sierra',
 'marek hamsik',
 'stephane ruffier',
 'lukasz fabianski',
 'andrea consigli',
 'franck ribery',
 'hector herrera',
 'kepler laveran lima ferreira',
 'esteban andrada',
 'andre pierre gignac',
 'jaime nicolas frendado',
 'vinicius jose de oliveira junior',
 'maximiliano gomez',
 'dominik livakovic',
 'viktor tsygankov',
 'jorge ezequiel serendero',
 'mauro evidio nerez',
 'matias david baldona',
 'saul marcelo ardero',
 'luis roberto dalves',
 'egidio maestre schetino',
 'jose maria sildero',
 'tanguy ndombele',
 'ben davies',
 'david neres campos',
 'christopher nkunku',
 'dean henderson',
 'caglar soyuncu',
 'eder gabriel militao',
 'unai simon mendibil',
 'mason mount',
 'mauro arambarri',
 'theo hernandez',
 'luka jovic',
 'tony josimar abranjes meneses',
 'marcus thuram',
 'oleksandr zinchenko',
 'laureano thomas santeiro marre',
 'segundo mandiquez',
 'maikel renan catarino fagundes',
 'leon bailey',
 'mario hermoso canseco',
 'yeray alvarez lopez',
 'nordi mukiele',
 'alejandro remiro gargallo',
 'stefan lainer',
 'daniel ceballos fernandez',
 'mikel merino zazon',
 'allan saint maximin',
 'heniton enaldo pires tramontino',
 'diogo jose teixeira da silva',
 'nicolo barella',
 'valentin rongier',
 'otavio edmilson da silva monteiro',
 'lukas klostermann',
 'hirving lozano',
 'victor lindelof',
 'jose angel esmoris tasende',
 'matias vecino',
 'corentin tolisso',
 'juan musso',
 'piotr zielinski',
 'pierre emile hojbjerg',
 'alassane plea',
 'gelson dany batalha martins',
 'jack grealish',
 'william silva de carvalho',
 'adnan januzaj',
 'andrea belotti',
 'franco armani',
 'lucas vazquez iglesias',
 'domenico berardi',
 'ruben pena jimenez',
 'daniele rugani',
 'kerem demirbay',
 'federico bernardeschi',
 'joao mario naval costa eduardo',
 'inigo martinez berridi',
 'nikola vlasic',
 'sime vrsaljko',
 'julian draxler',
 'granit xhaka',
 'jose gomez campana',
 'nico schulz',
 'jose ignacio fernandez iglesias',
 'benjamin lecomte',
 'martin hinteregger',
 'gerard deulofeu lazaro',
 'adem ljajic',
 'jerome roussillon',
 'willy boly',
 'john stones',
 'pavel kaderabek',
 'hector bellerin moruno',
 'damian suarez',
 'james tarkowski',
 'cedric bakambu',
 'asier illarramendi',
 'mathew ryan',
 'benjamin andre',
 'ricardo goulart pereira',
 'mario gaspar perez martinez',
 'henrikh mkhitaryan',
 'sergio escudero palomo',
 'willian jose da silva',
 'danny ings',
 'marc bartra aregall',
 'enzo perez',
 'grzegorz krychowiak',
 'andre gomes magalhaes almeida',
 'serge aurier',
 'givanildo vieira de souza',
 'luuk de jong',
 'nemanja matic',
 'joao miranda de souza filho',
 'sebastian giovinco',
 'ignacio monreal eraso',
 'antonio adan garrido',
 'branislav ivanovic',
 'simon kjaer',
 'diego da silva costa',
 'david luiz moreira marinho',
 'giuliano victor de paula',
 'sergio romero',
 'luiz gustavo dias',
 'lars stindl',
 'nicolas nkoulou',
 'giacomo bonaventura',
 'vicente guaita panadero',
 'francis coquelin',
 'lukasz piszczek',
 'alexis sanchez',
 'kurt zouma',
 'bafetimbi gomis',
 'daniel wass',
 'arjen robben',
 'raul garcia escudero',
 'erik lamela',
 'radamel falcao garcia zarate',
 'mousa dembele',
 'jonny evans',
 'pedro rodriguez ledesma',
 'igor akinfeev',
 'luis carlos almeida da cunha',
 'james milner',
 'joaquin sanchez rodriguez',
 'fabio quagliarella',
 'leandro miguel sareda',
 'aluisio chaves rib moraes junior',
 'enzo martin riquero',
 'rafael di leonardo',
 'edgar manuel guichon',
 'morgan sanson',
 'carlos vinicius alves morais',
 'daniel olmo carvajal',
 'rodrygo silva de goes',
 'dan axel zagadou',
 'predrag rajkovic',
 'jules kounde',
 'hector junior firpo adames',
 'youcef atal',
 'nemanja maksimovic',
 'pervis estupinan',
 'phil foden',
 'enis bardhi',
 'sander berge',
 'scott mctominay',
 'florian neuhaus',
 'denzel dumfries',
 'harvey barnes',
 'jonathan ikone',
 'boubacar kamara',
 'declan rice',
 'carlos soler barragan',
 'alvaro odriozola arzalluz',
 'igor zubeldia elorza',
 'alexander isak',
 'victor osimhen',
 'ruslan malinovskyi',
 'luan vagner boas macedo',
 'bernard gabriel prestao chaves',
 'melvin luan parrela porfirio',
 'everton jorge andrade zanon',
 'adnan claudiano vidual machado',
 'ronaldo diego esler domingues',
 'dayot upamecano',
 'milot rashica',
 'andre miguel valente da silva',
 'kasper dolberg',
 'ezequiel avila',
 'lorenzo pellegrini',
 'jaime mata arnaiz',
 'moussa marega',
 'leo dubois',
 'pablo fornals malla',
 'alexandr golovin',
 'hamari traore',
 'eric bailly',
 'duje caleta car',
 'joan jordan moreno',
 'cristian pavon',
 'borja iglesias quintas',
 'petros matheus dos santos araujo',
 'ramy bensebaini',
 'tiemoue bakayoko',
 'dominic calvert lewin',
 'munir el haddadi',
 'jason denayer',
 'joseba zaldua bengoetxea',
 'ante rebic',
 'julian weigl',
 'baptiste santamaria',
 'emerson palmieri dos santos',
 'harry winks',
 'adama traore diarra',
 'joao paulo dias fernandes',
 'jose luis morales nogales',
 'daniel garcia carrillo',
 'armando izzo',
 'ayoze perez gutierrez',
 'milton casco',
 'dario benedetto',
 'wilmar barrios',
 'alexey miranchuk',
 'frank fabra',
 'abderrazak hamdallah',
 'andreas christensen',
 'ricardo jorge da luz horta',
 'jonathan tah',
 'jose pedro malheiro de sa',
 'philipp max',
 'andre filipe tavares gomes',
 'pierluigi gollini',
 'valentino lazaro',
 'rodrigo bentancur',
 'ruben garcia santos',
 'edouard mendy',
 'luis muriel',
 'alejandro pozuelo melero',
 'fernando lucas martins',
 'nicolas otamendi',
 'rui tiago dantas da silva',
 'nathan ake',
 'omar mascarell gonzalez',
 'munas dabbur',
 'emil forsberg',
 'hakan calhanoglu',
 'matheus lima magalhaes',
 'ryan fraser',
 'leandro paredes',
 'maximilian arnold',
 'taras stepanenko',
 'luka milivojevic',
 'james ward prowse',
 'willi orban',
 'mario rui silva duarte',
 'kenny lala',
 'andre carrillo',
 'alvaro gonzalez soberon',
 'alexander schwolow',
 'gabriel appelt pires',
 'pedro leon sanchez gil',
 'kesen ai',
 'samuel castillejo azuaga',
 'ibai gomez perez',
 'faouzi ghoulam',
 'rafael alcantara',
 'jordan veretout',
 'aissa mandi',
 'marco bizot',
 'victor machin perez',
 'matz sels',
 'nicolas lodeiro',
 'lucas perez martinez',
 'danilo luiz da silva',
 'joao pedro g santos galvao',
 'geoffrey kondogbia',
 'alex oxlade chamberlain',
 'andy delort',
 'nemanja gudelj',
 'jaume vicent costa jorda',
 'conor coady',
 'fabian orellana',
 'salif sane',
 'ander herrera aguera',
 'stephan el shaarawy',
 'jose angel valdes diaz',
 'chris smalling',
 'ben mee',
 'vicente iborra de la fuente',
 'francesco caputo',
 'alex teixeira dos santos',
 'steven nzonzi',
 'artem dzyuba',
 'sven ulreich',
 'cristhian stuani',
 'sofiane feghouli',
 'gylfi sigurdhsson',
 'diego perotti',
 'marco parolo',
 'moussa sissoko',
 'nordin amrabat',
 'sidnei rechel da silva junior',
 'vitorino pacheco antunes',
 'vedran corluka',
 'seamus coleman',
 'yann mvila',
 'olivier giroud',
 'danny rose',
 'angel luis rodriguez diaz',
 'juan manuel mata garcia',
 'mathieu valbuena',
 'marcelo diaz',
 'nahuel guzman',
 'kevin gameiro',
 'kevin mbabu',
 'sokratis papastathopoulos',
 'diego valeri',
 'david ospina',
 'laurent koscielny',
 'ben foster',
 'benoit costil',
 'javier mascherano',
 'guillermo ochoa',
 'jose manuel reina paez',
 'ricardo andrade quaresma bernardo',
 'marcio rafael ferreira de souza',
 'eder citadin martins',
 'antony matheus dos santos',
 'enzo manuel aguerro',
 'vladimir coufal',
 'francisco mota castro trincao',
 'daniel martin lenzado',
 'bruno guimaraes moura',
 'sebastian bruno luna',
 'emerson leite de souza',
 'edmond tapsoba',
 'luis manuel arantes maximiano',
 'ondrej kolar',
 'lisandro martinez',
 'dwight mcneil',
 'lorenzo moron garcia',
 'anthony nwakaeme',
 'pau francisco torres',
 'luis diaz',
 'unai nunez gestoso',
 'teun koopmeiners',
 'matheus santos carneiro da cunha',
 'oscar melendo jimenez',
 'ibrahima konate',
 'matias rojas',
 'stefano sensi',
 'calvin stengs',
 'alban lafont',
 'federico chiesa',
 'matheus jadson bardeira cunha',
 'cengiz under',
 'domingos sousa menezes duarte',
 'patrik schick',
 'gabriel dos s magalhaes',
 'donyell malen',
 'tammy abraham',
 'gonzalo montiel',
 'miguel almiron',
 'renato junior luz sanches',
 'jonathan prazeres conradi',
 'fabian schar',
 'ismaila sarr',
 'fred claudinei tofoli vilela',
 'arturo adolfo inalcio dutra',
 'g pierre paiva souza',
 'alberto marcelo dutra cirino',
 'everton jorge simao resende',
 'vincente filho dourado hermes',
 'a benjamin chiamuloira paes',
 'wellingt edson sabrao rolim',
 'gerson adriano gutierres serra',
 'falaye sacko',
 'pierre lees melou',
 'breel embolo',
 'joao maria palhinha goncalves',
 'jordan amavi',
 'florian grillitsch',
 'daniel castelo podence',
 'kieran tierney',
 'benjamin verbic',
 'abdou diallo',
 'alex meret',
 'jonathan bamba',
 'paul bernardoni',
 'jonathan rodriguez',
 'ruben aguilar',
 'krzysztof piatek',
 'karl toko ekambi',
 'jaume domenech sanchez',
 'hans hateboer',
 'jonathan rodriguez menendez',
 'jean pierre nsame',
 'manuel locatelli',
 'nico elvedi',
 'lei wu',
 'rafael santos borre',
 'yerry mina',
 'mattia caldara',
 'angel mena',
 'franco cervi',
 'marcos paulo mesquita lopes',
 'samuel gigot',
 'nuno miguel jeronimo sequeira',
 'stanislav lobotka',
 'marcelo augusto ferreira teixeira',
 'davide zappacosta',
 'ivan marcone',
 'jean philippe gbamin',
 'carlos izquierdoz',
 'benjamin bourigeaud',
 'mateus uribe',
 'ruben loftus cheek',
 'roman zobnin',
 'leander dendoncker',
 'jack oconnell',
 'ricardo sousa esgaio',
 'jose ignacio martinez garcia',
 'roberto gagliardini',
 'vincenzo grifo',
 'florian niederlechner',
 'elseid hysaj',
 'renato steffen',
 'darwin machis',
 'raul de tomas gomez',
 'jhon cordoba',
 'manuel akanji',
 'youssef en nesyri',
 'suat serdar',
 'miguel angel moya rumbo',
 'sead kolasinac',
 'christoph kramer',
 'burak yilmaz',
 'hiroki sakai',
 'romain saiss',
 'bryan cristante',
 'abdoulaye doucoure',
 'yussuf poulsen',
 'michael keane',
 'robin olsen',
 'luciano vietto',
 'leandro trossard',
 'manuel trigueros munoz',
 'mattia de sciglio',
 'leonardo carrilho baptistao',
 'zouhair feddal',
 'teji savanier',
 'bernard anicio caldeira duarte',
 'filip novak',
 'denis suarez fernandez',
 'takashi inui',
 'john egan',
 'michy batshuayi',
 'jan boril',
 'loris karius',
 'emiliano martinez',
 'younes belhanda',
 'maicon pereira roque',
 'florent mollet',
 'djibril sidibe',
 'hans vanaken',
 'cristian tello herrera',
 'nacer chadli',
 'danny da costa',
 'eric dier',
 'pablo nascimento castro',
 'ciprian tatarusanu',
 'remo freuler',
 'diego demme',
 'nicolas pallois',
 'lewis dunk',
 'patrick herrmann',
 'domagoj vida',
 'ross barkley',
 'kevin malcuit',
 'nathan redmond',
 'fredrik midtsjo',
 'hugo mallo novegil',
 'tom heaton',
 'oscar de marcos arana',
 'leonardo spinazzola',
 'mbaye niang',
 'jonas svensson',
 'martin skrtel',
 'bas dost',
 'christian gunter',
 'ryan bertrand',
 'guilherme alvim marinato',
 'gervais yao kouassi',
 'dieumerci mbokani',
 'celso ortiz',
 'stefan radu',
 'ignacio piatti',
 'cristian ansaldi',
 'rogelio funes mori',
 'michail antonio',
 'sergio miguel relvas de oliveira',
 'marwin hitz',
 'victor laguardia cisneros',
 'youssef el arabi',
 'german pezzella',
 'ricardo rodriguez',
 'iago herrerin buisan',
 'enda stevens',
 'chris wood',
 'alexandr kokorin',
 'shkodran mustafi',
 'luis rodriguez',
 'ashley westwood',
 'callum wilson',
 'manuel lanzini',
 'kevin prince boateng',
 'senad lulic',
 'antonio mirante',
 'lautaro acosta',
 'matias suarez',
 'rafael de souza pereira',
 'mateo musacchio',
 'josuha guilavogui',
 'victor david diaz miguel',
 'papakouli diop',
 'etienne capoue',
 'felipe caicedo',
 'pablo piatti',
 'antonio candreva',
 'mathieu debuchy',
 'carlos tevez',
 'domenico criscito',
 'jose sosa',
 'jorge molina vidal',
 'andres eduardo fernandez moreno',
 'jose miguel da rocha fonte',
 'andres guardado',
 'victor moses',
 'lisandro lopez',
 'gaston ramirez',
 'lucas luciano mantela patricio',
 'timothy castagne',
 'roberto pereyra',
 'layvin kurzawa',
 'isaac hayden',
 'harry wilson',

#Assigning player list to a new column named PlayerName

In [11]:
df_musket['PlayerName'] = playerList

#confirming that PlayerName is now a new column of the data

In [12]:
df_musket.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'PlayerName'],
      dtype='object')

#Task 2
2. Create a new column titled Player Status from the CONTRACT column with 3 labels ;
a. 'Active' If the player has an active contract
b. 'Free', if the player is free
c. 'On Loan' if the player is on loan

In [13]:
df_musket.Contract

0        2004 ~ 2021
1        2018 ~ 2022
2        2014 ~ 2023
3        2015 ~ 2023
4        2017 ~ 2022
            ...
19016    2018 ~ 2022
19017    2020 ~ 2021
19018    2019 ~ 2020
19019    2020 ~ 2022
19020    2019 ~ 2023
Name: Contract, Length: 19021, dtype: object

In [14]:
df_musket.Contract.unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 2028',
       '2010 ~ 2023', '2014 ~ 2021', '2015 ~ 2025', '2014 ~ 2026',
       '2012 ~ 2025', '2017 ~ 2020', '2002 ~ 2022', '2020 ~ 2027',
       '2013 ~ 2025', 'Dec 31, 2020 On Loan', '2019 ~ 2020',
       '2011 ~ 2025', '2016 ~ 2020', '2007 ~ 2021', '2020 ~ 2026',
       '2010 ~ 2025', '2009 ~ 2023', '2008 ~ 2021', '2020 ~ 2020',
       '2016 ~ 2026', 'Jan 30, 2021 On Loan', '2012 ~ 2020',
       '2014 ~ 2025', 'Jun 30, 2022 On Loan', '2015 ~ 2020',
       'May 31, 2021 On Loan', '2018 ~ 2020', '2014 ~ 2020',
       '2013 ~ 2020', '2006 ~ 2024', 'Jul 5, 2021 On Loan',
       'Dec 31, 2021 On Loan', '2004 ~ 2025', '2011 ~ 2020',
       'Jul 1, 2021 On Loan', 'Jan 1, 2021 On Loan', '2006 ~ 2023',
       'Aug 31, 2021 On Loan', '2006 ~ 2021', '2005 ~ 2023',
       '2003 ~ 2020', '2009 ~ 2020', '2002 ~ 2020', '2005 ~ 2020',
       '2005 ~ 2022', 'Jan 31, 2021 On Loan', '2010 ~ 2020',
       'Dec 30, 2021 On Loan', '2008 ~ 2020', '2007 ~ 2020',
       '2003 ~ 2021', 'Jun 23, 2021 On Loan', 'Jan 3, 2021 On Loan',
       'Nov 27, 2021 On Loan', '2002 ~ 2021', 'Jan 17, 2021 On Loan',
       'Jun 30, 2023 On Loan', '1998 ~ 2021', '2003 ~ 2022',
       '2007 ~ 2023', 'Jul 31, 2021 On Loan', 'Nov 22, 2020 On Loan',
       'May 31, 2022 On Loan', '2006 ~ 2020', 'Dec 30, 2020 On Loan',
       '2007 ~ 2025', 'Jan 4, 2021 On Loan', 'Nov 30, 2020 On Loan',
       '2004 ~ 2020', '2009 ~ 2025', 'Aug 1, 2021 On Loan'], dtype=object)

In [15]:
df_musket['Contract'].isna().sum() #checking for missing value

0

In [16]:
contList = []
for item in df_musket.Contract.values:
    if 'Free' in item:
        contList.append('Free')
    elif 'On Loan' in item:
        contList.append('On Loan')
    else:
        contList.append('Active')
contList

['Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Active',
 'Active',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Free',
 'Free',
 'Free',
 'Free',
 'Free',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Active',
 'Free',
 'Free',
 'Free',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Active',
 'Active',
 'Free',
 'Active',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Free',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'On Loan',
 'On Loan',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 'Active',
 ...]

In [17]:
df_musket['PlayerStatus'] = contList

#Confirming that PlayerStatus column is added

In [18]:
df_musket.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'PlayerName', 'PlayerStatus'],
      dtype='object')

In [19]:
df_musket.Positions.unique()

array(['RW, ST, CF', 'ST, LW', 'GK', 'CAM, CM', 'LW, CAM', 'ST', 'RW',
       'ST, LW, RW', 'CB', 'LW', 'CDM', 'CF, ST', 'LW, RW', 'CDM, CM',
       'CDM, RB', 'CF, CAM', 'LW, ST', 'CM', 'ST, CF, LW', 'RM, LM, CAM',
       'RB', 'RW, CAM, CM', 'LB', 'LM, CF', 'CF', 'RW, LW', 'CAM, RM, RW',
       'CM, CDM', 'CAM, CF, ST', 'CM, CDM, CAM', 'CF, LW, CAM',
       'CAM, RM, CF', 'LM, ST', 'RM, LM, RW', 'LM', 'CAM, RW', 'CB, CDM',
       'RW, RM', 'LW, CF', 'CM, RM, LM', 'LB, LM', 'CAM, CM, RM',
       'CAM, CM, CF', 'CAM, CF', 'LM, RM, LW', 'LM, LB, CM', 'CM, LM, LB',
       'RM, RW', 'RM, CM', 'CAM, CM, LW', 'CB, LB', 'RM, RB', 'ST, RW',
       'LM, RW, LW', 'RB, LB', 'RB, RM', 'RM', 'LM, RM, CF', 'CAM, RM',
       'RB, RWB', 'CDM, CB, CM', 'CAM, RM, ST', 'LM, LW, RM', 'CM, CAM',
       'ST, RM, CF', 'LM, RM', 'RM, CF', 'LM, LWB', 'RW, RM, CF',
       'RB, CM', 'LW, CAM, RW', 'CAM, LW, CM', 'CM, CAM, CDM',
       'RW, LW, CAM', 'CM, CAM, LM', 'CM, RM, ST', 'CDM, CM, RB',
       'ST, CAM', 'CAM, LW, ST', 'LB, CB, LWB', 'RM, ST', 'CB, CDM, LB',
       'RWB, RM', 'CM, LM, RM', 'RB, CDM, CM', 'RW, LW, RM', 'LM, LW',
       'CM, LM', 'LM, LB', 'RM, LM, CF', 'LB, LM, RM', 'CDM, CM, CAM',
       'ST, LW, RM', 'CAM, CM, ST', 'ST, CF', 'LWB, LB', 'LW, RW, LM',
       'RM, RW, ST', 'LWB', 'CF, ST, CAM', 'LM, CAM, RM', 'RB, CB',
       'ST, LM', 'RW, CAM', 'LM, CAM', 'RWB, RB', 'ST, RW, LW', 'CAM',
       'RB, RM, RW', 'LB, LWB', 'RM, CAM', 'CAM, ST', 'CDM, CB',
       'CF, LM, LW', 'CAM, LM, LW', 'LW, RW, CAM', 'CB, RB',
       'RB, CB, RWB', 'LM, LW, ST', 'LW, ST, CM', 'RM, CAM, CM',
       'CB, RB, RWB', 'RW, ST, LW', 'LW, CAM, CM', 'CM, LM, CDM',
       'LB, LM, LWB', 'CB, LB, RB', 'CAM, LW', 'RWB, RB, RM',
       'CF, CAM, ST', 'RM, CAM, RW', 'RW, ST', 'LW, LM', 'RB, RM, CM',
       'ST, CAM, RW', 'CM, RB, LB', 'CAM, LM, RM', 'RB, RW', 'LM, CM',
       'RM, LM, CM', 'CDM, CM, CB', 'CM, CF', 'CF, LW, RW', 'ST, RM',
       'CAM, CM, CDM', 'LB, CB', 'RW, RWB', 'ST, LM, RM', 'RM, RWB, RB',
       'LM, ST, CAM', 'CAM, ST, CF', 'LW, CM', 'RB, RWB, LB', 'RM, LM',
       'CM, CAM, RM', 'ST, LW, CAM', 'RM, RW, CAM', 'CM, CDM, RM',
       'RB, RM, RWB', 'CDM, CB, LB', 'CAM, ST, LM', 'LM, CM, RM',
       'CF, RW', 'CAM, RM, LW', 'CM, RM, CDM', 'LB, LWB, LM',
       'LW, RW, CF', 'LW, LM, CAM', 'LWB, LW, LB', 'CDM, CM, LM',
       'CB, CM', 'RWB, RW, RB', 'ST, RW, RM', 'LW, RW, CM', 'LM, RM, CAM',
       'LB, RB', 'RWB, RM, RB', 'LM, RB, LB', 'LW, LM, ST', 'ST, RM, LM',
       'CAM, CM, LM', 'CF, CM', 'LW, ST, RW', 'ST, CAM, CF', 'LB, CB, LM',
       'CM, CDM, LM', 'RM, RWB', 'LB, LM, RB', 'RB, LB, CB',
       'CM, CDM, RB', 'LB, CM', 'CF, CAM, LW', 'RM, LWB', 'CF, ST, LM',
       'LB, RB, CB', 'LW, CF, ST', 'RM, ST, CAM', 'LW, RW, ST',
       'ST, LW, LM', 'CM, LW', 'CDM, CM, LB', 'CM, RM, CAM',
       'ST, CF, CAM', 'CM, LM, CAM', 'RWB', 'LM, ST, RM', 'CAM, RM, CM',
       'CAM, LM, CM', 'RW, LW, ST', 'CAM, RM, LM', 'CF, ST, LW',
       'LWB, LB, LM', 'RM, CM, CAM', 'LB, LM, CAM', 'CAM, CDM',
       'RW, RB, RM', 'RM, ST, RW', 'CM, CAM, LW', 'CF, ST, RW',
       'LM, RM, RB', 'LM, RM, CM', 'CB, RB, RM', 'RB, CDM', 'RM, ST, LM',
       'LB, LWB, CB', 'CDM, LB', 'LM, RM, ST', 'RWB, RB, LWB',
       'ST, LM, CAM', 'ST, RM, CAM', 'RB, RWB, RM', 'CF, LM, CAM',
       'CAM, CF, RW', 'RB, RM, LB', 'CDM, RWB', 'CM, RW, CAM',
       'ST, CF, LM', 'RM, LM, RWB', 'RB, LB, RM', 'LM, LW, LB',
       'RM, LM, ST', 'CAM, LM', 'ST, LM, LW', 'LW, RW, RM', 'CF, LW',
       'LB, CM, RB', 'RB, CB, CDM', 'CB, RB, LB', 'CAM, RW, RM',
       'LWB, LM', 'LW, CF, LM', 'CAM, CF, CM', 'LWB, CB', 'CM, CDM, LW',
       'LM, CM, LB', 'CM, RM', 'RW, LW, CF', 'CM, CDM, CB', 'LM, RM, RW',
       'RM, RW, LM', 'RM, CAM, LM', 'LWB, RM, LB', 'RM, LB, RB',
       'CM, CF, RM', 'RM, RB, LB', 'ST, LM, RW', 'CAM, ST, LW',
       'CF, LW, ST', 'LM, LW, CAM', 'RM, RW, CF', 'LW, LM, CF',
       'CM, RW, LW', 'LM, CM, CAM', 'CAM, RW, ST', 'CM, CAM, CF',
       'RW, LWB, LW', 'CB, RB, CDM', 'RW, RM, LW', 'LW, ST, LM',
       'RWB, RW', 'ST, CAM, LM', 'CM, CB', 'RM, RW, CM', 'LWB, CM',
       'RM, LM, LB', 'RM, CAM, ST', 'CDM, RM, RB', 'LM, LB, RB',
       'LB, RB, RWB', 'RM, RWB, CAM', 'CAM, LM, CF', 'LM, CAM, CM',
       'CF, CAM, RW', 'CDM, CM, RM', 'CF, CAM, CM', 'ST, RM, LW',
       'CB, CDM, CM', 'RB, RW, LB', 'ST, RW, CAM', 'CM, LB', 'LW, RM, RW',
       'CM, RM, RW', 'RM, CF, LM', 'CF, LM, RM', 'CAM, ST, RM', 'RW, CF',
       'CM, CAM, ST', 'CAM, CDM, CM', 'RM, RW, LW', 'CAM, LM, LB',
       'CAM, RW, LW', 'CDM, CAM', 'LWB, LM, LB', 'RW, LB', 'LW, CAM, CF',
       'RB, RWB, CB', 'LM, CF, RM', 'RB, LB, RWB', 'RM, LW',
       'CAM, LM, ST', 'LW, LM, LB', 'LB, RB, RM', 'CM, LWB',
       'CDM, RB, RM', 'RM, CM, RB', 'ST, RM, RW', 'LM, RM, LWB',
       'RW, LW, LM', 'LW, CF, RW', 'CM, CDM, LB', 'ST, LM, RB', 'LB, CDM',
       'CM, CB, CDM', 'CB, LB, CDM', 'RW, ST, RM', 'RM, ST, CF',
       'CAM, LW, LM', 'LM, ST, LW', 'CAM, RM, RB', 'RB, CM, RM',
       'CM, LW, LM', 'ST, CAM, RM', 'RW, ST, CAM', 'CM, LB, LM',
       'RB, CDM, RM', 'LM, RWB, RM', 'LM, CAM, LB', 'CAM, LW, RW',
       'CM, RM, RWB', 'RW, CAM, LW', 'RB, CB, LB', 'LB, LM, LW', 'RW, RB',
       'LM, LWB, CM', 'RM, CAM, RB', 'RM, CM, ST', 'RB, RM, LM',
       'LM, LB, LW', 'LM, ST, CF', 'RW, LWB, RM', 'LM, CAM, LW',
       'CB, RWB', 'RM, LW, CAM', 'LB, LW', 'CDM, CM, ST', 'LB, CM, CDM',
       'CF, CAM, LM', 'RW, CAM, RM', 'RW, LM, LW', 'RW, CM, CAM',
       'LM, LW, RW', 'RM, LW, RW', 'LW, LWB, RWB', 'RM, LM, RB',
       'CB, CDM, RB', 'CAM, RW, CM', 'ST, CAM, CM', 'LWB, LM, CM',
       'RW, LW, RWB', 'CB, LB, LWB', 'CM, LM, ST', 'CM, LWB, LM',
       'LB, LW, LM', 'RB, CM, CAM', 'RM, CAM, CF', 'CM, RW',
       'RW, RM, CAM', 'CB, LWB', 'CAM, RB', 'LM, CM, CDM', 'RM, LB, LM',
       'CB, RB, CM', 'RB, CM, RWB', 'LB, RB, LM', 'CAM, ST, RW',
       'LB, LW, RW', 'CDM, CAM, CM', 'CAM, ST, CM', 'LM, CAM, ST',
       'LM, ST, CM', 'CAM, CF, RM', 'CF, ST, RM', 'LM, ST, LB',
       'ST, CAM, LW', 'LWB, CM, LB', 'RWB, RM, LWB', 'LWB, LM, RB',
       'CM, LW, ST', 'LB, LM, CB', 'CM, RM, RB', 'RWB, CB', 'RM, RB, RWB',
       'LB, CM, LM', 'ST, LW, CF', 'RM, RWB, ST', 'CF, ST, CM',
       'LM, LB, LWB', 'LM, RW', 'LM, LWB, LB', 'LB, LWB, RB',
       'RM, RB, LM', 'RM, CM, LM', 'LW, ST, CAM', 'RB, RM, CB',
       'LWB, RWB, LB', 'CF, RM, RW', 'RM, CF, CAM', 'LM, LW, CF',
       'RB, LM, LB', 'CAM, CM, RW', 'LB, CM, LW', 'CM, CF, CAM',
       'RW, RM, ST', 'CDM, RB, CM', 'CM, RB', 'RB, RWB, RW', 'LM, RW, RM',
       'CM, RB, CDM', 'LM, RM, LB', 'CDM, RB, CB', 'RB, CB, RM',
       'RWB, LW, LM', 'ST, CF, RW', 'RM, CM, CDM', 'LM, CF, ST',
       'LW, CAM, LM', 'CDM, LM, CM', 'ST, CM, CAM', 'LM, RM, RWB',
       'CM, CAM, RW', 'CAM, LM, RW', 'LW, LM, RM', 'CAM, RW, CF',
       'LM, ST, RW', 'CB, LWB, LB', 'RW, CF, LW', 'CB, CM, CDM',
       'CB, CAM', 'LW, LB', 'CDM, RB, LB', 'ST, CM, RB', 'RWB, LWB, RB',
       'CM, CB, RB', 'LB, LW, RB', 'CF, RM, RWB', 'LB, RM', 'RM, RW, RB',
       'LB, RM, RB', 'CDM, RM, CM', 'CDM, LB, CM', 'LM, CDM, CM',
       'RW, LM, CAM', 'LM, LB, RM', 'RM, CF, ST', 'RW, CM', 'RM, RWB, LM',
       'CF, CM, ST', 'RW, RM, LM', 'LM, CM, RW', 'RWB, CM', 'RB, RM, CDM',
       'CM, CB, CAM', 'CF, CM, LM', 'RWB, LWB, RM', 'CF, RM',
       'CM, CF, ST', 'RWB, RB, CB', 'LWB, RWB', 'RM, LM, LW',
       'LW, RM, CM', 'LW, CAM, ST', 'ST, RM, RWB', 'ST, CM',
       'CDM, CM, RWB', 'LB, CB, RB', 'CB, ST, CAM', 'CF, RM, CM',
       'CDM, CB, RB', 'CM, LM, RB', 'RB, CB, LWB', 'LM, LB, CDM',
       'LW, LWB', 'RW, CF, CAM', 'RM, RB, CAM', 'LB, RB, CM',
       'RM, CDM, LM', 'LWB, LB, CB', 'LB, RB, CDM', 'RB, CM, LB',
       'CDM, RM', 'LM, RB, CB', 'RW, RWB, RM', 'RM, LW, ST',
       'LB, RB, LWB', 'RM, LM, CDM', 'RB, RM, CAM', 'RM, ST, LW',
       'CF, LM', 'RB, LB, CDM', 'RW, LW, RB', 'RB, RWB, CDM',
       'CM, CAM, LB', 'LW, RW, LWB', 'CB, LWB, RWB', 'LB, CB, CDM',
       'ST, RB, RM', 'CM, RB, RM', 'RW, LM', 'RM, CF, RB', 'CB, RM, RB',
       'RWB, LWB', 'CM, ST, CDM', 'LWB, LW', 'CB, RB, ST', 'LB, LWB, CDM',
       'CB, RWB, RM', 'CB, ST', 'CM, ST', 'LM, LWB, CB', 'ST, LW, LWB',
       'LM, CDM, RM', 'LWB, LB, RW', 'RB, CM, CB', 'LM, RW, ST',
       'CM, RM, LW', 'ST, RW, LM', 'RWB, CM, RM', 'CAM, RWB, CM',
       'CM, RB, LM', 'RM, RB, RW', 'LW, LM, CM', 'RM, LM, LWB',
       'ST, LM, CF', 'LW, RM, CAM', 'RB, RWB, LWB', 'LB, CM, ST',
       'ST, LWB', 'RB, ST, LM', 'CDM, CAM, LM', 'LM, ST, LWB',
       'LB, RB, RW', 'RM, CDM', 'RB, LB, LWB', 'RW, CAM, LM',
       'LB, CDM, LM', 'RW, RB, LM', 'CB, LM', 'RW, LM, RM', 'RM, LB, CM',
       'LW, CAM, RM', 'RW, RB, LB', 'LW, LB, LM', 'CDM, RB, RWB',
       'CB, RW', 'CM, LM, LW', 'LM, RM, CB', 'LM, LWB, ST', 'ST, CB, CDM',
       'LB, CDM, CB', 'CDM, CB, RM', 'RB, RWB, CM', 'ST, RW, CF',
       'ST, CB', 'ST, LW, CM', 'LM, LB, ST', 'ST, CB, RB', 'RB, LM',
       'GK, RB', 'LM, LW, CM', 'LM, CM, LW', 'CB, CAM, CM', 'LM, RB',
       'RWB, CAM', 'RB, CAM', 'CB, CDM, RM', 'ST, RB', 'ST, RWB',
       'CAM, CDM, LM', 'CB, RWB, RB', 'LM, LWB, RM', 'LB, LM, CM',
       'CM, CF, LM', 'CM, RWB', 'CDM, LM', 'ST, CF, RM', 'CAM, LB',
       'RB, RM, ST', 'LM, CDM', 'CDM, RW, RB', 'LM, CF, CAM',
       'LWB, LM, RWB', 'CF, RM, ST', 'CAM, CF, LM', 'RB, ST, CB',
       'RW, RB, LW', 'LB, LM, CDM', 'RB, CB, ST', 'RWB, CB, RB',
       'CDM, ST', 'LW, RM, LM', 'RB, LWB', 'CDM, LB, CB', 'LM, LB, CF',
       'RB, CDM, LB', 'LB, LWB, CM', 'RM, LM, CB', 'CAM, LW, CF',
       'LB, LW, CM', 'RB, CM, CDM', 'LWB, LM, ST', 'CM, RW, RM', 'CB, RM',
       'CM, LM, CB', 'LM, LB, CB', 'ST, RW, CM', 'RM, ST, CM',
       'RWB, RM, LM', 'CM, CAM, RB', 'CM, RWB, CDM', 'LB, LWB, LW'],
      dtype=object)

In [20]:
df_musket.values[2100]

array([251712, 'J. Santigaro', 'Juan José Santigaro',
       'https://cdn.sofifa.com/players/251/712/21_60.png',
       'http://sofifa.com/player/251712/juan-jose-santigaro/210006/',
       'Ecuador', 34, 74.0, 74.0, 'No Club', 'Free', 'GK', '198cm',
       '87kg', 'Right', 74, 'GK', '1-Jan-14', nan, '€0', '€0', '€0', 77.0,
       13.0, 6.0, 27.0, '18', 13.0, 99.0, '12', 23.0, 12.0, 27.0, 25.0,
       207.0, 34.0, 26.0, 43.0, 63.0, 41.0, 238.0, 61.0, 55.0, 38.0, 71.0,
       13.0, 122.0, 40, 26.0, 16.0, 15, 25.0, 21.0, 34.0, 18.0, 7.0, 9.0,
       375.0, 71.0, 79.0, 81.0, 75.0, 69, 1152.0, 405, '3 ★', '1★',
       'Medium', 'Medium', '1 ★', 71.0, 79.0, 81.0, 69.0, 30.0, 75.0, '3',
       'juan jose santigaro', 'Free'], dtype=object)

Task 3. 
Unpack the POSITIONS column into as many columns as there are positions and assign Boolean
values in the columns for each player as appropriate. Name the columns the play position

In [21]:
df_musket.Positions

0        RW, ST, CF
1            ST, LW
2                GK
3           CAM, CM
4           LW, CAM
            ...
19016            CB
19017            CM
19018            CM
19019            RW
19020        CB, LB
Name: Positions, Length: 19021, dtype: object

In [22]:
#To get the Unique position

In [23]:
df_musket.Positions.unique()

array(['RW, ST, CF', 'ST, LW', 'GK', 'CAM, CM', 'LW, CAM', 'ST', 'RW',
       'ST, LW, RW', 'CB', 'LW', 'CDM', 'CF, ST', 'LW, RW', 'CDM, CM',
       'CDM, RB', 'CF, CAM', 'LW, ST', 'CM', 'ST, CF, LW', 'RM, LM, CAM',
       'RB', 'RW, CAM, CM', 'LB', 'LM, CF', 'CF', 'RW, LW', 'CAM, RM, RW',
       'CM, CDM', 'CAM, CF, ST', 'CM, CDM, CAM', 'CF, LW, CAM',
       'CAM, RM, CF', 'LM, ST', 'RM, LM, RW', 'LM', 'CAM, RW', 'CB, CDM',
       'RW, RM', 'LW, CF', 'CM, RM, LM', 'LB, LM', 'CAM, CM, RM',
       'CAM, CM, CF', 'CAM, CF', 'LM, RM, LW', 'LM, LB, CM', 'CM, LM, LB',
       'RM, RW', 'RM, CM', 'CAM, CM, LW', 'CB, LB', 'RM, RB', 'ST, RW',
       'LM, RW, LW', 'RB, LB', 'RB, RM', 'RM', 'LM, RM, CF', 'CAM, RM',
       'RB, RWB', 'CDM, CB, CM', 'CAM, RM, ST', 'LM, LW, RM', 'CM, CAM',
       'ST, RM, CF', 'LM, RM', 'RM, CF', 'LM, LWB', 'RW, RM, CF',
       'RB, CM', 'LW, CAM, RW', 'CAM, LW, CM', 'CM, CAM, CDM',
       'RW, LW, CAM', 'CM, CAM, LM', 'CM, RM, ST', 'CDM, CM, RB',
       'ST, CAM', 'CAM, LW, ST', 'LB, CB, LWB', 'RM, ST', 'CB, CDM, LB',
       'RWB, RM', 'CM, LM, RM', 'RB, CDM, CM', 'RW, LW, RM', 'LM, LW',
       'CM, LM', 'LM, LB', 'RM, LM, CF', 'LB, LM, RM', 'CDM, CM, CAM',
       'ST, LW, RM', 'CAM, CM, ST', 'ST, CF', 'LWB, LB', 'LW, RW, LM',
       'RM, RW, ST', 'LWB', 'CF, ST, CAM', 'LM, CAM, RM', 'RB, CB',
       'ST, LM', 'RW, CAM', 'LM, CAM', 'RWB, RB', 'ST, RW, LW', 'CAM',
       'RB, RM, RW', 'LB, LWB', 'RM, CAM', 'CAM, ST', 'CDM, CB',
       'CF, LM, LW', 'CAM, LM, LW', 'LW, RW, CAM', 'CB, RB',
       'RB, CB, RWB', 'LM, LW, ST', 'LW, ST, CM', 'RM, CAM, CM',
       'CB, RB, RWB', 'RW, ST, LW', 'LW, CAM, CM', 'CM, LM, CDM',
       'LB, LM, LWB', 'CB, LB, RB', 'CAM, LW', 'RWB, RB, RM',
       'CF, CAM, ST', 'RM, CAM, RW', 'RW, ST', 'LW, LM', 'RB, RM, CM',
       'ST, CAM, RW', 'CM, RB, LB', 'CAM, LM, RM', 'RB, RW', 'LM, CM',
       'RM, LM, CM', 'CDM, CM, CB', 'CM, CF', 'CF, LW, RW', 'ST, RM',
       'CAM, CM, CDM', 'LB, CB', 'RW, RWB', 'ST, LM, RM', 'RM, RWB, RB',
       'LM, ST, CAM', 'CAM, ST, CF', 'LW, CM', 'RB, RWB, LB', 'RM, LM',
       'CM, CAM, RM', 'ST, LW, CAM', 'RM, RW, CAM', 'CM, CDM, RM',
       'RB, RM, RWB', 'CDM, CB, LB', 'CAM, ST, LM', 'LM, CM, RM',
       'CF, RW', 'CAM, RM, LW', 'CM, RM, CDM', 'LB, LWB, LM',
       'LW, RW, CF', 'LW, LM, CAM', 'LWB, LW, LB', 'CDM, CM, LM',
       'CB, CM', 'RWB, RW, RB', 'ST, RW, RM', 'LW, RW, CM', 'LM, RM, CAM',
       'LB, RB', 'RWB, RM, RB', 'LM, RB, LB', 'LW, LM, ST', 'ST, RM, LM',
       'CAM, CM, LM', 'CF, CM', 'LW, ST, RW', 'ST, CAM, CF', 'LB, CB, LM',
       'CM, CDM, LM', 'RM, RWB', 'LB, LM, RB', 'RB, LB, CB',
       'CM, CDM, RB', 'LB, CM', 'CF, CAM, LW', 'RM, LWB', 'CF, ST, LM',
       'LB, RB, CB', 'LW, CF, ST', 'RM, ST, CAM', 'LW, RW, ST',
       'ST, LW, LM', 'CM, LW', 'CDM, CM, LB', 'CM, RM, CAM',
       'ST, CF, CAM', 'CM, LM, CAM', 'RWB', 'LM, ST, RM', 'CAM, RM, CM',
       'CAM, LM, CM', 'RW, LW, ST', 'CAM, RM, LM', 'CF, ST, LW',
       'LWB, LB, LM', 'RM, CM, CAM', 'LB, LM, CAM', 'CAM, CDM',
       'RW, RB, RM', 'RM, ST, RW', 'CM, CAM, LW', 'CF, ST, RW',
       'LM, RM, RB', 'LM, RM, CM', 'CB, RB, RM', 'RB, CDM', 'RM, ST, LM',
       'LB, LWB, CB', 'CDM, LB', 'LM, RM, ST', 'RWB, RB, LWB',
       'ST, LM, CAM', 'ST, RM, CAM', 'RB, RWB, RM', 'CF, LM, CAM',
       'CAM, CF, RW', 'RB, RM, LB', 'CDM, RWB', 'CM, RW, CAM',
       'ST, CF, LM', 'RM, LM, RWB', 'RB, LB, RM', 'LM, LW, LB',
       'RM, LM, ST', 'CAM, LM', 'ST, LM, LW', 'LW, RW, RM', 'CF, LW',
       'LB, CM, RB', 'RB, CB, CDM', 'CB, RB, LB', 'CAM, RW, RM',
       'LWB, LM', 'LW, CF, LM', 'CAM, CF, CM', 'LWB, CB', 'CM, CDM, LW',
       'LM, CM, LB', 'CM, RM', 'RW, LW, CF', 'CM, CDM, CB', 'LM, RM, RW',
       'RM, RW, LM', 'RM, CAM, LM', 'LWB, RM, LB', 'RM, LB, RB',
       'CM, CF, RM', 'RM, RB, LB', 'ST, LM, RW', 'CAM, ST, LW',
       'CF, LW, ST', 'LM, LW, CAM', 'RM, RW, CF', 'LW, LM, CF',
       'CM, RW, LW', 'LM, CM, CAM', 'CAM, RW, ST', 'CM, CAM, CF',
       'RW, LWB, LW', 'CB, RB, CDM', 'RW, RM, LW', 'LW, ST, LM',
       'RWB, RW', 'ST, CAM, LM', 'CM, CB', 'RM, RW, CM', 'LWB, CM',
       'RM, LM, LB', 'RM, CAM, ST', 'CDM, RM, RB', 'LM, LB, RB',
       'LB, RB, RWB', 'RM, RWB, CAM', 'CAM, LM, CF', 'LM, CAM, CM',
       'CF, CAM, RW', 'CDM, CM, RM', 'CF, CAM, CM', 'ST, RM, LW',
       'CB, CDM, CM', 'RB, RW, LB', 'ST, RW, CAM', 'CM, LB', 'LW, RM, RW',
       'CM, RM, RW', 'RM, CF, LM', 'CF, LM, RM', 'CAM, ST, RM', 'RW, CF',
       'CM, CAM, ST', 'CAM, CDM, CM', 'RM, RW, LW', 'CAM, LM, LB',
       'CAM, RW, LW', 'CDM, CAM', 'LWB, LM, LB', 'RW, LB', 'LW, CAM, CF',
       'RB, RWB, CB', 'LM, CF, RM', 'RB, LB, RWB', 'RM, LW',
       'CAM, LM, ST', 'LW, LM, LB', 'LB, RB, RM', 'CM, LWB',
       'CDM, RB, RM', 'RM, CM, RB', 'ST, RM, RW', 'LM, RM, LWB',
       'RW, LW, LM', 'LW, CF, RW', 'CM, CDM, LB', 'ST, LM, RB', 'LB, CDM',
       'CM, CB, CDM', 'CB, LB, CDM', 'RW, ST, RM', 'RM, ST, CF',
       'CAM, LW, LM', 'LM, ST, LW', 'CAM, RM, RB', 'RB, CM, RM',
       'CM, LW, LM', 'ST, CAM, RM', 'RW, ST, CAM', 'CM, LB, LM',
       'RB, CDM, RM', 'LM, RWB, RM', 'LM, CAM, LB', 'CAM, LW, RW',
       'CM, RM, RWB', 'RW, CAM, LW', 'RB, CB, LB', 'LB, LM, LW', 'RW, RB',
       'LM, LWB, CM', 'RM, CAM, RB', 'RM, CM, ST', 'RB, RM, LM',
       'LM, LB, LW', 'LM, ST, CF', 'RW, LWB, RM', 'LM, CAM, LW',
       'CB, RWB', 'RM, LW, CAM', 'LB, LW', 'CDM, CM, ST', 'LB, CM, CDM',
       'CF, CAM, LM', 'RW, CAM, RM', 'RW, LM, LW', 'RW, CM, CAM',
       'LM, LW, RW', 'RM, LW, RW', 'LW, LWB, RWB', 'RM, LM, RB',
       'CB, CDM, RB', 'CAM, RW, CM', 'ST, CAM, CM', 'LWB, LM, CM',
       'RW, LW, RWB', 'CB, LB, LWB', 'CM, LM, ST', 'CM, LWB, LM',
       'LB, LW, LM', 'RB, CM, CAM', 'RM, CAM, CF', 'CM, RW',
       'RW, RM, CAM', 'CB, LWB', 'CAM, RB', 'LM, CM, CDM', 'RM, LB, LM',
       'CB, RB, CM', 'RB, CM, RWB', 'LB, RB, LM', 'CAM, ST, RW',
       'LB, LW, RW', 'CDM, CAM, CM', 'CAM, ST, CM', 'LM, CAM, ST',
       'LM, ST, CM', 'CAM, CF, RM', 'CF, ST, RM', 'LM, ST, LB',
       'ST, CAM, LW', 'LWB, CM, LB', 'RWB, RM, LWB', 'LWB, LM, RB',
       'CM, LW, ST', 'LB, LM, CB', 'CM, RM, RB', 'RWB, CB', 'RM, RB, RWB',
       'LB, CM, LM', 'ST, LW, CF', 'RM, RWB, ST', 'CF, ST, CM',
       'LM, LB, LWB', 'LM, RW', 'LM, LWB, LB', 'LB, LWB, RB',
       'RM, RB, LM', 'RM, CM, LM', 'LW, ST, CAM', 'RB, RM, CB',
       'LWB, RWB, LB', 'CF, RM, RW', 'RM, CF, CAM', 'LM, LW, CF',
       'RB, LM, LB', 'CAM, CM, RW', 'LB, CM, LW', 'CM, CF, CAM',
       'RW, RM, ST', 'CDM, RB, CM', 'CM, RB', 'RB, RWB, RW', 'LM, RW, RM',
       'CM, RB, CDM', 'LM, RM, LB', 'CDM, RB, CB', 'RB, CB, RM',
       'RWB, LW, LM', 'ST, CF, RW', 'RM, CM, CDM', 'LM, CF, ST',
       'LW, CAM, LM', 'CDM, LM, CM', 'ST, CM, CAM', 'LM, RM, RWB',
       'CM, CAM, RW', 'CAM, LM, RW', 'LW, LM, RM', 'CAM, RW, CF',
       'LM, ST, RW', 'CB, LWB, LB', 'RW, CF, LW', 'CB, CM, CDM',
       'CB, CAM', 'LW, LB', 'CDM, RB, LB', 'ST, CM, RB', 'RWB, LWB, RB',
       'CM, CB, RB', 'LB, LW, RB', 'CF, RM, RWB', 'LB, RM', 'RM, RW, RB',
       'LB, RM, RB', 'CDM, RM, CM', 'CDM, LB, CM', 'LM, CDM, CM',
       'RW, LM, CAM', 'LM, LB, RM', 'RM, CF, ST', 'RW, CM', 'RM, RWB, LM',
       'CF, CM, ST', 'RW, RM, LM', 'LM, CM, RW', 'RWB, CM', 'RB, RM, CDM',
       'CM, CB, CAM', 'CF, CM, LM', 'RWB, LWB, RM', 'CF, RM',
       'CM, CF, ST', 'RWB, RB, CB', 'LWB, RWB', 'RM, LM, LW',
       'LW, RM, CM', 'LW, CAM, ST', 'ST, RM, RWB', 'ST, CM',
       'CDM, CM, RWB', 'LB, CB, RB', 'CB, ST, CAM', 'CF, RM, CM',
       'CDM, CB, RB', 'CM, LM, RB', 'RB, CB, LWB', 'LM, LB, CDM',
       'LW, LWB', 'RW, CF, CAM', 'RM, RB, CAM', 'LB, RB, CM',
       'RM, CDM, LM', 'LWB, LB, CB', 'LB, RB, CDM', 'RB, CM, LB',
       'CDM, RM', 'LM, RB, CB', 'RW, RWB, RM', 'RM, LW, ST',
       'LB, RB, LWB', 'RM, LM, CDM', 'RB, RM, CAM', 'RM, ST, LW',
       'CF, LM', 'RB, LB, CDM', 'RW, LW, RB', 'RB, RWB, CDM',
       'CM, CAM, LB', 'LW, RW, LWB', 'CB, LWB, RWB', 'LB, CB, CDM',
       'ST, RB, RM', 'CM, RB, RM', 'RW, LM', 'RM, CF, RB', 'CB, RM, RB',
       'RWB, LWB', 'CM, ST, CDM', 'LWB, LW', 'CB, RB, ST', 'LB, LWB, CDM',
       'CB, RWB, RM', 'CB, ST', 'CM, ST', 'LM, LWB, CB', 'ST, LW, LWB',
       'LM, CDM, RM', 'LWB, LB, RW', 'RB, CM, CB', 'LM, RW, ST',
       'CM, RM, LW', 'ST, RW, LM', 'RWB, CM, RM', 'CAM, RWB, CM',
       'CM, RB, LM', 'RM, RB, RW', 'LW, LM, CM', 'RM, LM, LWB',
       'ST, LM, CF', 'LW, RM, CAM', 'RB, RWB, LWB', 'LB, CM, ST',
       'ST, LWB', 'RB, ST, LM', 'CDM, CAM, LM', 'LM, ST, LWB',
       'LB, RB, RW', 'RM, CDM', 'RB, LB, LWB', 'RW, CAM, LM',
       'LB, CDM, LM', 'RW, RB, LM', 'CB, LM', 'RW, LM, RM', 'RM, LB, CM',
       'LW, CAM, RM', 'RW, RB, LB', 'LW, LB, LM', 'CDM, RB, RWB',
       'CB, RW', 'CM, LM, LW', 'LM, RM, CB', 'LM, LWB, ST', 'ST, CB, CDM',
       'LB, CDM, CB', 'CDM, CB, RM', 'RB, RWB, CM', 'ST, RW, CF',
       'ST, CB', 'ST, LW, CM', 'LM, LB, ST', 'ST, CB, RB', 'RB, LM',
       'GK, RB', 'LM, LW, CM', 'LM, CM, LW', 'CB, CAM, CM', 'LM, RB',
       'RWB, CAM', 'RB, CAM', 'CB, CDM, RM', 'ST, RB', 'ST, RWB',
       'CAM, CDM, LM', 'CB, RWB, RB', 'LM, LWB, RM', 'LB, LM, CM',
       'CM, CF, LM', 'CM, RWB', 'CDM, LM', 'ST, CF, RM', 'CAM, LB',
       'RB, RM, ST', 'LM, CDM', 'CDM, RW, RB', 'LM, CF, CAM',
       'LWB, LM, RWB', 'CF, RM, ST', 'CAM, CF, LM', 'RB, ST, CB',
       'RW, RB, LW', 'LB, LM, CDM', 'RB, CB, ST', 'RWB, CB, RB',
       'CDM, ST', 'LW, RM, LM', 'RB, LWB', 'CDM, LB, CB', 'LM, LB, CF',
       'RB, CDM, LB', 'LB, LWB, CM', 'RM, LM, CB', 'CAM, LW, CF',
       'LB, LW, CM', 'RB, CM, CDM', 'LWB, LM, ST', 'CM, RW, RM', 'CB, RM',
       'CM, LM, CB', 'LM, LB, CB', 'ST, RW, CM', 'RM, ST, CM',
       'RWB, RM, LM', 'CM, CAM, RB', 'CM, RWB, CDM', 'LB, LWB, LW'],
      dtype=object)

# Extracting only one instance of each position

In [24]:
posList = []

for val in df_musket.Positions:
    if ',' in val: # if comma exists in string, it means player plays multiple positions
        pList = val.split(',')
        playPos= [x.strip() for x in pList]
        posList.extend(playPos)
    else:
        val.strip()
        posList.append(val)
posList

['RW',
 'ST',
 'CF',
 'ST',
 'LW',
 'GK',
 'CAM',
 'CM',
 'LW',
 'CAM',
 'ST',
 'RW',
 'GK',
 'ST',
 'LW',
 'RW',
 'GK',
 'CB',
 'LW',
 'CDM',
 'GK',
 'GK',
 'CF',
 'ST',
 'CB',
 'ST',
 'LW',
 'RW',
 'CDM',
 'CM',
 'CDM',
 'RB',
 'CF',
 'CAM',
 'GK',
 'ST',
 'GK',
 'CB',
 'LW',
 'ST',
 'CM',
 'ST',
 'CF',
 'LW',
 'RM',
 'LM',
 'CAM',
 'RB',
 'RW',
 'CAM',
 'CM',
 'LB',
 'CB',
 'CAM',
 'CM',
 'CDM',
 'LM',
 'CF',
 'CF',
 'GK',
 'CB',
 'CDM',
 'CM',
 'ST',
 'LW',
 'GK',
 'RW',
 'LW',
 'CM',
 'ST',
 'GK',
 'ST',
 'CAM',
 'RM',
 'RW',
 'GK',
 'RB',
 'CB',
 'CM',
 'CDM',
 'CM',
 'CDM',
 'ST',
 'CB',
 'CB',
 'GK',
 'CAM',
 'CM',
 'CAM',
 'CF',
 'ST',
 'LB',
 'CDM',
 'CM',
 'CDM',
 'CM',
 'CM',
 'CDM',
 'CAM',
 'CF',
 'LW',
 'CAM',
 'CAM',
 'RM',
 'CF',
 'CB',
 'CB',
 'LM',
 'ST',
 'GK',
 'RM',
 'LM',
 'RW',
 'LM',
 'CAM',
 'RW',
 'CB',
 'CB',
 'CDM',
 'RW',
 'RM',
 'RB',
 'ST',
 'LW',
 'CM',
 'ST',
 'CM',
 'LW',
 'CF',
 'CB',
 'CB',
 'CM',
 'RM',
 'LM',
 'GK',
 'ST',
 'LB',
 'LM',
 'CM',
 'CDM',
 'RB',
 'CAM',
 'CM',
 'RM',
 'GK',
 'CB',
 'CF',
 'ST',
 'CAM',
 'CM',
 'CF',
 'CB',
 'CM',
 'CM',
 'CAM',
 'CF',
 'CDM',
 'CM',
 'CB',
 'GK',
 'CAM',
 'CM',
 'LW',
 'RW',
 'ST',
 'ST',
 'LB',
 'LM',
 'RM',
 'LW',
 'LB',
 'CM',
 'CB',
 'LM',
 'LB',
 'CM',
 'ST',
 'CB',
 'CM',
 'CDM',
 'CM',
 'LM',
 'LB',
 'CM',
 'ST',
 'LB',
 'ST',
 'CDM',
 'CM',
 'LB',
 'GK',
 'CF',
 'ST',
 'RM',
 'RW',
 'RM',
 'CM',
 'CAM',
 'CM',
 'LW',
 'CB',
 'LB',
 'CDM',
 'CM',
 'RM',
 'RB',
 'ST',
 'RW',
 'LM',
 'RW',
 'LW',
 'CB',
 'CB',
 'CDM',
 'CDM',
 'RB',
 'LB',
 'GK',
 'GK',
 'CDM',
 'CM',
 'GK',
 'ST',
 'RB',
 'RM',
 'RM',
 'LB',
 'LW',
 'RW',
 'LM',
 'RM',
 'CF',
 'CAM',
 'RM',
 'RB',
 'RWB',
 'CDM',
 'CB',
 'CM',
 'CAM',
 'RM',
 'ST',
 'LB',
 'LM',
 'LM',
 'LW',
 'RM',
 'CB',
 'CAM',
 'CM',
 'CM',
 'CAM',
 'GK',
 'GK',
 'CB',
 'CM',
 'ST',
 'RM',
 'CF',
 'ST',
 'LM',
 'RM',
 'RM',
 'CF',
 'GK',
 'LM',
 'LWB',
 'LB',
 'CAM',
 'CM',
 'RB',
 'CB',
 'LB',
 'LM',
 'RM',
 'CB',
 'CM',
 'CDM',
 'RW',
 'RM',
 'CF',
 'CM',
 'CAM',
 'ST',
 'CM',
 'CDM',
 'RB',
 'CDM',
 'CM',
 'CF',
 'LW',
 'CAM',
 'CDM',
 'CM',
 'RB',
 'RB',
 'CM',
 'GK',
 'CDM',
 'CM',
 'CB',
 'GK',
 'ST',
 'LM',
 'CF',
 'CB',
 'GK',
 'LW',
 'CAM',
 'RW',
 'CAM',
 'LW',
 'CM',
 'CAM',
 'CM',
 'LW',
 'GK',
 'CB',
 'CM',
 'CDM',
 'GK',
 'CM',
 'CAM',
 'CDM',
 'LB',
 'CM',
 'CDM',
 'CM',
 'CDM',
 'CAM',
 'ST',
 'CAM',
 'CM',
 'CF',
 'LB',
 'RW',
 'CM',
 'CDM',
 'CB',
 'LB',
 'GK',
 'ST',
 'RW',
 'LW',
 'CAM',
 'CM',
 'ST',
 'CM',
 'CAM',
 'LM',
 'CB',
 'LB',
 'CB',
 'RW',
 'RM',
 'GK',
 'CB',
 'CM',
 'CAM',
 'CM',
 'RM',
 'ST',
 'RM',
 'RW',
 'CDM',
 'CM',
 'RB',
 'CM',
 'GK',
 'LM',
 'LW',
 'RW',
 'LM',
 'LB',
 'LM',
 'ST',
 'CAM',
 'CAM',
 'LW',
 'ST',
 'GK',
 'RW',
 'LW',
 'GK',
 'CM',
 'CDM',
 'CB',
 'GK',
 'LB',
 'CB',
 'LWB',
 'CAM',
 'RW',
 'RM',
 'ST',
 'GK',
 'CM',
 'GK',
 'GK',
 'CB',
 'CB',
 'CDM',
 'LB',
 'GK',
 'ST',
 'CAM',
 'GK',
 'RWB',
 'RM',
 'GK',
 'GK',
 'GK',
 'CAM',
 'RW',
 'CDM',
 'CM',
 'ST',
 'CB',
 'CM',
 'LM',
 'RM',
 'RM',
 'RW',
 'GK',
 'GK',
 'RB',
 'CDM',
 'CM',
 'GK',
 'CM',
 'CAM',
 'CB',
 'CAM',
 'RW',
 'LW',
 'CAM',
 'CM',
 'RW',
 'LW',
 'RM',
 'ST',
 'GK',
 'LB',
 'CB',
 'LM',
 'LW',
 'CM',
 'LM',
 'RM',
 'LM',
 'LB',
 'CB',
 'LM',
 'LW',
 'RM',
 'LM',
 'CF',
 'CF',
 'ST',
 'LB',
 'RM',
 'RW',
 'ST',
 'LB',
 'LM',
 'RM',
 'CDM',
 'CM',
 'CAM',
 'ST',
 'LW',
 'RM',
 'ST',
 'CAM',
 'CM',
 'ST',
 'LB',
 'LM',
 'ST',
 'CF',
 'LWB',
 'LB',
 'CB',
 'CDM',
 'LB',
 'LW',
 'RW',
 'LM',
 'CDM',
 'CM',
 'GK',
 'ST',
 'CB',
 'RB',
 'LB',
 'CM',
 'RM',
 'RW',
 'ST',
 'CAM',
 'CM',
 'LW',
 'CM',
 'LM',
 'CDM',
 'CM',
 'ST',
 'RW',
 'CB',
 'LWB',
 'CM',
 'CAM',
 'CF',
 'ST',
 'CAM',
 'GK',
 'LM',
 'CAM',
 'RM',
 'GK',
 'ST',
 'CM',
 'CDM',
 'CDM',
 'CM',
 'LM',
 'ST',
 'CDM',
 'CM',
 'RB',
 'CB',
 'CDM',
 'CM',
 'GK',
 'RM',
 'CB',
 'CM',
 'CDM',
 'CAM',
 'GK',
 'CB',
 'ST',
 'GK',
 'CB',
 'ST',
 'LM',
 'RB',
 'RB',
 'RW',
 'CAM',
 'LB',
 'LM',
 'CAM',
 'RWB',
 'RB',
 'ST',
 'RW',
 'LW',
 'ST',
 'RW',
 'GK',
 'RW',
 'CAM',
 'RB',
 'RM',
 'ST',
 'GK',
 'LB',
 'CAM',
 'CB',
 'CDM',
 'RB',
 'RM',
 'RW',
 'CM',
 'CAM',
 'LB',
 'LWB',
 'CAM',
 'CM',
 'RM',
 'RW',
 'RM',
 'CAM',
 'CAM',
 'ST',
 'CM',
 'CDM',
 'CDM',
 'CB',
 'LM',
 'CAM',
 'CB',
 'CM',
 'CDM',
 'CAM',
 'GK',
 'GK',
 'GK',
 'CF',
 'LM',
 'LW',
 'CM',
 'CB',
 'GK',
 'ST',
 'CF',
 'CB',
 'CDM',
 'LW',
 'ST',
 'GK',
 'RM',
 'GK',
 'LB',
 'LM',
 'CDM',
 'CM',
 'CAM',
 'LM',
 'LW',
 'ST',
 'CF',
 'CB',
 'CAM',
 'RM',
 'CM',
 'CDM',
 'LB',
 'LWB',
 'LW',
 'RW',
 'CAM',
 'CAM',
 'ST',
 'GK',
 'CB',
 'CB',
 'RB',
 'GK',
 'CAM',
 'CM',
 'LW',
 'CDM',
 'CM',
 'LB',
 'ST',
 'CB',
 'LW',
 'ST',
 'LB',
 'CAM',
 'LM',
 'LW',
 'ST',
 'RB',
 'RM',
 'LM',
 'RM',
 'CB',
 'CB',
 'RB',
 'CB',
 'RWB',
 'GK',
 'RB',
 'CM',
 'CAM',
 'CM',
 'LM',
 'LW',
 'ST',
 'GK',
 'LW',
 'ST',
 'CM',
 'CM',
 'CAM',
 'CM',
 'CDM',
 'RM',
 'CAM',
 'CM',
 'CB',
 'RB',
 'RWB',
 'RW',
 'ST',
 'LW',
 'CB',
 'LB',
 'CDM',
 'CM',
 'CDM',
 'GK',
 'CM',
 'LM',
 'CDM',
 'ST',
 'LW',
 'RM',
 'RW',
 'LW',
 'CAM',
 'CM',
 'CDM',
 'CM',
 'RW',
 'RM',
 'ST',
 'GK',
 'RW',
 'RM',
 'RW',
 'RB',
 'LB',
 'CB',
 'CM',
 'CAM',
 'RM',
 'CM',
 'CAM',
 'LM',
 'CB',
 'CAM',
 'RB',
 'CAM',
 'CM',
 'LW',
 'CDM',
 'CM',
 'CM',
 'LM',
 'CDM',
 'LB',
 'LM',
 'LWB',
 'CB',
 'LB',
 'RB',
 'GK',
 'CB',
 'LM',
 'CF',
 'CAM',
 'LW',
 'LB',
 'LM',
 'CB',
 'CB',
 'RWB',
 'RB',
 'RM',
 'RB',
 'RWB',
 'RB',
 'CB',
 'ST',
 'CDM',
 'CM',
 'GK',
 'CDM',
 'CM',
 'CF',
 'CAM',
 'ST',
 'RB',
 'RM',
 'CAM',
 'RW',
 'LB',
 'LM',
 'ST',
 'ST',
 'CB',
 'CDM',
 'CDM',
 'CM',
 'CDM',
 'CM',
 'RB',
 'RB',
 'RWB',
 'RW',
 'ST',
 'ST',
 'CDM',
 'CM',
 'CB',
 'CAM',
 'CF',
 'LB',
 'GK',
 'CB',
 'RB',
 'CB',
 'ST',
 'CB',
 'CAM',
 'GK',
 'CDM',
 'CB',
 'CAM',
 'ST',
 'CB',
 'CM',
 'GK',
 'CM',
 'CDM',
 'CB',
 'RB',
 'LW',
 'LM',
 'CB',
 'ST',
 'RB',
 'RM',
 'CM',
 'RM',
 'CAM',
 'ST',
 'CAM',
 'RW',
 'RM',
 'CAM',
 'ST',
 'CM',
 'CAM',
 'CDM',
 'CB',
 'RW',
 'LW',
 'GK',
 'LW',
 'RW',
 'CM',
 'RB',
 'LB',
 'LM',
 'RM',
 'ST',
 'GK',
 'ST',
 'CDM',
 'CM',
 'CAM',
 'RB',
 'RM',
 'LB',
 'LM',
 'CM',
 'CAM',
 'ST',
 'CAM',
 'LM',
 'RM',
 'RW',
 'LW',
 'CB',
 'GK',
 'CB',
 'LB',
 'LM',
 'RB',
 'RW',
 'CDM',
 'CM',
 'LB',
 'LWB',
 'CAM',
 'CM',
 'LM',
 'CM',
 'CDM',
 'CM',
 'CDM',
 'CM',
 'CM',
 'RB',
 'LW',
 'CAM',
 'RM',
 'CAM',
 'CDM',
 'CB',
 'CDM',
 'CM',
 'RM',
 'LM',
 'CM',
 'RB',
 'CDM',
 'CM',
 'CB',
 'ST',
 'ST',
 'CM',
 'CF',
 'ST',
 'GK',
 'CDM',
 'CDM',
 'CM',
 'RB',
 'LB',
 'LM',
 'CB',
 'CF',
 'LW',
 'RW',
 'ST',
 'ST',
 'ST',
 'RM',
 'CAM',
 'CM',
 'CDM',
 'ST',
 'ST',
 'RM',
 'RB',
 'LM',
 'CAM',
 'RM',
 'CM',
 'CAM',
 'RB',
 'RWB',
 'CB',
 'CB',
 'CM',
 'CDM',
 'CAM',
 'LW',
 'RW',
 'LM',
 'ST',
 'CDM',
 'CM',
 'LB',
 'CB',
 'CDM',
 'CM',
 'ST',
 'ST',
 'RW',
 'LW',
 'CB',
 'RB',
 'ST',
 'CAM',
 'CDM',
 'CM',
 'CB',
 'CDM',
 'CM',
 'LB',
 'CDM',
 'CM',
 'RW',
 'RWB',
 'ST',
 'ST',
 'LM',
 'RM',
 'CM',
 'CDM',
 'CB',
 'RW',
 'RM',
 'LB',
 'LWB',
 'ST',
 'CDM',
 'CM',
 'CAM',
 'ST',
 'LB',
 'ST',
 'CB',
 'LW',
 'RW',
 'CB',
 'GK',
 'LB',
 'LM',
 'CM',
 'CDM',
 'GK',
 'RM',
 'RWB',
 'RB',
 'CM',
 'LM',
 'ST',
 'CAM',
 'GK',
 'ST',
 'CAM',
 'ST',
 ...]

In [25]:
pos=list(set(posList)) #converting to list in set format
pos

['RW',
 'CF',
 'CM',
 'CDM',
 'LWB',
 'GK',
 'RM',
 'RB',
 'CB',
 'CAM',
 'ST',
 'LW',
 'LM',
 'LB',
 'RWB']

In [26]:
playerPos = []
for positions in df_musket.Positions.values:
    posTable = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    for p in pos:
        if p in positions:
            Pidx = pos.index(p)
            posTable[Pidx]=1
    playerPos.append(posTable)
playerPos

[[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],

In [27]:
dfPos = pd.DataFrame(playerPos, columns = pos) #converting to a dataFrame
dfPos

       RW  CF  CM  CDM  LWB  GK  RM  RB  CB  CAM  ST  LW  LM  LB  RWB
0       1   1   0    0    0   0   0   0   0    0   1   0   0   0    0
1       0   0   0    0    0   0   0   0   0    0   1   1   0   0    0
2       0   0   0    0    0   1   0   0   0    0   0   0   0   0    0
3       0   0   1    0    0   0   0   0   0    1   0   0   0   0    0
4       0   0   0    0    0   0   0   0   0    1   0   1   0   0    0
...    ..  ..  ..  ...  ...  ..  ..  ..  ..  ...  ..  ..  ..  ..  ...
19016   0   0   0    0    0   0   0   0   1    0   0   0   0   0    0
19017   0   0   1    0    0   0   0   0   0    0   0   0   0   0    0
19018   0   0   1    0    0   0   0   0   0    0   0   0   0   0    0
19019   1   0   0    0    0   0   0   0   0    0   0   0   0   0    0
19020   0   0   0    0    0   0   0   0   1    0   0   0   0   1    0

[19021 rows x 15 columns]

In [28]:
# confirming the results
df_musket.Positions.values[19016:19021]

array(['CB', 'CM', 'CM', 'RW', 'CB, LB'], dtype=object)

In [29]:
#Merging the play position with the original table
dfNew =df_musket.join(dfPos)
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,GK,RM,RB,CB,CAM,ST,LW,LM,LB,RWB
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,0,0,0,0,0,1,0,0,0,0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,0,0,0,0,0,1,1,0,0,0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,1,0,0,0,0,0,0,0,0,0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,0,0,0,0,1,0,0,0,0,0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,0,0,0,1,0,0,0,0,0,0
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,0,0,0,0,0,0,0,0,0,0
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,0,0,0,0,0,0,0,0,0,0
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,0,0,0,0,0,0,0
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,1,0,0,0,0,1,0

In [30]:
dfNew.values[19020] #checking that it is done

array([252520, 'Zhou Xiao', 'Xiao Zhou',
       'https://cdn.sofifa.com/players/252/520/21_60.png',
       'http://sofifa.com/player/252520/xiao-zhou/210006/', 'China PR',
       21, 47.0, 57.0, '\n\n\n\nDalian YiFang FC', '2019 ~ 2023',
       'CB, LB', '188cm', '75kg', 'Left', 50, 'LB', '29-Jul-19', nan,
       '€100K', '€1K', '€79K', 163.0, 40.0, 18.0, 40.0, 45.0, 20.0, 171.0,
       40, 33.0, 20.0, 40.0, 38.0, 279.0, 60.0, 63.0, 57.0, 47.0, 52.0,
       231.0, 37.0, 66.0, 60.0, 55.0, 13.0, 185.0, 45, 47.0, 33.0, 33,
       27.0, 33.0, 136.0, 45.0, 46.0, 45.0, 50.0, 10.0, 11.0, 7.0, 10.0,
       12, 1215.0, 265, '3 ★', '2★', 'Medium', 'Medium', '1 ★', 62.0,
       22.0, 39.0, 42.0, 45.0, 55.0, nan, 'xiao zhou', 'Active', 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0], dtype=object)

Task 4
Weight and Height, W/F, SM and IR Columns: convert to integers

In [31]:
df_musket['W/F']

0        4 ★
1        4 ★
2        3 ★
3        5 ★
4        5 ★
        ...
19016    2 ★
19017    2 ★
19018    2 ★
19019    3 ★
19020    3 ★
Name: W/F, Length: 19021, dtype: object

In [32]:
stList=[]
for y1, y2, y3 in zip(df_musket['W/F'].values, df_musket['SM'].values,df_musket['IR'].values,):
    stList.append([int(y1[0]),int(y2[0]),int(y3[0])])
pd.DataFrame(stList, columns=['W/F', 'SM','IR'])

       W/F  SM  IR
0        4   4   5
1        4   5   5
2        3   1   3
3        5   4   4
4        5   5   5
...    ...  ..  ..
19016    2   2   1
19017    2   2   1
19018    2   2   1
19019    3   2   1
19020    3   2   1

[19021 rows x 3 columns]

In [33]:
#Merging them with the original table
stDF = pd.DataFrame(stList, columns=['W/F1', 'SM1','IR1'])
dfNew =dfNew.join(stDF)
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,CB,CAM,ST,LW,LM,LB,RWB,W/F1,SM1,IR1
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,0,0,1,0,0,0,0,4,4,5
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,0,0,1,1,0,0,0,4,5,5
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,0,0,0,0,0,0,0,3,1,3
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,0,1,0,0,0,0,0,5,4,4
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,0,1,0,1,0,0,0,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,1,0,0,0,0,0,0,2,2,1
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,0,0,0,0,0,0,0,2,2,1
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,0,0,0,0,0,0,0,2,2,1
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,0,0,0,0,3,2,1
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,1,0,0,0,0,1,0,3,2,1

In [34]:
# Weight and Height

In [35]:
df_musket.Weight.unique() #for Weight

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       nan, '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs',
       '185lbs', '170lbs', '203lbs', '168lbs', '161lbs', '146lbs',
       '130lbs', '190lbs', '174lbs', '148lbs', '165lbs', '159lbs',
       '192lbs', '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg',
       '103kg', '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg',
       '107kg', '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [36]:
wList = [] #Keeping kg as Unit
for val in df_musket.Weight.values:
    val =str(val)
    if 'kg' in val:
        wList.append(float(val[:-2]))
    elif 'lbs'in val:
        wList.append(float(val[:-3])*0.453592) # converting lbs to kg
    else:
          wList.append(float(val))
wList

[72.0,
 83.0,
 87.0,
 70.0,
 68.0,
 80.0,
 71.0,
 91.0,
 73.0,
 85.0,
 92.0,
 69.0,
 84.0,
 96.0,
 92.0,
 81.0,
 82.0,
 70.0,
 69.0,
 70.0,
 73.0,
 75.0,
 86.0,
 89.0,
 92.0,
 89.0,
 74.0,
 76.0,
 73.0,
 76.0,
 69.0,
 64.0,
 64.0,
 85.0,
 69.0,
 78.0,
 78.0,
 76.0,
 80.0,
 85.0,
 76.0,
 80.0,
 90.0,
 69.0,
 66.0,
 83.0,
 82.0,
 85.0,
 75.0,
 82.0,
 73.0,
 81.0,
 60.0,
 84.0,
 74.0,
 85.0,
 94.0,
 79.0,
 67.0,
 68.0,
 68.0,
 80.0,
 82.0,
 76.0,
 78.0,
 83.0,
 89.0,
 80.0,
 70.0,
 90.0,
 75.0,
 75.0,
 65.0,
 81.0,
 75.0,
 67.0,
 70.0,
 76.0,
 74.0,
 75.0,
 74.0,
 59.0,
 81.0,
 79.0,
 75.0,
 82.0,
 94.0,
 80.0,
 70.0,
 70.0,
 76.0,
 86.0,
 85.0,
 61.0,
 74.0,
 78.0,
 69.0,
 72.0,
 71.0,
 74.0,
 79.0,
 93.0,
 83.0,
 79.0,
 81.0,
 88.0,
 71.0,
 75.0,
 69.0,
 73.0,
 97.0,
 71.0,
 76.0,
 84.0,
 76.0,
 75.0,
 77.0,
 68.0,
 65.0,
 81.0,
 68.0,
 74.0,
 85.0,
 79.0,
 73.0,
 72.0,
 79.0,
 78.0,
 66.0,
 62.0,
 67.0,
 70.0,
 78.0,
 67.0,
 78.0,
 77.0,
 80.0,
 89.0,
 81.0,
 84.0,
 77.0,
 60.0,
 73.0,
 73.0,
 67.0,
 71.0,
 75.0,
 72.0,
 80.0,
 75.0,
 69.0,
 78.0,
 77.0,
 68.0,
 74.0,
 77.0,
 80.0,
 86.0,
 78.0,
 77.0,
 73.0,
 66.0,
 70.0,
 78.0,
 82.0,
 66.0,
 80.0,
 74.0,
 78.0,
 67.0,
 63.0,
 75.0,
 68.0,
 66.0,
 76.0,
 88.0,
 80.0,
 69.0,
 76.0,
 76.0,
 75.0,
 69.0,
 68.0,
 81.0,
 70.0,
 90.0,
 78.0,
 77.0,
 66.0,
 83.0,
 82.0,
 66.0,
 68.0,
 66.0,
 86.0,
 88.0,
 80.0,
 88.0,
 80.0,
 80.0,
 74.0,
 75.0,
 80.0,
 65.0,
 75.0,
 82.0,
 71.0,
 86.0,
 82.0,
 95.0,
 77.0,
 61.0,
 89.0,
 86.0,
 76.0,
 72.0,
 70.0,
 81.0,
 80.0,
 68.0,
 74.0,
 73.0,
 72.0,
 80.0,
 85.0,
 76.0,
 76.0,
 73.0,
 68.0,
 73.0,
 72.0,
 91.0,
 84.0,
 88.0,
 86.0,
 86.0,
 81.0,
 87.0,
 80.0,
 70.0,
 84.0,
 70.0,
 85.0,
 85.0,
 100.0,
 72.0,
 76.0,
 77.0,
 94.0,
 80.0,
 84.0,
 77.0,
 85.0,
 75.0,
 83.0,
 84.0,
 72.0,
 65.0,
 81.0,
 82.0,
 87.0,
 78.0,
 92.0,
 76.0,
 74.0,
 71.0,
 77.0,
 78.0,
 77.0,
 83.0,
 74.0,
 nan,
 90.0,
 80.0,
 70.0,
 67.0,
 66.0,
 82.0,
 67.0,
 77.0,
 70.0,
 70.0,
 68.0,
 69.0,
 72.0,
 70.0,
 71.0,
 79.0,
 75.0,
 69.0,
 83.0,
 68.0,
 82.0,
 77.0,
 69.0,
 86.0,
 94.0,
 84.0,
 80.0,
 75.0,
 75.0,
 72.0,
 67.0,
 73.0,
 64.0,
 72.0,
 60.0,
 79.0,
 79.0,
 70.0,
 70.0,
 77.0,
 93.0,
 66.0,
 77.0,
 74.0,
 80.0,
 62.0,
 68.0,
 76.0,
 76.0,
 79.0,
 68.0,
 72.0,
 92.0,
 66.0,
 78.0,
 85.0,
 78.0,
 77.0,
 80.0,
 71.0,
 72.0,
 67.0,
 70.0,
 85.0,
 70.0,
 87.0,
 85.0,
 72.0,
 75.0,
 83.0,
 70.0,
 82.0,
 82.0,
 87.0,
 86.0,
 67.0,
 81.0,
 72.0,
 68.0,
 85.0,
 75.0,
 68.0,
 76.0,
 76.0,
 90.0,
 86.0,
 75.0,
 77.0,
 73.0,
 93.0,
 83.0,
 82.0,
 72.0,
 78.0,
 81.0,
 83.0,
 89.0,
 82.0,
 73.0,
 84.0,
 79.0,
 71.0,
 85.0,
 69.0,
 75.0,
 63.0,
 83.0,
 80.0,
 75.0,
 76.0,
 76.0,
 66.0,
 72.0,
 85.0,
 82.0,
 78.0,
 89.0,
 70.0,
 74.0,
 82.0,
 85.0,
 80.0,
 87.0,
 64.0,
 63.0,
 84.0,
 75.0,
 79.0,
 76.0,
 78.0,
 84.0,
 83.0,
 70.0,
 68.0,
 83.0,
 67.0,
 74.0,
 73.0,
 68.0,
 70.0,
 71.0,
 88.0,
 70.0,
 80.0,
 69.0,
 81.0,
 81.0,
 93.0,
 75.0,
 84.0,
 79.0,
 74.0,
 68.0,
 79.0,
 76.0,
 72.0,
 88.0,
 70.0,
 72.0,
 65.0,
 84.0,
 74.0,
 77.0,
 73.0,
 77.0,
 79.0,
 76.0,
 77.0,
 80.0,
 70.0,
 83.0,
 76.0,
 78.0,
 82.0,
 73.0,
 74.0,
 80.0,
 97.0,
 70.0,
 81.0,
 74.0,
 68.0,
 81.0,
 74.0,
 74.0,
 82.0,
 74.0,
 80.0,
 74.0,
 75.0,
 72.0,
 91.0,
 73.0,
 73.0,
 77.0,
 84.0,
 80.0,
 74.0,
 85.0,
 86.0,
 83.0,
 80.0,
 61.0,
 77.0,
 86.0,
 91.0,
 82.0,
 84.0,
 86.0,
 68.0,
 86.0,
 78.0,
 80.0,
 77.0,
 75.0,
 80.0,
 74.0,
 79.0,
 62.0,
 95.0,
 77.0,
 74.0,
 80.0,
 83.0,
 80.0,
 72.0,
 85.0,
 77.0,
 67.0,
 78.0,
 70.0,
 70.0,
 75.0,
 79.0,
 80.0,
 74.0,
 70.0,
 75.0,
 65.0,
 73.0,
 83.0,
 72.0,
 64.0,
 90.0,
 85.0,
 75.0,
 78.0,
 66.0,
 78.0,
 73.0,
 69.0,
 64.0,
 96.0,
 88.0,
 74.0,
 80.0,
 66.0,
 73.0,
 68.0,
 80.0,
 76.0,
 66.0,
 73.0,
 77.0,
 78.0,
 79.0,
 73.0,
 80.0,
 88.0,
 75.0,
 70.0,
 65.0,
 90.0,
 73.0,
 78.0,
 84.0,
 81.0,
 77.0,
 79.0,
 83.0,
 73.0,
 67.0,
 69.0,
 71.0,
 77.0,
 89.0,
 74.0,
 78.0,
 86.0,
 78.0,
 82.0,
 85.0,
 71.0,
 69.0,
 80.0,
 69.0,
 78.0,
 72.0,
 73.0,
 79.0,
 74.0,
 72.0,
 82.0,
 70.0,
 80.0,
 78.0,
 72.0,
 69.0,
 80.0,
 74.0,
 74.0,
 86.0,
 81.0,
 82.0,
 63.0,
 97.0,
 85.0,
 77.0,
 84.0,
 94.0,
 76.0,
 78.0,
 71.0,
 86.0,
 79.0,
 73.0,
 66.0,
 81.0,
 91.0,
 75.0,
 76.0,
 76.0,
 76.0,
 76.0,
 84.0,
 70.0,
 75.0,
 74.0,
 80.0,
 80.0,
 66.0,
 87.0,
 67.0,
 78.0,
 75.0,
 75.0,
 84.0,
 82.0,
 73.0,
 77.0,
 67.0,
 72.0,
 80.0,
 71.0,
 67.0,
 78.0,
 85.0,
 79.0,
 88.0,
 69.0,
 73.0,
 78.0,
 73.0,
 80.0,
 70.0,
 83.0,
 73.0,
 62.0,
 80.0,
 64.0,
 85.0,
 71.0,
 73.0,
 77.0,
 81.0,
 82.0,
 80.0,
 74.0,
 72.0,
 89.0,
 91.0,
 87.0,
 76.0,
 75.0,
 77.0,
 70.0,
 75.0,
 91.0,
 85.0,
 80.0,
 70.0,
 84.0,
 77.0,
 80.0,
 91.0,
 76.0,
 68.0,
 63.0,
 58.0,
 68.0,
 94.0,
 70.0,
 83.0,
 84.0,
 73.0,
 80.0,
 75.0,
 90.0,
 88.0,
 73.0,
 78.0,
 92.0,
 67.0,
 67.0,
 72.0,
 63.0,
 73.0,
 76.0,
 77.0,
 79.0,
 78.0,
 75.0,
 79.0,
 78.0,
 82.0,
 81.0,
 70.0,
 70.0,
 82.0,
 80.0,
 80.0,
 73.0,
 81.0,
 77.0,
 76.0,
 63.0,
 95.0,
 78.0,
 62.0,
 68.0,
 82.0,
 70.0,
 85.0,
 66.0,
 78.0,
 73.0,
 87.0,
 78.0,
 87.0,
 70.0,
 63.0,
 70.0,
 70.0,
 84.0,
 76.0,
 87.0,
 60.0,
 72.0,
 72.0,
 75.0,
 88.0,
 79.0,
 66.0,
 73.0,
 68.0,
 70.0,
 86.0,
 82.0,
 70.0,
 77.0,
 58.0,
 76.0,
 78.0,
 79.0,
 83.0,
 70.0,
 78.0,
 79.0,
 71.0,
 77.0,
 78.0,
 73.0,
 72.0,
 71.0,
 88.0,
 70.0,
 78.0,
 66.0,
 71.0,
 94.0,
 80.0,
 71.0,
 62.0,
 68.0,
 83.0,
 79.0,
 64.0,
 68.0,
 70.0,
 79.0,
 83.0,
 88.0,
 68.0,
 71.0,
 88.0,
 78.0,
 88.0,
 85.0,
 68.0,
 67.0,
 77.0,
 77.0,
 86.0,
 70.0,
 65.0,
 74.0,
 72.0,
 85.0,
 91.0,
 78.0,
 75.0,
 83.007336,
 86.0,
 76.0,
 77.0,
 70.0,
 84.0,
 80.0,
 76.0,
 84.0,
 82.0,
 86.0,
 65.0,
 67.0,
 75.0,
 78.0,
 71.0,
 84.0,
 69.0,
 60.0,
 78.0,
 69.0,
 69.0,
 75.0,
 91.0,
 75.0,
 87.0,
 90.0,
 75.0,
 84.0,
 67.0,
 71.0,
 80.0,
 65.0,
 85.0,
 89.0,
 90.0,
 89.0,
 90.0,
 80.0,
 71.0,
 89.0,
 88.0,
 70.0,
 76.0,
 87.0,
 77.0,
 69.0,
 70.0,
 69.0,
 92.0,
 80.0,
 75.0,
 83.0,
 70.0,
 81.192968,
 83.007336,
 87.0,
 85.0,
 95.0,
 65.0,
 73.0,
 74.0,
 79.0,
 76.0,
 76.0,
 78.0,
 82.0,
 78.017824,
 88.904032,
 79.83219199999999,
 83.91452,
 81.192968,
 77.11064,
 88.904032,
 78.017824,
 92.079176,
 83.007336,
 83.0,
 76.203456,
 73.028312,
 66.224432,
 58.96696,
 86.18248,
 78.017824,
 78.925008,
 67.131616,
 74.84268,
 78.017824,
 73.028312,
 77.0,
 72.121128,
 77.11064,
 87.089664,
 82.100152,
 63.049288,
 69.853168,
 76.203456,
 77.11064,
 74.84268,
 71.213944,
 72.121128,
 82.100152,
 81.192968,
 67.131616,
 77.11064,
 73.935496,
 78.0,
 77.0,
 80.0,
 77.0,
 74.0,
 79.0,
 70.0,
 65.0,
 82.0,
 75.0,
 82.0,
 76.0,
 75.0,
 67.0,
 83.0,
 73.0,
 62.0,
 83.0,
 77.0,
 82.0,
 75.0,
 67.0,
 71.0,
 68.0,
 85.0,
 88.0,
 75.0,
 85.0,
 81.0,
 85.0,
 85.0,
 69.0,
 77.0,
 76.0,
 72.0,
 70.0,
 75.0,
 77.0,
 85.0,
 65.0,
 78.0,
 67.0,
 74.0,
 70.0,
 75.0,
 98.0,
 69.0,
 77.0,
 80.0,
 65.0,
 81.0,
 80.0,
 70.0,
 83.0,
 79.0,
 86.0,
 67.0,
 79.0,
 82.0,
 80.0,
 84.0,
 65.0,
 82.0,
 71.0,
 75.0,
 86.0,
 80.0,
 76.0,
 90.0,
 80.0,
 88.0,
 67.0,
 82.0,
 62.0,
 75.0,
 62.0,
 83.0,
 85.0,
 77.0,
 79.0,
 63.0,
 72.0,
 76.0,
 73.0,
 73.0,
 82.0,
 62.0,
 82.0,
 78.0,
 82.0,
 76.0,
 73.0,
 72.0,
 68.0,
 73.0,
 83.0,
 75.0,
 83.0,
 77.0,
 73.0,
 77.0,
 ...]

In [37]:
dfNew['wt(kg)']=wList
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,CAM,ST,LW,LM,LB,RWB,W/F1,SM1,IR1,wt(kg)
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,0,1,0,0,0,0,4,4,5,72.0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,0,1,1,0,0,0,4,5,5,83.0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,0,0,0,0,0,0,3,1,3,87.0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,1,0,0,0,0,0,5,4,4,70.0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,1,0,1,0,0,0,5,5,5,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,0,0,0,0,0,0,2,2,1,66.0
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,0,0,0,0,0,0,2,2,1,65.0
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,0,0,0,0,0,0,2,2,1,74.0
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,0,0,0,3,2,1,69.0
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,0,1,0,3,2,1,75.0

In [38]:
df_musket.Height.unique() #for Height

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [39]:
hList = [] #Keeping metre (m) as Unit
for val in df_musket.Height.values:
    val =str(val)
    if 'cm' in val:
        hList.append(float(val[:-2])/100)# converting cm to m 
    elif '\'' in val:
        vals=val.split('\'')
        # ft = vals[0]; and inch = vals[1][:-1]
        hList.append(float(vals[0])*0.3048 + float(vals[1][:-1])*0.0254 ) # converting ft and inches to m
    else:
        hList.append(float(val))
hList

[1.7,
 1.87,
 1.88,
 1.81,
 1.75,
 1.84,
 1.75,
 1.91,
 1.78,
 1.87,
 1.93,
 1.75,
 1.85,
 1.99,
 1.93,
 1.85,
 1.84,
 1.73,
 1.7,
 1.68,
 1.76,
 1.77,
 1.88,
 1.88,
 1.93,
 1.87,
 1.75,
 1.83,
 1.76,
 1.8,
 1.8,
 1.73,
 1.78,
 1.89,
 1.79,
 1.88,
 1.83,
 1.81,
 1.85,
 1.87,
 1.89,
 1.87,
 1.95,
 1.8,
 1.72,
 1.82,
 1.88,
 1.85,
 1.86,
 1.92,
 1.73,
 1.91,
 1.65,
 1.91,
 1.79,
 1.94,
 1.91,
 1.83,
 1.73,
 1.67,
 1.7,
 1.82,
 1.91,
 1.91,
 1.76,
 1.88,
 1.89,
 1.88,
 1.86,
 1.96,
 1.75,
 1.84,
 1.81,
 1.86,
 1.83,
 1.79,
 1.75,
 1.8,
 1.82,
 1.81,
 1.8,
 1.63,
 1.86,
 1.83,
 1.76,
 1.9,
 1.91,
 1.8,
 1.74,
 1.83,
 1.81,
 1.91,
 1.9,
 1.69,
 1.83,
 1.87,
 1.75,
 1.78,
 1.8,
 1.83,
 1.85,
 1.9,
 1.85,
 1.81,
 1.74,
 1.94,
 1.81,
 1.79,
 1.71,
 1.71,
 1.95,
 1.7,
 1.84,
 1.9,
 1.89,
 1.84,
 1.85,
 1.7,
 1.72,
 1.88,
 1.81,
 1.78,
 1.87,
 1.9,
 1.78,
 1.77,
 1.76,
 1.8,
 1.74,
 1.73,
 1.76,
 1.72,
 1.89,
 1.79,
 1.79,
 1.78,
 1.92,
 1.89,
 1.86,
 1.9,
 1.85,
 1.72,
 1.81,
 1.8,
 1.78,
 1.75,
 1.77,
 1.83,
 1.9,
 1.73,
 1.72,
 1.78,
 1.88,
 1.78,
 1.84,
 1.89,
 1.9,
 1.85,
 1.82,
 1.8,
 1.75,
 1.72,
 1.74,
 1.93,
 1.84,
 1.72,
 1.88,
 1.82,
 1.88,
 1.7,
 1.72,
 1.82,
 1.8,
 1.67,
 1.78,
 1.89,
 1.76,
 1.77,
 1.83,
 1.81,
 1.8,
 1.73,
 1.78,
 1.84,
 1.71,
 1.94,
 1.82,
 1.76,
 1.8,
 1.89,
 1.92,
 1.7,
 1.72,
 1.79,
 1.97,
 1.92,
 1.8,
 1.89,
 1.83,
 1.81,
 1.75,
 1.8,
 1.93,
 1.76,
 1.74,
 1.85,
 1.74,
 1.89,
 1.85,
 1.95,
 1.77,
 1.7,
 1.86,
 1.86,
 1.82,
 1.78,
 1.79,
 1.96,
 1.85,
 1.77,
 1.84,
 1.83,
 1.8,
 1.8,
 1.92,
 1.83,
 1.82,
 1.85,
 1.78,
 1.77,
 1.74,
 1.91,
 1.88,
 1.86,
 1.86,
 1.91,
 1.86,
 1.88,
 1.9,
 1.71,
 1.89,
 1.89,
 1.88,
 1.9,
 1.94,
 1.8,
 2.0,
 1.82,
 1.95,
 1.87,
 1.9,
 1.88,
 1.88,
 1.8,
 1.88,
 1.9,
 1.85,
 1.76,
 1.84,
 1.87,
 1.89,
 1.85,
 1.92,
 1.83,
 1.87,
 1.8,
 1.75,
 1.84,
 1.75,
 1.92,
 1.9,
 1.87,
 1.92,
 1.86,
 1.75,
 1.74,
 1.72,
 1.87,
 1.7,
 1.84,
 1.81,
 1.73,
 1.76,
 1.7,
 1.81,
 1.75,
 1.81,
 1.84,
 1.8,
 1.78,
 1.88,
 1.72,
 1.81,
 1.78,
 1.77,
 1.92,
 1.94,
 1.97,
 1.89,
 1.75,
 1.81,
 1.76,
 1.71,
 1.75,
 1.72,
 1.74,
 1.66,
 1.86,
 1.87,
 1.7,
 1.82,
 1.88,
 1.91,
 1.71,
 1.88,
 1.83,
 1.92,
 1.69,
 1.79,
 1.85,
 1.86,
 1.82,
 1.8,
 1.69,
 1.96,
 1.78,
 1.84,
 1.9,
 1.86,
 1.85,
 1.87,
 1.82,
 1.78,
 1.73,
 1.76,
 1.85,
 1.75,
 1.82,
 1.79,
 1.75,
 1.82,
 1.85,
 1.74,
 1.9,
 1.9,
 1.93,
 1.77,
 1.71,
 1.86,
 1.79,
 1.71,
 1.88,
 1.76,
 1.72,
 1.74,
 1.8,
 1.89,
 1.92,
 1.72,
 1.89,
 1.83,
 1.88,
 1.9,
 1.89,
 1.7,
 1.85,
 1.88,
 1.93,
 1.88,
 1.81,
 1.76,
 1.86,
 1.87,
 1.75,
 1.9,
 1.78,
 1.77,
 1.71,
 1.88,
 1.85,
 1.77,
 1.81,
 1.82,
 1.76,
 1.79,
 1.9,
 1.85,
 1.86,
 1.9,
 1.78,
 1.75,
 1.84,
 1.82,
 1.79,
 1.92,
 1.75,
 1.71,
 1.88,
 1.77,
 1.78,
 1.85,
 1.83,
 1.87,
 1.91,
 1.75,
 1.79,
 1.89,
 1.73,
 1.82,
 1.78,
 1.72,
 1.72,
 1.72,
 1.87,
 1.75,
 1.87,
 1.75,
 1.87,
 1.81,
 1.91,
 1.8,
 1.85,
 1.81,
 1.73,
 1.8,
 1.87,
 1.86,
 1.81,
 1.89,
 1.73,
 1.83,
 1.7,
 1.9,
 1.83,
 1.85,
 1.79,
 1.82,
 1.78,
 1.81,
 1.87,
 1.85,
 1.79,
 1.81,
 1.8,
 1.87,
 1.86,
 1.77,
 1.82,
 1.75,
 1.95,
 1.88,
 1.82,
 1.78,
 1.73,
 1.85,
 1.82,
 1.79,
 1.84,
 1.8,
 1.81,
 1.82,
 1.77,
 1.76,
 1.89,
 1.78,
 1.84,
 1.78,
 1.87,
 1.85,
 1.74,
 1.8,
 1.88,
 1.94,
 1.86,
 1.63,
 1.8,
 1.9,
 1.85,
 1.91,
 1.88,
 1.89,
 1.72,
 1.92,
 1.87,
 1.81,
 1.84,
 1.81,
 1.9,
 1.76,
 1.84,
 1.68,
 1.9,
 1.84,
 1.81,
 1.8,
 1.84,
 1.84,
 1.77,
 1.85,
 1.88,
 1.69,
 1.86,
 1.77,
 1.75,
 1.79,
 1.8,
 1.86,
 1.76,
 1.75,
 1.77,
 1.68,
 1.8,
 1.9,
 1.79,
 1.74,
 1.96,
 1.91,
 1.78,
 1.84,
 1.75,
 1.89,
 1.75,
 1.71,
 1.72,
 1.95,
 1.93,
 1.83,
 1.88,
 1.8,
 1.75,
 1.84,
 1.85,
 1.8,
 1.76,
 1.81,
 1.92,
 1.85,
 1.81,
 1.76,
 1.86,
 1.88,
 1.77,
 1.75,
 1.68,
 1.86,
 1.77,
 1.84,
 1.87,
 1.72,
 1.86,
 1.85,
 1.86,
 1.78,
 1.78,
 1.8,
 1.75,
 1.86,
 1.92,
 1.83,
 1.74,
 1.87,
 1.82,
 1.86,
 1.89,
 1.87,
 1.75,
 1.84,
 1.76,
 1.85,
 1.86,
 1.83,
 1.76,
 1.76,
 1.78,
 1.87,
 1.8,
 1.8,
 1.83,
 1.78,
 1.7,
 1.77,
 1.78,
 1.82,
 1.74,
 1.79,
 1.87,
 1.73,
 1.95,
 1.92,
 1.77,
 1.88,
 1.94,
 1.8,
 1.87,
 1.71,
 1.97,
 1.79,
 1.7,
 1.73,
 1.83,
 1.91,
 1.8,
 1.81,
 1.82,
 1.77,
 1.78,
 1.9,
 1.63,
 1.8,
 1.84,
 1.81,
 1.86,
 1.73,
 1.86,
 1.7,
 1.78,
 1.8,
 1.83,
 1.9,
 1.87,
 1.83,
 1.8,
 1.82,
 1.77,
 1.84,
 1.74,
 1.77,
 1.84,
 1.93,
 1.85,
 1.9,
 1.7,
 1.8,
 1.84,
 1.84,
 1.88,
 1.75,
 1.81,
 1.87,
 1.71,
 1.86,
 1.71,
 1.96,
 1.82,
 1.78,
 1.82,
 1.94,
 1.8,
 1.9,
 1.81,
 1.74,
 1.96,
 1.96,
 1.92,
 1.86,
 1.76,
 1.86,
 1.79,
 1.84,
 1.87,
 1.8,
 1.85,
 1.76,
 1.92,
 1.77,
 1.82,
 1.93,
 1.74,
 1.72,
 1.7,
 1.67,
 1.67,
 1.93,
 1.72,
 1.84,
 1.86,
 1.78,
 1.83,
 1.86,
 1.93,
 1.87,
 1.74,
 1.85,
 1.88,
 1.75,
 1.72,
 1.79,
 1.72,
 1.76,
 1.75,
 1.83,
 1.82,
 1.82,
 1.76,
 1.81,
 1.92,
 1.9,
 1.93,
 1.75,
 1.83,
 1.88,
 1.85,
 1.91,
 1.8,
 1.86,
 1.83,
 1.83,
 1.67,
 1.94,
 1.86,
 1.68,
 1.87,
 1.93,
 1.75,
 1.87,
 1.73,
 1.9,
 1.86,
 1.9,
 1.79,
 1.96,
 1.75,
 1.74,
 1.76,
 1.72,
 1.88,
 1.85,
 1.88,
 1.7,
 1.73,
 1.75,
 1.76,
 1.9,
 1.82,
 1.69,
 1.86,
 1.79,
 1.86,
 1.85,
 1.9,
 1.76,
 1.87,
 1.65,
 1.78,
 1.79,
 1.87,
 1.9,
 1.75,
 1.9,
 1.77,
 1.72,
 1.83,
 1.85,
 1.85,
 1.85,
 1.79,
 1.88,
 1.8,
 1.89,
 1.74,
 1.75,
 1.95,
 1.87,
 1.68,
 1.65,
 1.74,
 1.87,
 1.84,
 1.7,
 1.76,
 1.85,
 1.82,
 1.86,
 1.85,
 1.78,
 1.82,
 1.91,
 1.82,
 1.89,
 1.91,
 1.73,
 1.75,
 1.88,
 1.8,
 1.87,
 1.82,
 1.7,
 1.74,
 1.81,
 1.88,
 1.87,
 1.88,
 1.84,
 1.8796000000000002,
 1.83,
 1.91,
 1.88,
 1.83,
 1.88,
 1.86,
 1.84,
 1.92,
 1.91,
 1.96,
 1.73,
 1.72,
 1.78,
 1.82,
 1.81,
 1.92,
 1.72,
 1.64,
 1.84,
 1.76,
 1.69,
 1.88,
 1.85,
 1.75,
 1.89,
 1.95,
 1.79,
 1.91,
 1.7,
 1.82,
 1.95,
 1.78,
 1.87,
 1.87,
 1.9,
 1.88,
 1.98,
 1.8,
 1.72,
 1.89,
 1.92,
 1.79,
 1.84,
 1.86,
 1.78,
 1.73,
 1.76,
 1.73,
 1.87,
 1.82,
 1.86,
 1.88,
 1.7,
 1.9050000000000002,
 1.9558000000000002,
 1.85,
 1.79,
 1.95,
 1.79,
 1.85,
 1.74,
 1.83,
 1.8,
 1.81,
 1.86,
 1.78,
 1.8034,
 1.9304000000000001,
 1.8542000000000003,
 1.8288000000000002,
 1.8542000000000003,
 1.8034,
 1.8796000000000002,
 1.8288000000000002,
 1.9050000000000002,
 1.8288000000000002,
 1.84,
 1.778,
 1.7526,
 1.8034,
 1.6764000000000001,
 1.8542000000000003,
 1.8288000000000002,
 1.9304000000000001,
 1.7018,
 1.8288000000000002,
 1.8034,
 1.8034,
 1.88,
 1.8288000000000002,
 1.778,
 1.9050000000000002,
 1.8288000000000002,
 1.6256,
 1.8034,
 1.7526,
 1.7018,
 1.8288000000000002,
 1.778,
 1.8796000000000002,
 1.8796000000000002,
 1.9050000000000002,
 1.7018,
 1.778,
 1.7526,
 1.83,
 1.83,
 1.8,
 1.82,
 1.82,
 1.85,
 1.73,
 1.76,
 1.88,
 1.85,
 1.82,
 1.83,
 1.84,
 1.68,
 1.9,
 1.8,
 1.79,
 1.76,
 1.77,
 1.87,
 1.76,
 1.77,
 1.74,
 1.66,
 1.94,
 1.88,
 1.8,
 1.84,
 1.9,
 1.85,
 1.87,
 1.75,
 1.86,
 1.87,
 1.8,
 1.79,
 1.8,
 1.81,
 1.86,
 1.74,
 1.91,
 1.74,
 1.7,
 1.81,
 1.84,
 1.97,
 1.71,
 1.83,
 1.87,
 1.79,
 1.82,
 1.89,
 1.75,
 1.92,
 1.83,
 1.91,
 1.72,
 1.87,
 1.88,
 1.91,
 1.86,
 1.74,
 1.87,
 1.8,
 1.88,
 1.86,
 1.86,
 1.72,
 1.92,
 1.83,
 1.9,
 1.76,
 1.84,
 1.65,
 1.8,
 1.83,
 1.84,
 1.87,
 1.8,
 1.87,
 1.77,
 1.78,
 1.82,
 1.78,
 1.75,
 1.87,
 1.7,
 1.82,
 1.83,
 1.87,
 1.93,
 1.83,
 1.78,
 1.75,
 1.85,
 1.88,
 1.86,
 1.89,
 1.85,
 1.74,
 1.79,
 ...]

In [40]:
dfNew['ht(m)'] = hList
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,ST,LW,LM,LB,RWB,W/F1,SM1,IR1,wt(kg),ht(m)
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,1,0,0,0,0,4,4,5,72.0,1.70
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,1,1,0,0,0,4,5,5,83.0,1.87
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,0,0,0,0,0,3,1,3,87.0,1.88
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,0,0,0,0,0,5,4,4,70.0,1.81
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,0,1,0,0,0,5,5,5,68.0,1.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,0,0,0,0,0,2,2,1,66.0,1.78
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,0,0,0,0,0,2,2,1,65.0,1.75
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,0,0,0,0,0,2,2,1,74.0,1.79
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,0,0,3,2,1,69.0,1.75
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,1,0,3,2,1,75.0,1.88

In [41]:
dfNew.values[19020]

array([252520, 'Zhou Xiao', 'Xiao Zhou',
       'https://cdn.sofifa.com/players/252/520/21_60.png',
       'http://sofifa.com/player/252520/xiao-zhou/210006/', 'China PR',
       21, 47.0, 57.0, '\n\n\n\nDalian YiFang FC', '2019 ~ 2023',
       'CB, LB', '188cm', '75kg', 'Left', 50, 'LB', '29-Jul-19', nan,
       '€100K', '€1K', '€79K', 163.0, 40.0, 18.0, 40.0, 45.0, 20.0, 171.0,
       40, 33.0, 20.0, 40.0, 38.0, 279.0, 60.0, 63.0, 57.0, 47.0, 52.0,
       231.0, 37.0, 66.0, 60.0, 55.0, 13.0, 185.0, 45, 47.0, 33.0, 33,
       27.0, 33.0, 136.0, 45.0, 46.0, 45.0, 50.0, 10.0, 11.0, 7.0, 10.0,
       12, 1215.0, 265, '3 ★', '2★', 'Medium', 'Medium', '1 ★', 62.0,
       22.0, 39.0, 42.0, 45.0, 55.0, nan, 'xiao zhou', 'Active', 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 3, 2, 1, 75.0, 1.88],
      dtype=object)

Task 5 - Value, Wage and Release Clause columns: convert to Float

In [42]:
df_musket.Value.unique() # checking the unique contents under Value

array(['€103.5M', '€63M', '€120M', '€129M', '€132M', '€111M', '€120.5M',
       '€102M', '€185.5M', '€110M', '€113M', '€90.5M', '€82M', '€17.5M',
       '€83.5M', '€33.5M', '€114.5M', '€78M', '€103M', '€109M', '€92M',
       '€10M', '€76.5M', '€89.5M', '€87.5M', '€79.5M', '€124M', '€114M',
       '€95M', '€92.5M', '€105.5M', '€88.5M', '€85M', '€81.5M', '€26M',
       '€21M', '€56M', '€67.5M', '€53M', '€36.5M', '€51M', '€65.5M',
       '€46.5M', '€61.5M', '€72.5M', '€77.5M', '€43.5M', '€32.5M', '€36M',
       '€32M', '€54M', '€49.5M', '€57M', '€66.5M', '€74.5M', '€71.5M',
       '€121M', '€99M', '€67M', '€86.5M', '€93.5M', '€70M', '€62M',
       '€66M', '€58M', '€44M', '€81M', '€37M', '€14.5M', '€46M', '€47.5M',
       '€52.5M', '€54.5M', '€34.5M', '€57.5M', '€51.5M', '€44.5M', '€55M',
       '€48M', '€60.5M', '€63.5M', '€61M', '€29M', '€58.5M', '€55.5M',
       '€42M', '€40.5M', '€43M', '€45.5M', '€34M', '€26.5M', '€42.5M',
       '€35.5M', '€45M', '€41.5M', '€40M', '€11M', '€13.5M', '€29.5M',
       '€27M', '€15.5M', '€38.5M', '€52M', '€33M', '€19M', '€73.5M',
       '€38M', '€35M', '€47M', '€24M', '€30.5M', '€18M', '€28M', '€25.5M',
       '€25M', '€31M', '€23.5M', '€30M', '€31.5M', '€22.5M', '€28.5M',
       '€4M', '€12.5M', '€37.5M', '€27.5M', '€16M', '€15M', '€20.5M',
       '€22M', '€3.4M', '€5M', '€56.5M', '€62.5M', '€0', '€39M', '€24.5M',
       '€21.5M', '€13M', '€8M', '€20M', '€8.5M', '€2.9M', '€9M', '€4.6M',
       '€50M', '€23M', '€18.5M', '€7M', '€19.5M', '€5.5M', '€7.5M',
       '€3.8M', '€14M', '€10.5M', '€16.5M', '€3.6M', '€9.5M', '€39.5M',
       '€17M', '€12M', '€11.5M', '€4.9M', '€3M', '€1.9M', '€6.5M',
       '€1.7M', '€2.4M', '€3.1M', '€6M', '€3.7M', '€4.7M', '€4.3M',
       '€2.1M', '€1.2M', '€1.8M', '€4.8M', '€3.2M', '€1.3M', '€825K',
       '€2.3M', '€1.5M', '€3.9M', '€2.6M', '€3.5M', '€2.8M', '€2.7M',
       '€4.4M', '€4.1M', '€950K', '€1.6M', '€625K', '€1.1M', '€4.5M',
       '€4.2M', '€2.2M', '€3.3M', '€1.4M', '€2M', '€475K', '€925K',
       '€750K', '€725K', '€2.5M', '€1M', '€350K', '€525K', '€600K',
       '€850K', '€800K', '€550K', '€250K', '€400K', '€425K', '€575K',
       '€210K', '€325K', '€900K', '€875K', '€650K', '€700K', '€500K',
       '€975K', '€375K', '€775K', '€275K', '€180K', '€450K', '€675K',
       '€150K', '€240K', '€300K', '€130K', '€220K', '€200K', '€110K',
       '€170K', '€230K', '€90K', '€120K', '€80K', '€190K', '€140K',
       '€160K', '€100K', '€60K', '€50K', '€70K', '€45K', '€35K', '€40K',
       '€25K', '€20K', '€15K', '€30K', '€9K'], dtype=object)

In [43]:
vaList = [] 
for val in df_musket.Value:
    if 'K' in val:
        val=float(val[1:-1])*1000 
        vaList.append(val)
    elif 'M' in val:
        val = float(val[1:-1])*1000000
        vaList.append(val)
    else:
        vaList.append(float(0))
vaList

[103500000.0,
 63000000.0,
 120000000.0,
 129000000.0,
 132000000.0,
 111000000.0,
 120500000.0,
 102000000.0,
 185500000.0,
 110000000.0,
 113000000.0,
 120500000.0,
 90500000.0,
 82000000.0,
 17500000.0,
 83500000.0,
 33500000.0,
 83500000.0,
 114500000.0,
 78000000.0,
 103000000.0,
 109000000.0,
 92000000.0,
 109000000.0,
 10000000.0,
 76500000.0,
 89500000.0,
 87500000.0,
 79500000.0,
 124000000.0,
 114000000.0,
 95000000.0,
 90500000.0,
 92500000.0,
 105500000.0,
 88500000.0,
 85000000.0,
 81500000.0,
 26000000.0,
 21000000.0,
 56000000.0,
 67500000.0,
 53000000.0,
 63000000.0,
 36500000.0,
 51000000.0,
 26000000.0,
 78000000.0,
 65500000.0,
 46500000.0,
 61500000.0,
 72500000.0,
 77500000.0,
 77500000.0,
 43500000.0,
 32500000.0,
 46500000.0,
 36000000.0,
 32000000.0,
 54000000.0,
 49500000.0,
 57000000.0,
 66500000.0,
 74500000.0,
 71500000.0,
 121000000.0,
 99000000.0,
 67000000.0,
 86500000.0,
 93500000.0,
 70000000.0,
 81500000.0,
 62000000.0,
 67000000.0,
 66000000.0,
 53000000.0,
 58000000.0,
 74500000.0,
 44000000.0,
 63000000.0,
 81000000.0,
 53000000.0,
 37000000.0,
 14500000.0,
 54000000.0,
 46000000.0,
 63000000.0,
 47500000.0,
 52500000.0,
 46500000.0,
 54500000.0,
 36000000.0,
 26000000.0,
 34500000.0,
 57500000.0,
 17500000.0,
 52500000.0,
 51500000.0,
 44500000.0,
 55000000.0,
 52500000.0,
 48000000.0,
 60500000.0,
 66500000.0,
 86500000.0,
 92000000.0,
 44500000.0,
 60500000.0,
 56000000.0,
 63500000.0,
 57500000.0,
 49500000.0,
 61000000.0,
 29000000.0,
 58500000.0,
 55500000.0,
 48000000.0,
 42000000.0,
 40500000.0,
 42000000.0,
 43000000.0,
 45500000.0,
 32500000.0,
 34000000.0,
 26500000.0,
 40500000.0,
 42500000.0,
 36500000.0,
 35500000.0,
 45000000.0,
 34000000.0,
 41500000.0,
 40000000.0,
 11000000.0,
 21000000.0,
 36500000.0,
 13500000.0,
 13500000.0,
 29500000.0,
 21000000.0,
 27000000.0,
 15500000.0,
 56000000.0,
 49500000.0,
 57500000.0,
 38500000.0,
 36500000.0,
 52000000.0,
 47500000.0,
 43000000.0,
 33000000.0,
 56000000.0,
 49500000.0,
 58500000.0,
 52000000.0,
 42500000.0,
 19000000.0,
 38500000.0,
 73500000.0,
 37000000.0,
 52500000.0,
 38500000.0,
 38500000.0,
 42500000.0,
 38500000.0,
 49500000.0,
 52000000.0,
 43500000.0,
 45500000.0,
 38000000.0,
 35000000.0,
 42000000.0,
 36500000.0,
 36500000.0,
 44500000.0,
 36500000.0,
 47000000.0,
 43500000.0,
 24000000.0,
 30500000.0,
 18000000.0,
 32000000.0,
 33000000.0,
 28000000.0,
 25500000.0,
 34500000.0,
 25000000.0,
 36500000.0,
 38500000.0,
 33500000.0,
 24000000.0,
 38500000.0,
 36500000.0,
 36500000.0,
 31000000.0,
 23500000.0,
 35500000.0,
 25000000.0,
 30000000.0,
 31500000.0,
 35500000.0,
 22500000.0,
 17500000.0,
 29000000.0,
 25000000.0,
 35000000.0,
 28500000.0,
 17500000.0,
 4000000.0,
 12500000.0,
 30000000.0,
 22500000.0,
 29500000.0,
 28500000.0,
 41500000.0,
 29000000.0,
 32500000.0,
 24000000.0,
 26500000.0,
 46000000.0,
 40000000.0,
 40500000.0,
 40000000.0,
 46000000.0,
 28000000.0,
 34000000.0,
 43500000.0,
 33500000.0,
 58000000.0,
 30500000.0,
 30500000.0,
 34500000.0,
 36500000.0,
 33500000.0,
 37500000.0,
 31500000.0,
 26000000.0,
 27500000.0,
 40000000.0,
 40500000.0,
 26000000.0,
 48000000.0,
 16000000.0,
 15000000.0,
 34500000.0,
 25000000.0,
 24000000.0,
 30500000.0,
 32000000.0,
 27000000.0,
 20500000.0,
 28000000.0,
 15000000.0,
 30500000.0,
 27000000.0,
 35500000.0,
 28000000.0,
 29500000.0,
 29500000.0,
 20500000.0,
 16000000.0,
 22000000.0,
 3400000.0,
 29500000.0,
 10000000.0,
 25000000.0,
 19000000.0,
 24000000.0,
 25000000.0,
 25500000.0,
 5000000.0,
 11000000.0,
 21000000.0,
 25000000.0,
 57500000.0,
 30500000.0,
 58000000.0,
 37000000.0,
 51000000.0,
 56500000.0,
 62500000.0,
 38500000.0,
 37000000.0,
 30000000.0,
 53000000.0,
 25500000.0,
 52000000.0,
 26500000.0,
 29500000.0,
 0.0,
 26500000.0,
 23500000.0,
 0.0,
 34500000.0,
 41500000.0,
 34500000.0,
 20500000.0,
 28000000.0,
 33000000.0,
 23500000.0,
 31000000.0,
 36500000.0,
 28000000.0,
 37000000.0,
 35500000.0,
 39000000.0,
 33500000.0,
 34000000.0,
 31500000.0,
 31000000.0,
 24500000.0,
 34500000.0,
 25500000.0,
 37000000.0,
 29500000.0,
 37500000.0,
 30500000.0,
 28000000.0,
 40500000.0,
 22000000.0,
 34500000.0,
 22500000.0,
 13500000.0,
 26000000.0,
 21500000.0,
 25000000.0,
 27500000.0,
 27500000.0,
 34000000.0,
 26000000.0,
 24000000.0,
 21000000.0,
 23500000.0,
 22500000.0,
 28000000.0,
 31500000.0,
 27500000.0,
 23500000.0,
 28000000.0,
 31000000.0,
 26000000.0,
 13500000.0,
 26000000.0,
 23500000.0,
 32500000.0,
 13000000.0,
 22000000.0,
 25000000.0,
 17500000.0,
 18000000.0,
 8000000.0,
 22500000.0,
 26000000.0,
 25500000.0,
 20500000.0,
 20500000.0,
 16000000.0,
 18000000.0,
 20500000.0,
 12500000.0,
 20000000.0,
 8500000.0,
 2900000.0,
 8500000.0,
 9000000.0,
 24500000.0,
 4600000.0,
 20000000.0,
 12500000.0,
 0.0,
 50000000.0,
 32000000.0,
 24500000.0,
 34000000.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 42000000.0,
 22000000.0,
 32000000.0,
 34000000.0,
 36000000.0,
 29000000.0,
 40000000.0,
 27000000.0,
 43000000.0,
 29000000.0,
 30000000.0,
 33000000.0,
 13500000.0,
 34000000.0,
 29500000.0,
 24000000.0,
 0.0,
 22000000.0,
 32500000.0,
 25000000.0,
 25000000.0,
 40500000.0,
 23000000.0,
 20500000.0,
 31500000.0,
 33000000.0,
 33500000.0,
 18000000.0,
 33500000.0,
 42000000.0,
 27500000.0,
 28000000.0,
 29000000.0,
 29000000.0,
 26500000.0,
 29500000.0,
 18500000.0,
 27500000.0,
 21000000.0,
 27500000.0,
 27500000.0,
 24500000.0,
 28000000.0,
 29000000.0,
 18500000.0,
 28000000.0,
 28000000.0,
 7000000.0,
 20500000.0,
 25000000.0,
 19000000.0,
 25000000.0,
 24500000.0,
 26000000.0,
 24000000.0,
 19500000.0,
 34000000.0,
 19000000.0,
 25000000.0,
 21500000.0,
 24000000.0,
 22000000.0,
 17500000.0,
 16000000.0,
 22500000.0,
 25000000.0,
 21000000.0,
 22000000.0,
 17500000.0,
 24500000.0,
 19000000.0,
 29000000.0,
 14500000.0,
 21000000.0,
 21000000.0,
 17500000.0,
 18000000.0,
 18000000.0,
 21000000.0,
 18500000.0,
 17500000.0,
 18000000.0,
 21500000.0,
 23000000.0,
 17500000.0,
 7000000.0,
 17500000.0,
 18500000.0,
 20500000.0,
 13000000.0,
 21000000.0,
 15000000.0,
 5500000.0,
 13000000.0,
 7500000.0,
 7000000.0,
 3800000.0,
 14500000.0,
 18000000.0,
 10000000.0,
 20500000.0,
 7000000.0,
 14000000.0,
 17500000.0,
 17500000.0,
 20000000.0,
 7000000.0,
 20500000.0,
 5500000.0,
 17500000.0,
 25000000.0,
 10500000.0,
 15500000.0,
 7000000.0,
 13500000.0,
 21000000.0,
 10500000.0,
 16500000.0,
 13500000.0,
 16500000.0,
 3600000.0,
 13000000.0,
 9500000.0,
 7000000.0,
 7000000.0,
 0.0,
 11000000.0,
 0.0,
 0.0,
 0.0,
 23000000.0,
 26000000.0,
 39500000.0,
 38000000.0,
 33000000.0,
 21500000.0,
 33000000.0,
 26000000.0,
 26000000.0,
 23500000.0,
 34000000.0,
 38500000.0,
 24000000.0,
 33500000.0,
 24500000.0,
 35000000.0,
 23500000.0,
 28000000.0,
 35500000.0,
 24000000.0,
 33500000.0,
 26500000.0,
 22000000.0,
 24500000.0,
 35000000.0,
 39500000.0,
 20000000.0,
 20000000.0,
 12500000.0,
 17500000.0,
 18000000.0,
 16000000.0,
 18000000.0,
 37000000.0,
 28000000.0,
 27000000.0,
 26000000.0,
 23000000.0,
 26500000.0,
 15000000.0,
 17500000.0,
 21500000.0,
 25000000.0,
 25000000.0,
 16000000.0,
 20500000.0,
 25000000.0,
 23000000.0,
 27500000.0,
 20500000.0,
 12500000.0,
 21500000.0,
 20000000.0,
 28000000.0,
 27000000.0,
 22000000.0,
 16000000.0,
 21000000.0,
 21500000.0,
 21000000.0,
 21500000.0,
 24500000.0,
 27500000.0,
 20500000.0,
 14000000.0,
 17000000.0,
 17500000.0,
 19000000.0,
 12000000.0,
 17000000.0,
 0.0,
 26500000.0,
 15500000.0,
 17500000.0,
 24000000.0,
 21000000.0,
 24000000.0,
 16000000.0,
 19000000.0,
 20500000.0,
 19000000.0,
 25000000.0,
 27500000.0,
 19000000.0,
 15000000.0,
 17500000.0,
 17500000.0,
 17000000.0,
 11500000.0,
 19000000.0,
 22000000.0,
 18000000.0,
 18000000.0,
 17500000.0,
 19000000.0,
 17000000.0,
 20500000.0,
 23000000.0,
 18500000.0,
 14500000.0,
 15000000.0,
 24500000.0,
 18500000.0,
 15500000.0,
 16000000.0,
 17000000.0,
 14500000.0,
 15000000.0,
 20500000.0,
 11000000.0,
 17000000.0,
 21000000.0,
 17000000.0,
 15500000.0,
 20000000.0,
 19000000.0,
 16500000.0,
 13500000.0,
 17000000.0,
 15000000.0,
 14500000.0,
 15000000.0,
 16000000.0,
 18000000.0,
 20000000.0,
 20500000.0,
 18000000.0,
 17000000.0,
 12000000.0,
 18500000.0,
 8000000.0,
 14500000.0,
 17000000.0,
 18500000.0,
 15000000.0,
 14500000.0,
 14500000.0,
 11500000.0,
 14000000.0,
 17000000.0,
 12500000.0,
 0.0,
 9500000.0,
 11000000.0,
 17000000.0,
 17000000.0,
 14500000.0,
 4900000.0,
 17000000.0,
 11000000.0,
 14500000.0,
 9000000.0,
 5500000.0,
 12500000.0,
 14500000.0,
 11000000.0,
 15500000.0,
 11000000.0,
 14000000.0,
 7000000.0,
 8500000.0,
 3000000.0,
 11000000.0,
 22500000.0,
 11500000.0,
 8000000.0,
 9500000.0,
 5500000.0,
 1900000.0,
 8500000.0,
 3400000.0,
 3000000.0,
 1900000.0,
 5500000.0,
 6500000.0,
 11000000.0,
 31000000.0,
 0.0,
 13500000.0,
 34000000.0,
 0.0,
 31500000.0,
 0.0,
 30000000.0,
 29500000.0,
 27500000.0,
 16500000.0,
 27000000.0,
 31000000.0,
 18500000.0,
 11500000.0,
 29000000.0,
 31000000.0,
 20000000.0,
 21000000.0,
 31500000.0,
 22500000.0,
 29500000.0,
 22000000.0,
 21000000.0,
 31500000.0,
 18500000.0,
 23000000.0,
 16000000.0,
 22500000.0,
 17500000.0,
 22500000.0,
 26500000.0,
 29000000.0,
 29000000.0,
 27000000.0,
 16500000.0,
 28500000.0,
 16000000.0,
 14000000.0,
 31500000.0,
 11500000.0,
 15500000.0,
 16000000.0,
 14000000.0,
 14500000.0,
 14000000.0,
 14000000.0,
 9500000.0,
 14500000.0,
 19000000.0,
 16000000.0,
 22500000.0,
 20500000.0,
 16000000.0,
 21000000.0,
 20000000.0,
 30000000.0,
 16500000.0,
 18000000.0,
 27000000.0,
 21000000.0,
 18000000.0,
 17000000.0,
 15000000.0,
 21000000.0,
 15000000.0,
 11000000.0,
 16500000.0,
 14000000.0,
 16500000.0,
 21000000.0,
 20000000.0,
 14500000.0,
 21500000.0,
 15500000.0,
 18500000.0,
 11000000.0,
 16500000.0,
 21000000.0,
 17500000.0,
 12500000.0,
 20500000.0,
 9500000.0,
 12500000.0,
 12000000.0,
 19500000.0,
 9500000.0,
 17500000.0,
 13500000.0,
 22000000.0,
 16500000.0,
 18500000.0,
 17500000.0,
 15000000.0,
 10000000.0,
 16500000.0,
 15000000.0,
 14000000.0,
 17000000.0,
 14000000.0,
 15000000.0,
 18000000.0,
 16500000.0,
 20000000.0,
 21500000.0,
 22000000.0,
 1700000.0,
 15000000.0,
 12000000.0,
 7000000.0,
 12000000.0,
 11500000.0,
 18000000.0,
 14500000.0,
 17500000.0,
 14000000.0,
 9500000.0,
 16500000.0,
 18500000.0,
 14000000.0,
 13500000.0,
 15000000.0,
 11500000.0,
 14000000.0,
 15000000.0,
 12000000.0,
 16500000.0,
 11000000.0,
 15000000.0,
 17000000.0,
 12500000.0,
 14000000.0,
 14000000.0,
 13500000.0,
 9500000.0,
 14000000.0,
 13500000.0,
 15000000.0,
 14000000.0,
 13500000.0,
 15000000.0,
 17500000.0,
 13000000.0,
 2400000.0,
 14000000.0,
 13500000.0,
 9000000.0,
 14000000.0,
 14000000.0,
 9500000.0,
 18000000.0,
 12500000.0,
 16500000.0,
 16500000.0,
 12500000.0,
 2400000.0,
 10000000.0,
 15000000.0,
 19000000.0,
 15000000.0,
 3100000.0,
 9500000.0,
 13500000.0,
 12000000.0,
 2400000.0,
 9000000.0,
 7000000.0,
 10000000.0,
 6500000.0,
 6000000.0,
 9000000.0,
 14000000.0,
 14000000.0,
 10500000.0,
 6500000.0,
 8500000.0,
 6500000.0,
 8500000.0,
 9000000.0,
 6500000.0,
 8500000.0,
 10500000.0,
 10500000.0,
 14000000.0,
 8500000.0,
 8500000.0,
 10500000.0,
 12000000.0,
 6500000.0,
 5000000.0,
 1700000.0,
 8000000.0,
 8500000.0,
 8000000.0,
 8500000.0,
 12000000.0,
 6500000.0,
 4000000.0,
 8000000.0,
 9500000.0,
 9000000.0,
 6500000.0,
 3600000.0,
 3700000.0,
 4700000.0,
 4300000.0,
 3700000.0,
 5500000.0,
 2100000.0,
 6000000.0,
 10000000.0,
 3700000.0,
 10500000.0,
 8500000.0,
 16000000.0,
 10500000.0,
 10000000.0,
 12500000.0,
 16500000.0,
 22000000.0,
 14500000.0,
 7000000.0,
 8500000.0,
 16000000.0,
 15000000.0,
 12500000.0,
 7000000.0,
 16000000.0,
 23500000.0,
 4900000.0,
 16000000.0,
 11500000.0,
 4900000.0,
 13000000.0,
 12000000.0,
 4900000.0,
 9000000.0,
 9500000.0,
 7500000.0,
 12500000.0,
 5000000.0,
 11000000.0,
 9500000.0,
 10500000.0,
 7000000.0,
 1200000.0,
 10000000.0,
 12000000.0,
 0.0,
 10500000.0,
 10500000.0,
 11000000.0,
 19500000.0,
 14000000.0,
 7500000.0,
 13000000.0,
 10500000.0,
 5500000.0,
 15500000.0,
 10500000.0,
 22000000.0,
 14000000.0,
 11000000.0,
 12000000.0,
 16000000.0,
 20000000.0,
 10500000.0,
 7000000.0,
 10500000.0,
 8500000.0,
 5000000.0,
 7000000.0,
 10500000.0,
 11500000.0,
 10500000.0,
 9000000.0,
 15500000.0,
 21500000.0,
 9000000.0,
 10000000.0,
 10500000.0,
 14000000.0,
 12000000.0,
 9500000.0,
 11000000.0,
 9500000.0,
 15000000.0,
 16000000.0,
 7000000.0,
 0.0,
 10000000.0,
 8500000.0,
 10500000.0,
 15500000.0,
 10500000.0,
 8500000.0,
 9500000.0,
 5000000.0,
 12500000.0,
 3400000.0,
 9500000.0,
 8500000.0,
 10000000.0,
 9000000.0,
 9000000.0,
 3400000.0,
 12500000.0,
 8500000.0,
 23000000.0,
 7500000.0,
 5500000.0,
 7500000.0,
 10500000.0,
 ...]

In [44]:
dfNew['Value(€)'] = vaList
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,LW,LM,LB,RWB,W/F1,SM1,IR1,wt(kg),ht(m),Value(€)
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,0,0,0,0,4,4,5,72.0,1.70,103500000.0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,1,0,0,0,4,5,5,83.0,1.87,63000000.0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,0,0,0,0,3,1,3,87.0,1.88,120000000.0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,0,0,0,0,5,4,4,70.0,1.81,129000000.0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,1,0,0,0,5,5,5,68.0,1.75,132000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,0,0,0,0,2,2,1,66.0,1.78,100000.0
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,0,0,0,0,2,2,1,65.0,1.75,130000.0
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,0,0,0,0,2,2,1,74.0,1.79,120000.0
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,0,3,2,1,69.0,1.75,100000.0
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,1,0,3,2,1,75.0,1.88,100000.0

In [45]:
df_musket.Wage.unique() # checking the unique contents under Wage

array(['€560K', '€220K', '€125K', '€370K', '€270K', '€240K', '€250K',
       '€160K', '€260K', '€210K', '€310K', '€130K', '€350K', '€300K',
       '€190K', '€145K', '€195K', '€100K', '€140K', '€290K', '€82K',
       '€110K', '€230K', '€155K', '€200K', '€165K', '€95K', '€170K',
       '€105K', '€115K', '€150K', '€135K', '€55K', '€58K', '€81K', '€34K',
       '€120K', '€59K', '€90K', '€65K', '€56K', '€71K', '€18K', '€75K',
       '€47K', '€20K', '€84K', '€86K', '€74K', '€78K', '€27K', '€68K',
       '€85K', '€25K', '€46K', '€83K', '€54K', '€79K', '€175K', '€43K',
       '€49K', '€45K', '€38K', '€41K', '€39K', '€23K', '€51K', '€50K',
       '€87K', '€30K', '€14K', '€69K', '€31K', '€64K', '€53K', '€35K',
       '€21K', '€28K', '€17K', '€33K', '€70K', '€32K', '€89K', '€26K',
       '€40K', '€76K', '€72K', '€48K', '€36K', '€29K', '€60K', '€16K',
       '€37K', '€24K', '€52K', '€0', '€62K', '€73K', '€63K', '€19K',
       '€1K', '€66K', '€80K', '€12K', '€2K', '€42K', '€13K', '€900',
       '€57K', '€77K', '€61K', '€22K', '€67K', '€44K', '€15K', '€11K',
       '€8K', '€850', '€10K', '€88K', '€500', '€7K', '€6K', '€9K', '€5K',
       '€700', '€950', '€750', '€3K', '€650', '€600', '€4K', '€800',
       '€550'], dtype=object)

In [46]:
waList = [] # for Wage
for val in df_musket.Wage:
    if 'K' in val:
        val=float(val[1:-1])*1000
        waList.append(val)
    else:
        val=float(val[1:])*1000
        waList.append(val)
waList

[560000.0,
 220000.0,
 125000.0,
 370000.0,
 270000.0,
 240000.0,
 250000.0,
 160000.0,
 160000.0,
 260000.0,
 210000.0,
 250000.0,
 310000.0,
 250000.0,
 130000.0,
 350000.0,
 300000.0,
 300000.0,
 270000.0,
 190000.0,
 145000.0,
 190000.0,
 195000.0,
 220000.0,
 100000.0,
 140000.0,
 350000.0,
 310000.0,
 290000.0,
 82000.0,
 110000.0,
 230000.0,
 155000.0,
 200000.0,
 195000.0,
 155000.0,
 165000.0,
 190000.0,
 110000.0,
 95000.0,
 240000.0,
 170000.0,
 105000.0,
 160000.0,
 260000.0,
 115000.0,
 125000.0,
 125000.0,
 130000.0,
 150000.0,
 230000.0,
 220000.0,
 135000.0,
 190000.0,
 160000.0,
 220000.0,
 95000.0,
 55000.0,
 58000.0,
 100000.0,
 220000.0,
 140000.0,
 145000.0,
 95000.0,
 115000.0,
 105000.0,
 81000.0,
 130000.0,
 150000.0,
 34000.0,
 100000.0,
 100000.0,
 140000.0,
 190000.0,
 115000.0,
 210000.0,
 120000.0,
 135000.0,
 59000.0,
 135000.0,
 190000.0,
 120000.0,
 130000.0,
 95000.0,
 90000.0,
 105000.0,
 165000.0,
 120000.0,
 150000.0,
 170000.0,
 155000.0,
 65000.0,
 110000.0,
 115000.0,
 100000.0,
 56000.0,
 150000.0,
 220000.0,
 95000.0,
 95000.0,
 71000.0,
 18000.0,
 75000.0,
 47000.0,
 130000.0,
 56000.0,
 145000.0,
 95000.0,
 20000.0,
 100000.0,
 84000.0,
 86000.0,
 155000.0,
 74000.0,
 105000.0,
 78000.0,
 120000.0,
 90000.0,
 27000.0,
 140000.0,
 125000.0,
 110000.0,
 68000.0,
 90000.0,
 85000.0,
 25000.0,
 210000.0,
 105000.0,
 105000.0,
 25000.0,
 46000.0,
 110000.0,
 130000.0,
 110000.0,
 83000.0,
 120000.0,
 54000.0,
 90000.0,
 79000.0,
 90000.0,
 175000.0,
 43000.0,
 90000.0,
 160000.0,
 175000.0,
 79000.0,
 49000.0,
 115000.0,
 45000.0,
 38000.0,
 41000.0,
 105000.0,
 95000.0,
 135000.0,
 125000.0,
 25000.0,
 47000.0,
 39000.0,
 135000.0,
 56000.0,
 150000.0,
 23000.0,
 120000.0,
 58000.0,
 45000.0,
 46000.0,
 105000.0,
 140000.0,
 51000.0,
 95000.0,
 59000.0,
 170000.0,
 125000.0,
 50000.0,
 74000.0,
 87000.0,
 120000.0,
 100000.0,
 39000.0,
 30000.0,
 14000.0,
 71000.0,
 175000.0,
 69000.0,
 79000.0,
 115000.0,
 31000.0,
 125000.0,
 82000.0,
 84000.0,
 64000.0,
 41000.0,
 190000.0,
 25000.0,
 53000.0,
 75000.0,
 160000.0,
 35000.0,
 39000.0,
 35000.0,
 115000.0,
 125000.0,
 39000.0,
 125000.0,
 170000.0,
 200000.0,
 55000.0,
 21000.0,
 28000.0,
 49000.0,
 17000.0,
 110000.0,
 17000.0,
 33000.0,
 70000.0,
 39000.0,
 59000.0,
 32000.0,
 41000.0,
 95000.0,
 65000.0,
 100000.0,
 53000.0,
 89000.0,
 30000.0,
 68000.0,
 160000.0,
 68000.0,
 85000.0,
 56000.0,
 26000.0,
 31000.0,
 40000.0,
 76000.0,
 72000.0,
 48000.0,
 28000.0,
 65000.0,
 36000.0,
 65000.0,
 35000.0,
 70000.0,
 29000.0,
 32000.0,
 120000.0,
 23000.0,
 59000.0,
 140000.0,
 71000.0,
 60000.0,
 125000.0,
 20000.0,
 16000.0,
 105000.0,
 20000.0,
 100000.0,
 46000.0,
 36000.0,
 79000.0,
 37000.0,
 34000.0,
 72000.0,
 41000.0,
 100000.0,
 41000.0,
 100000.0,
 59000.0,
 39000.0,
 110000.0,
 24000.0,
 64000.0,
 105000.0,
 82000.0,
 115000.0,
 65000.0,
 70000.0,
 28000.0,
 105000.0,
 54000.0,
 95000.0,
 52000.0,
 49000.0,
 100000.0,
 14000.0,
 40000.0,
 31000.0,
 90000.0,
 56000.0,
 43000.0,
 0.0,
 53000.0,
 48000.0,
 0.0,
 79000.0,
 83000.0,
 46000.0,
 30000.0,
 62000.0,
 69000.0,
 31000.0,
 95000.0,
 82000.0,
 105000.0,
 82000.0,
 95000.0,
 17000.0,
 74000.0,
 35000.0,
 79000.0,
 86000.0,
 24000.0,
 73000.0,
 35000.0,
 54000.0,
 14000.0,
 72000.0,
 83000.0,
 115000.0,
 39000.0,
 63000.0,
 65000.0,
 64000.0,
 21000.0,
 105000.0,
 19000.0,
 65000.0,
 32000.0,
 90000.0,
 81000.0,
 70000.0,
 60000.0,
 27000.0,
 60000.0,
 85000.0,
 39000.0,
 115000.0,
 53000.0,
 95000.0,
 68000.0,
 45000.0,
 23000.0,
 33000.0,
 100000.0,
 64000.0,
 58000.0,
 26000.0,
 1000.0,
 28000.0,
 66000.0,
 80000.0,
 12000.0,
 95000.0,
 26000.0,
 26000.0,
 2000.0,
 42000.0,
 87000.0,
 76000.0,
 2000.0,
 18000.0,
 25000.0,
 32000.0,
 26000.0,
 32000.0,
 54000.0,
 63000.0,
 13000.0,
 19000.0,
 66000.0,
 0.0,
 95000.0,
 40000.0,
 900000.0,
 1000.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 82000.0,
 86000.0,
 21000.0,
 51000.0,
 70000.0,
 69000.0,
 115000.0,
 18000.0,
 70000.0,
 28000.0,
 37000.0,
 140000.0,
 43000.0,
 43000.0,
 95000.0,
 23000.0,
 0.0,
 34000.0,
 59000.0,
 51000.0,
 26000.0,
 46000.0,
 25000.0,
 41000.0,
 125000.0,
 31000.0,
 43000.0,
 28000.0,
 90000.0,
 86000.0,
 45000.0,
 17000.0,
 46000.0,
 66000.0,
 100000.0,
 95000.0,
 95000.0,
 74000.0,
 17000.0,
 69000.0,
 74000.0,
 49000.0,
 56000.0,
 65000.0,
 29000.0,
 37000.0,
 57000.0,
 17000.0,
 165000.0,
 39000.0,
 37000.0,
 47000.0,
 68000.0,
 81000.0,
 100000.0,
 29000.0,
 47000.0,
 56000.0,
 83000.0,
 81000.0,
 31000.0,
 57000.0,
 135000.0,
 46000.0,
 33000.0,
 25000.0,
 78000.0,
 49000.0,
 84000.0,
 110000.0,
 41000.0,
 77000.0,
 32000.0,
 59000.0,
 30000.0,
 32000.0,
 53000.0,
 42000.0,
 35000.0,
 37000.0,
 28000.0,
 31000.0,
 40000.0,
 70000.0,
 29000.0,
 21000.0,
 53000.0,
 17000.0,
 86000.0,
 20000.0,
 38000.0,
 105000.0,
 18000.0,
 49000.0,
 32000.0,
 13000.0,
 61000.0,
 43000.0,
 63000.0,
 81000.0,
 46000.0,
 86000.0,
 68000.0,
 45000.0,
 48000.0,
 61000.0,
 48000.0,
 41000.0,
 41000.0,
 105000.0,
 82000.0,
 53000.0,
 38000.0,
 12000.0,
 33000.0,
 100000.0,
 81000.0,
 22000.0,
 81000.0,
 30000.0,
 40000.0,
 13000.0,
 95000.0,
 22000.0,
 22000.0,
 0.0,
 1000.0,
 0.0,
 0.0,
 0.0,
 42000.0,
 18000.0,
 48000.0,
 90000.0,
 38000.0,
 20000.0,
 21000.0,
 110000.0,
 32000.0,
 29000.0,
 29000.0,
 86000.0,
 26000.0,
 34000.0,
 86000.0,
 37000.0,
 18000.0,
 80000.0,
 36000.0,
 29000.0,
 31000.0,
 34000.0,
 110000.0,
 26000.0,
 28000.0,
 54000.0,
 58000.0,
 27000.0,
 26000.0,
 19000.0,
 23000.0,
 42000.0,
 27000.0,
 36000.0,
 32000.0,
 32000.0,
 39000.0,
 40000.0,
 23000.0,
 36000.0,
 19000.0,
 57000.0,
 41000.0,
 48000.0,
 49000.0,
 100000.0,
 35000.0,
 30000.0,
 21000.0,
 31000.0,
 42000.0,
 37000.0,
 77000.0,
 80000.0,
 30000.0,
 57000.0,
 32000.0,
 48000.0,
 13000.0,
 27000.0,
 77000.0,
 70000.0,
 80000.0,
 20000.0,
 32000.0,
 29000.0,
 47000.0,
 90000.0,
 20000.0,
 48000.0,
 0.0,
 50000.0,
 21000.0,
 52000.0,
 70000.0,
 20000.0,
 50000.0,
 1000.0,
 20000.0,
 83000.0,
 40000.0,
 81000.0,
 67000.0,
 37000.0,
 70000.0,
 65000.0,
 12000.0,
 24000.0,
 16000.0,
 23000.0,
 100000.0,
 31000.0,
 46000.0,
 57000.0,
 48000.0,
 14000.0,
 47000.0,
 78000.0,
 46000.0,
 1000.0,
 59000.0,
 59000.0,
 50000.0,
 63000.0,
 34000.0,
 48000.0,
 40000.0,
 40000.0,
 17000.0,
 33000.0,
 32000.0,
 42000.0,
 31000.0,
 63000.0,
 78000.0,
 24000.0,
 27000.0,
 12000.0,
 55000.0,
 28000.0,
 12000.0,
 32000.0,
 74000.0,
 44000.0,
 40000.0,
 89000.0,
 43000.0,
 30000.0,
 34000.0,
 76000.0,
 25000.0,
 32000.0,
 78000.0,
 24000.0,
 30000.0,
 24000.0,
 56000.0,
 34000.0,
 42000.0,
 29000.0,
 47000.0,
 0.0,
 15000.0,
 16000.0,
 70000.0,
 83000.0,
 70000.0,
 40000.0,
 89000.0,
 46000.0,
 26000.0,
 16000.0,
 50000.0,
 76000.0,
 2000.0,
 95000.0,
 85000.0,
 36000.0,
 110000.0,
 1000.0,
 22000.0,
 40000.0,
 43000.0,
 44000.0,
 76000.0,
 12000.0,
 48000.0,
 35000.0,
 12000.0,
 28000.0,
 15000.0,
 34000.0,
 30000.0,
 11000.0,
 2000.0,
 29000.0,
 15000.0,
 0.0,
 39000.0,
 105000.0,
 0.0,
 52000.0,
 0.0,
 17000.0,
 38000.0,
 8000.0,
 850000.0,
 15000.0,
 41000.0,
 28000.0,
 34000.0,
 26000.0,
 14000.0,
 20000.0,
 11000.0,
 34000.0,
 10000.0,
 33000.0,
 19000.0,
 74000.0,
 11000.0,
 25000.0,
 67000.0,
 33000.0,
 66000.0,
 25000.0,
 56000.0,
 59000.0,
 17000.0,
 77000.0,
 15000.0,
 43000.0,
 33000.0,
 33000.0,
 41000.0,
 19000.0,
 43000.0,
 30000.0,
 35000.0,
 45000.0,
 21000.0,
 31000.0,
 20000.0,
 37000.0,
 20000.0,
 11000.0,
 37000.0,
 37000.0,
 12000.0,
 37000.0,
 32000.0,
 72000.0,
 59000.0,
 1000.0,
 56000.0,
 36000.0,
 33000.0,
 16000.0,
 68000.0,
 46000.0,
 48000.0,
 65000.0,
 28000.0,
 52000.0,
 58000.0,
 28000.0,
 27000.0,
 30000.0,
 13000.0,
 19000.0,
 66000.0,
 37000.0,
 28000.0,
 16000.0,
 27000.0,
 51000.0,
 16000.0,
 57000.0,
 20000.0,
 77000.0,
 18000.0,
 59000.0,
 18000.0,
 47000.0,
 16000.0,
 70000.0,
 51000.0,
 66000.0,
 36000.0,
 16000.0,
 21000.0,
 77000.0,
 28000.0,
 35000.0,
 54000.0,
 48000.0,
 29000.0,
 12000.0,
 50000.0,
 42000.0,
 27000.0,
 27000.0,
 15000.0,
 69000.0,
 37000.0,
 41000.0,
 37000.0,
 69000.0,
 21000.0,
 69000.0,
 54000.0,
 69000.0,
 56000.0,
 17000.0,
 56000.0,
 35000.0,
 55000.0,
 16000.0,
 14000.0,
 36000.0,
 76000.0,
 58000.0,
 28000.0,
 30000.0,
 36000.0,
 88000.0,
 1000.0,
 60000.0,
 43000.0,
 64000.0,
 38000.0,
 36000.0,
 46000.0,
 28000.0,
 27000.0,
 43000.0,
 28000.0,
 74000.0,
 33000.0,
 30000.0,
 55000.0,
 57000.0,
 26000.0,
 56000.0,
 44000.0,
 58000.0,
 81000.0,
 57000.0,
 56000.0,
 13000.0,
 25000.0,
 43000.0,
 24000.0,
 24000.0,
 49000.0,
 12000.0,
 26000.0,
 33000.0,
 25000.0,
 51000.0,
 37000.0,
 38000.0,
 27000.0,
 41000.0,
 51000.0,
 20000.0,
 45000.0,
 50000.0,
 46000.0,
 16000.0,
 39000.0,
 25000.0,
 500000.0,
 50000.0,
 41000.0,
 19000.0,
 37000.0,
 62000.0,
 63000.0,
 72000.0,
 46000.0,
 50000.0,
 48000.0,
 43000.0,
 7000.0,
 56000.0,
 500000.0,
 24000.0,
 21000.0,
 44000.0,
 38000.0,
 44000.0,
 26000.0,
 28000.0,
 20000.0,
 60000.0,
 11000.0,
 23000.0,
 32000.0,
 16000.0,
 18000.0,
 47000.0,
 24000.0,
 20000.0,
 24000.0,
 26000.0,
 84000.0,
 18000.0,
 22000.0,
 18000.0,
 62000.0,
 20000.0,
 61000.0,
 35000.0,
 66000.0,
 8000.0,
 47000.0,
 26000.0,
 40000.0,
 33000.0,
 56000.0,
 32000.0,
 37000.0,
 48000.0,
 15000.0,
 31000.0,
 45000.0,
 16000.0,
 17000.0,
 24000.0,
 25000.0,
 26000.0,
 33000.0,
 18000.0,
 73000.0,
 52000.0,
 21000.0,
 52000.0,
 27000.0,
 38000.0,
 29000.0,
 7000.0,
 29000.0,
 37000.0,
 0.0,
 31000.0,
 21000.0,
 21000.0,
 11000.0,
 79000.0,
 17000.0,
 13000.0,
 19000.0,
 21000.0,
 52000.0,
 28000.0,
 41000.0,
 43000.0,
 59000.0,
 24000.0,
 41000.0,
 13000.0,
 51000.0,
 37000.0,
 45000.0,
 20000.0,
 15000.0,
 22000.0,
 57000.0,
 46000.0,
 17000.0,
 27000.0,
 79000.0,
 19000.0,
 34000.0,
 40000.0,
 21000.0,
 23000.0,
 11000.0,
 50000.0,
 19000.0,
 36000.0,
 20000.0,
 14000.0,
 40000.0,
 0.0,
 50000.0,
 31000.0,
 18000.0,
 68000.0,
 34000.0,
 55000.0,
 23000.0,
 25000.0,
 29000.0,
 6000.0,
 11000.0,
 27000.0,
 52000.0,
 21000.0,
 21000.0,
 9000.0,
 25000.0,
 77000.0,
 54000.0,
 13000.0,
 12000.0,
 14000.0,
 54000.0,
 ...]

In [47]:
dfNew['Wage(€)'] = waList
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,LM,LB,RWB,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€)
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,0,0,0,4,4,5,72.0,1.70,103500000.0,560000.0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,0,0,0,4,5,5,83.0,1.87,63000000.0,220000.0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,0,0,0,3,1,3,87.0,1.88,120000000.0,125000.0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,0,0,0,5,4,4,70.0,1.81,129000000.0,370000.0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,0,0,0,5,5,5,68.0,1.75,132000000.0,270000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,0,0,0,2,2,1,66.0,1.78,100000.0,1000.0
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,0,0,0,2,2,1,65.0,1.75,130000.0,500000.0
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,0,0,0,2,2,1,74.0,1.79,120000.0,500000.0
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,0,3,2,1,69.0,1.75,100000.0,2000.0
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,1,0,3,2,1,75.0,1.88,100000.0,1000.0

In [48]:
df_musket ['Release Clause'].unique() # checking the unique contents under Release Clause

array(['€138.4M', '€75.9M', '€159.4M', ..., '€59K', '€35K', '€64K'],
      dtype=object)

In [49]:
list(df_musket ['Release Clause'].unique())

['€138.4M',
 '€75.9M',
 '€159.4M',
 '€161M',
 '€166.5M',
 '€132M',
 '€144.3M',
 '€120.3M',
 '€203.1M',
 '€147.7M',
 '€145.3M',
 '€122M',
 '€119M',
 '€47.9M',
 '€108.7M',
 '€50.2M',
 '€98.1M',
 '€139.6M',
 '€96.9M',
 '€112.1M',
 '€122.5M',
 '€103M',
 '€140.2M',
 '€27.2M',
 '€85M',
 '€118.9M',
 '€112.8M',
 '€103.5M',
 '€132.1M',
 '€115.5M',
 '€102M',
 '€107.8M',
 '€124.4M',
 '€104.9M',
 '€99.8M',
 '€96.2M',
 '€50M',
 '€25.6M',
 '€77.9M',
 '€85.5M',
 '€56.1M',
 '€72.2M',
 '€64.6M',
 '€51.3M',
 '€82.5M',
 '€69.3M',
 '€59.9M',
 '€98.8M',
 '€96.3M',
 '€53.2M',
 '€43.1M',
 '€48.5M',
 '€47.3M',
 '€58.7M',
 '€65.6M',
 '€67.5M',
 '€84.7M',
 '€87M',
 '€95.8M',
 '€119.7M',
 '€91.6M',
 '€79M',
 '€111.3M',
 '€78.9M',
 '€81.9M',
 '€88.8M',
 '€86.9M',
 '€94.6M',
 '€69.4M',
 '€78M',
 '€97.8M',
 '€86.6M',
 '€107.3M',
 '€63.8M',
 '€54.2M',
 '€21.9M',
 '€66.2M',
 '€79.9M',
 '€52M',
 '€68.5M',
 '€56.4M',
 '€66.3M',
 '€44.2M',
 '€29.7M',
 '€40.8M',
 '€68.9M',
 '€24.7M',
 '€72.8M',
 '€57.8M',
 '€72.1M',
 '€76.5M',
 '€44.3M',
 '€71.9M',
 '€84.6M',
 '€61.2M',
 '€69.9M',
 '€73.7M',
 '€70.7M',
 '€64.7M',
 '€64.8M',
 '€81M',
 '€47.2M',
 '€68.1M',
 '€81.8M',
 '€69.1M',
 '€58.9M',
 '€38.5M',
 '€56.8M',
 '€62.2M',
 '€44.4M',
 '€42.5M',
 '€32.3M',
 '€59M',
 '€45.4M',
 '€65M',
 '€52.5M',
 '€50.3M',
 '€54.1M',
 '€17.6M',
 '€25.5M',
 '€46.6M',
 '€28.9M',
 '€40M',
 '€36.1M',
 '€37.1M',
 '€23.1M',
 '€62.1M',
 '€45.9M',
 '€49.4M',
 '€60.2M',
 '€46.2M',
 '€59.7M',
 '€65.2M',
 '€55.5M',
 '€31.4M',
 '€56.7M',
 '€66.4M',
 '€54M',
 '€45.3M',
 '€67.2M',
 '€53.9M',
 '€53.3M',
 '€49.1M',
 '€60.6M',
 '€54.6M',
 '€55M',
 '€55.3M',
 '€35.7M',
 '€32.9M',
 '€18.8M',
 '€44.1M',
 '€45.1M',
 '€41.5M',
 '€33.2M',
 '€38.9M',
 '€43.5M',
 '€29.8M',
 '€41.6M',
 '€39.9M',
 '€28.1M',
 '€46.3M',
 '€31.5M',
 '€35.2M',
 '€47.5M',
 '€28.4M',
 '€34M',
 '€32.8M',
 '€0',
 '€24M',
 '€13.3M',
 '€16.2M',
 '€33.8M',
 '€28.5M',
 '€30.8M',
 '€31.2M',
 '€45.7M',
 '€46.8M',
 '€43.7M',
 '€34.7M',
 '€57.3M',
 '€58.4M',
 '€40.2M',
 '€61.6M',
 '€49.2M',
 '€37.4M',
 '€57.6M',
 '€47M',
 '€42.4M',
 '€46.1M',
 '€59.5M',
 '€57M',
 '€29.4M',
 '€25.7M',
 '€47.4M',
 '€25.2M',
 '€36.5M',
 '€44M',
 '€29.6M',
 '€27M',
 '€42.8M',
 '€44.9M',
 '€45.2M',
 '€3.6M',
 '€35.5M',
 '€16.8M',
 '€32M',
 '€18.1M',
 '€13.6M',
 '€37.3M',
 '€61M',
 '€54.3M',
 '€72M',
 '€48.4M',
 '€47.7M',
 '€33.1M',
 '€33.3M',
 '€53.6M',
 '€35.1M',
 '€40.5M',
 '€51.5M',
 '€32.6M',
 '€40.4M',
 '€37.5M',
 '€43.3M',
 '€49.8M',
 '€48.9M',
 '€39.5M',
 '€30.6M',
 '€36.3M',
 '€46.4M',
 '€36.2M',
 '€35.4M',
 '€24.2M',
 '€30M',
 '€29.3M',
 '€31.6M',
 '€19.6M',
 '€26.8M',
 '€15.4M',
 '€22.1M',
 '€18.2M',
 '€7.2M',
 '€27.6M',
 '€24.5M',
 '€17.3M',
 '€22.3M',
 '€17M',
 '€20.9M',
 '€19M',
 '€9.1M',
 '€11.1M',
 '€21.4M',
 '€15.2M',
 '€73.6M',
 '€33M',
 '€28.6M',
 '€29.5M',
 '€39M',
 '€33.6M',
 '€35.6M',
 '€39.2M',
 '€31.1M',
 '€17.1M',
 '€33.7M',
 '€26.6M',
 '€35.9M',
 '€30.5M',
 '€46M',
 '€20.7M',
 '€42M',
 '€38.4M',
 '€31.9M',
 '€25.3M',
 '€34.6M',
 '€27.3M',
 '€11.2M',
 '€26.3M',
 '€30.2M',
 '€36.9M',
 '€24.6M',
 '€23.7M',
 '€27.5M',
 '€23.8M',
 '€31.8M',
 '€21.3M',
 '€18.9M',
 '€30.4M',
 '€7.7M',
 '€19.2M',
 '€14.4M',
 '€7M',
 '€15.3M',
 '€10.5M',
 '€16M',
 '€6M',
 '€18.7M',
 '€27.7M',
 '€20.4M',
 '€23M',
 '€7.3M',
 '€20M',
 '€10.4M',
 '€13.5M',
 '€13M',
 '€9.9M',
 '€25.9M',
 '€36.8M',
 '€34.9M',
 '€34.8M',
 '€37M',
 '€41.4M',
 '€24.9M',
 '€19.8M',
 '€22.8M',
 '€38M',
 '€35M',
 '€25M',
 '€30.1M',
 '€21M',
 '€22.2M',
 '€14.7M',
 '€21.7M',
 '€26.1M',
 '€27.9M',
 '€17.9M',
 '€22M',
 '€19.5M',
 '€15.8M',
 '€16.5M',
 '€26M',
 '€13.7M',
 '€20.2M',
 '€18.6M',
 '€12.8M',
 '€6.8M',
 '€11M',
 '€7.5M',
 '€11.6M',
 '€8.4M',
 '€8.8M',
 '€9.8M',
 '€9.4M',
 '€2.3M',
 '€15M',
 '€4.1M',
 '€2.2M',
 '€9.2M',
 '€12.4M',
 '€53.5M',
 '€34.5M',
 '€21.6M',
 '€28.3M',
 '€18M',
 '€32.2M',
 '€34.1M',
 '€29.9M',
 '€22.4M',
 '€26.4M',
 '€20.8M',
 '€11.7M',
 '€22.7M',
 '€26.7M',
 '€18.5M',
 '€20.1M',
 '€19.3M',
 '€21.8M',
 '€20.5M',
 '€17.8M',
 '€14.3M',
 '€8.6M',
 '€5.9M',
 '€8.3M',
 '€14.5M',
 '€8.5M',
 '€12M',
 '€11.9M',
 '€5.2M',
 '€8.2M',
 '€7.8M',
 '€12.1M',
 '€4M',
 '€12.6M',
 '€14.8M',
 '€9M',
 '€11.8M',
 '€2.4M',
 '€13.2M',
 '€21.2M',
 '€15.1M',
 '€19.7M',
 '€16.6M',
 '€4.7M',
 '€28.8M',
 '€23.9M',
 '€26.5M',
 '€6.3M',
 '€11.4M',
 '€16.9M',
 '€10.3M',
 '€14M',
 '€26.2M',
 '€10.2M',
 '€3.4M',
 '€43M',
 '€6.6M',
 '€5.5M',
 '€7.1M',
 '€13.4M',
 '€18.4M',
 '€10.8M',
 '€1.9M',
 '€14.1M',
 '€9.6M',
 '€16.4M',
 '€11.3M',
 '€7.4M',
 '€16.1M',
 '€3.3M',
 '€13.1M',
 '€14.2M',
 '€10.1M',
 '€1.2M',
 '€40.1M',
 '€4.2M',
 '€3.2M',
 '€6.7M',
 '€5M',
 '€10.9M',
 '€4.4M',
 '€2.7M',
 '€4.8M',
 '€3M',
 '€15.9M',
 '€9.3M',
 '€8.9M',
 '€2.5M',
 '€3.1M',
 '€6.5M',
 '€6.1M',
 '€16.3M',
 '€12.2M',
 '€15.6M',
 '€17.4M',
 '€5.8M',
 '€5.6M',
 '€10M',
 '€5.3M',
 '€3.9M',
 '€6.2M',
 '€13.8M',
 '€4.6M',
 '€3.8M',
 '€6.4M',
 '€5.7M',
 '€4.5M',
 '€2.8M',
 '€8.1M',
 '€2.9M',
 '€8.7M',
 '€1.1M',
 '€7.6M',
 '€3.5M',
 '€8M',
 '€11.5M',
 '€33.4M',
 '€13.9M',
 '€30.3M',
 '€22.5M',
 '€4.3M',
 '€9.5M',
 '€7.9M',
 '€10.7M',
 '€1.3M',
 '€5.1M',
 '€5.4M',
 '€12.5M',
 '€9.7M',
 '€4.9M',
 '€978K',
 '€2M',
 '€10.6M',
 '€1M',
 '€949K',
 '€2.1M',
 '€1.8M',
 '€12.3M',
 '€12.7M',
 '€2.6M',
 '€760K',
 '€6.9M',
 '€3.7M',
 '€800K',
 '€600K',
 '€23.6M',
 '€560K',
 '€1.7M',
 '€1.5M',
 '€19.1M',
 '€880K',
 '€1.6M',
 '€788K',
 '€998K',
 '€1.4M',
 '€945K',
 '€585K',
 '€455K',
 '€553K',
 '€17.7M',
 '€683K',
 '€906K',
 '€324K',
 '€713K',
 '€878K',
 '€348K',
 '€750K',
 '€820K',
 '€975K',
 '€432K',
 '€680K',
 '€616K',
 '€360K',
 '€808K',
 '€640K',
 '€543K',
 '€926K',
 '€938K',
 '€438K',
 '€508K',
 '€825K',
 '€834K',
 '€252K',
 '€891K',
 '€689K',
 '€844K',
 '€405K',
 '€719K',
 '€306K',
 '€290K',
 '€342K',
 '€480K',
 '€594K',
 '€358K',
 '€910K',
 '€210K',
 '€378K',
 '€688K',
 '€618K',
 '€149K',
 '€775K',
 '€368K',
 '€471K',
 '€641K',
 '€284K',
 '€426K',
 '€709K',
 '€900K',
 '€504K',
 '€187K',
 '€420K',
 '€660K',
 '€563K',
 '€725K',
 '€979K',
 '€968K',
 '€578K',
 '€540K',
 '€638K',
 '€357K',
 '€943K',
 '€875K',
 '€806K',
 '€385K',
 '€950K',
 '€675K',
 '€798K',
 '€840K',
 '€452K',
 '€439K',
 '€465K',
 '€544K',
 '€969K',
 '€879K',
 '€665K',
 '€409K',
 '€813K',
 '€525K',
 '€911K',
 '€736K',
 '€855K',
 '€625K',
 '€399K',
 '€488K',
 '€387K',
 '€305K',
 '€520K',
 '€180K',
 '€500K',
 '€744K',
 '€516K',
 '€276K',
 '€853K',
 '€650K',
 '€776K',
 '€870K',
 '€312K',
 '€765K',
 '€580K',
 '€860K',
 '€122K',
 '€531K',
 '€805K',
 '€153K',
 '€208K',
 '€920K',
 '€131K',
 '€406K',
 '€418K',
 '€174K',
 '€715K',
 '€574K',
 '€963K',
 '€656K',
 '€344K',
 '€158K',
 '€330K',
 '€243K',
 '€700K',
 '€396K',
 '€960K',
 '€990K',
 '€200K',
 '€300K',
 '€569K',
 '€375K',
 '€591K',
 '€748K',
 '€903K',
 '€863K',
 '€113K',
 '€468K',
 '€962K',
 '€810K',
 '€323K',
 '€753K',
 '€240K',
 '€263K',
 '€648K',
 '€241K',
 '€216K',
 '€961K',
 '€761K',
 '€613K',
 '€930K',
 '€391K',
 '€831K',
 '€814K',
 '€781K',
 '€469K',
 '€653K',
 '€301K',
 '€699K',
 '€743K',
 '€894K',
 '€120K',
 '€991K',
 '€620K',
 '€221K',
 '€495K',
 '€780K',
 '€163K',
 '€116K',
 '€345K',
 '€203K',
 '€280K',
 '€861K',
 '€481K',
 '€218K',
 '€915K',
 '€601K',
 '€919K',
 '€506K',
 '€334K',
 '€845K',
 '€319K',
 '€523K',
 '€729K',
 '€570K',
 '€109K',
 '€454K',
 '€250K',
 '€380K',
 '€914K',
 '€935K',
 '€408K',
 '€196K',
 '€762K',
 '€696K',
 '€770K',
 '€435K',
 '€994K',
 '€338K',
 '€701K',
 '€270K',
 '€255K',
 '€953K',
 '€959K',
 '€828K',
 '€893K',
 '€976K',
 '€264K',
 '€784K',
 '€297K',
 '€160K',
 '€444K',
 '€928K',
 '€234K',
 '€659K',
 '€176K',
 '€866K',
 '€984K',
 '€581K',
 '€189K',
 '€819K',
 '€720K',
 '€877K',
 '€801K',
 '€225K',
 '€645K',
 '€371K',
 '€786K',
 '€313K',
 '€908K',
 '€298K',
 '€288K',
 '€440K',
 '€213K',
 '€363K',
 '€261K',
 '€971K',
 '€138K',
 '€889K',
 '€350K',
 '€677K',
 '€536K',
 '€698K',
 '€958K',
 '€827K',
 '€108K',
 '€310K',
 '€73K',
 '€63K',
 '€238K',
 '€763K',
 '€175K',
 '€388K',
 '€986K',
 '€838K',
 '€473K',
 '€795K',
 '€839K',
 '€921K',
 '€932K',
 '€867K',
 '€257K',
 '€352K',
 '€155K',
 '€430K',
 '€996K',
 '€333K',
 '€663K',
 '€596K',
 '€774K',
 '€248K',
 '€258K',
 '€150K',
 '€538K',
 '€403K',
 '€731K',
 '€608K',
 '€70K',
 '€735K',
 '€934K',
 '€232K',
 '€304K',
 '€686K',
 '€497K',
 '€275K',
 '€619K',
 '€913K',
 '€666K',
 '€68K',
 '€988K',
 '€61K',
 '€821K',
 '€830K',
 '€799K',
 '€172K',
 '€194K',
 '€530K',
 '€629K',
 '€888K',
 '€630K',
 '€724K',
 '€606K',
 '€245K',
 '€584K',
 '€125K',
 '€259K',
 '€534K',
 '€450K',
 '€104K',
 '€572K',
 '€843K',
 '€372K',
 '€56K',
 '€555K',
 '€550K',
 '€890K',
 '€850K',
 '€811K',
 '€311K',
 '€946K',
 '€97K',
 '€490K',
 '€100K',
 '€140K',
 '€956K',
 '€135K',
 '€413K',
 '€77K',
 '€848K',
 '€754K',
 '€272K',
 '€772K',
 '€464K',
 '€326K',
 '€499K',
 '€188K',
 '€778K',
 '€398K',
 '€710K',
 '€669K',
 '€228K',
 '€98K',
 '€684K',
 '€940K',
 '€730K',
 '€341K',
 '€674K',
 '€366K',
 '€610K',
 '€528K',
 '€463K',
 '€193K',
 '€428K',
 '€429K',
 '€145K',
 '€639K',
 '€431K',
 '€496K',
 '€202K',
 '€723K',
 '€314K',
 '€924K',
 '€712K',
 '€548K',
 '€315K',
 '€593K',
 '€586K',
 '€46K',
 '€612K',
 '€237K',
 '€423K',
 '€512K',
 '€87K',
 '€510K',
 '€694K',
 '€215K',
 '€882K',
 '€151K',
 '€54K',
 '€740K',
 '€44K',
 '€779K',
 '€690K',
 '€247K',
 '€722K',
 '€364K',
 '€967K',
 '€533K',
 '€88K',
 '€123K',
 '€111K',
 '€705K',
 '€829K',
 '€231K',
 '€595K',
 '€419K',
 '€621K',
 '€604K',
 '€318K',
 '€331K',
 '€999K',
 '€647K',
 '€726K',
 '€668K',
 '€129K',
 '€503K',
 '€816K',
 '€561K',
 '€381K',
 '€295K',
 '€458K',
 '€518K',
 '€502K',
 '€796K',
 '€881K',
 '€609K',
 '€443K',
 '€217K',
 '€670K',
 '€551K',
 '€53K',
 '€556K',
 '€433K',
 '€356K',
 '€169K',
 '€124K',
 '€279K',
 '€38K',
 '€233K',
 '€833K',
 '€764K',
 '€394K',
 '€623K',
 '€424K',
 '€392K',
 '€634K',
 '€402K',
 '€790K',
 '€362K',
 '€475K',
 '€456K',
 '€474K',
 '€347K',
 '€823K',
 '€39K',
 '€369K',
 '€195K',
 '€519K',
 '€445K',
 '€95K',
 '€447K',
 '€75K',
 '€58K',
 '€390K',
 '€171K',
 '€31K',
 '€577K',
 '€498K',
 '€436K',
 '€182K',
 '€571K',
 '€588K',
 '€374K',
 '€130K',
 '€365K',
 '€162K',
 '€494K',
 '€797K',
 '€278K',
 '€646K',
 '€351K',
 '€281K',
 '€325K',
 '€292K',
 '€605K',
 '€909K',
 '€947K',
 '€410K',
 '€328K',
 '€598K',
 '€289K',
 '€872K',
 '€970K',
 '€741K',
 '€332K',
 '€576K',
 '€615K',
 '€397K',
 '€320K',
 '€425K',
 '€954K',
 '€302K',
 '€401K',
 '€244K',
 '€980K',
 '€509K',
 '€293K',
 '€564K',
 ...]

In [50]:
rcList = [] 
for val in df_musket['Release Clause'].values:
    val =str(val)
    if 'K' in val:
        val=float(val[1:-1])*1000 
        rcList.append(val)
    elif 'M' in val:
        val = float(val[1:-1])*1000000
        rcList.append(val)
    else:
        rcList.append(float(0))
rcList

[138400000.0,
 75900000.0,
 159400000.0,
 161000000.0,
 166500000.0,
 132000000.0,
 144300000.0,
 120300000.0,
 203100000.0,
 147700000.0,
 145300000.0,
 144300000.0,
 122000000.0,
 119000000.0,
 47900000.0,
 108700000.0,
 50200000.0,
 98100000.0,
 139600000.0,
 96900000.0,
 112100000.0,
 122500000.0,
 103000000.0,
 140200000.0,
 27200000.0,
 85000000.0,
 118900000.0,
 112800000.0,
 103500000.0,
 132100000.0,
 115500000.0,
 115500000.0,
 102000000.0,
 107800000.0,
 124400000.0,
 104900000.0,
 99800000.0,
 96200000.0,
 50000000.0,
 25600000.0,
 77900000.0,
 85500000.0,
 56100000.0,
 72200000.0,
 50200000.0,
 64599999.99999999,
 51300000.0,
 82500000.0,
 69300000.0,
 59900000.0,
 77900000.0,
 98800000.0,
 96300000.0,
 98800000.0,
 53200000.0,
 43100000.0,
 56100000.0,
 48500000.0,
 47300000.0,
 58700000.0,
 65599999.99999999,
 67500000.0,
 84700000.0,
 87000000.0,
 95800000.0,
 119700000.0,
 91600000.0,
 79000000.0,
 111300000.0,
 78900000.0,
 81900000.0,
 88800000.0,
 86900000.0,
 94600000.0,
 84700000.0,
 69400000.0,
 78000000.0,
 97800000.0,
 69300000.0,
 86600000.0,
 107300000.0,
 63800000.0,
 54200000.0,
 21900000.0,
 77900000.0,
 66200000.0,
 79900000.0,
 52000000.0,
 68500000.0,
 56400000.0,
 66300000.0,
 44200000.0,
 29700000.0,
 40800000.0,
 68900000.0,
 24700000.0,
 68500000.0,
 72800000.0,
 57800000.0,
 72100000.0,
 76500000.0,
 44300000.0,
 71900000.0,
 97800000.0,
 84600000.0,
 85500000.0,
 61200000.0,
 69900000.0,
 73700000.0,
 70700000.0,
 64700000.0,
 64800000.0,
 81000000.0,
 47200000.0,
 68100000.0,
 81800000.0,
 69100000.0,
 58900000.0,
 38500000.0,
 58900000.0,
 56800000.0,
 62200000.0,
 44400000.0,
 42500000.0,
 32299999.999999996,
 59000000.0,
 64599999.99999999,
 45400000.0,
 47200000.0,
 65000000.0,
 52500000.0,
 50300000.0,
 54100000.0,
 17600000.0,
 25500000.0,
 46600000.0,
 28900000.0,
 32299999.999999996,
 40000000.0,
 36100000.0,
 37100000.0,
 23100000.0,
 62100000.0,
 64800000.0,
 79900000.0,
 45900000.0,
 49400000.0,
 60200000.0,
 54100000.0,
 66300000.0,
 46200000.0,
 68100000.0,
 59700000.0,
 81000000.0,
 65200000.0,
 55500000.0,
 31400000.0,
 58700000.0,
 81000000.0,
 56700000.0,
 66400000.00000001,
 54000000.0,
 51300000.0,
 45300000.0,
 45900000.0,
 66300000.0,
 67200000.0,
 53900000.0,
 53300000.0,
 49100000.0,
 46600000.0,
 60600000.0,
 48500000.0,
 54600000.0,
 55000000.0,
 44200000.0,
 62200000.0,
 55300000.0,
 35700000.0,
 32900000.0,
 18800000.0,
 44100000.0,
 45100000.0,
 41500000.0,
 33200000.000000004,
 49100000.0,
 38900000.0,
 49400000.0,
 51300000.0,
 43500000.0,
 29800000.0,
 56700000.0,
 53300000.0,
 41600000.0,
 39900000.0,
 28100000.0,
 46300000.0,
 31500000.0,
 35200000.0,
 43100000.0,
 47500000.0,
 25500000.0,
 28400000.0,
 34000000.0,
 32799999.999999996,
 0.0,
 33200000.000000004,
 24000000.0,
 13300000.0,
 16200000.0,
 33800000.0,
 28500000.0,
 30800000.0,
 31200000.0,
 45700000.0,
 46800000.0,
 43700000.0,
 34700000.0,
 37100000.0,
 57300000.0,
 58400000.0,
 55300000.0,
 46200000.0,
 57300000.0,
 40200000.0,
 40800000.0,
 61600000.0,
 49200000.0,
 57800000.0,
 37400000.0,
 31500000.0,
 42500000.0,
 57600000.0,
 41500000.0,
 47000000.0,
 40800000.0,
 42400000.0,
 32299999.999999996,
 46100000.0,
 59500000.0,
 42400000.0,
 57000000.0,
 29400000.0,
 25700000.0,
 47400000.0,
 25200000.0,
 36500000.0,
 44000000.0,
 0.0,
 29600000.0,
 30800000.0,
 34700000.0,
 27000000.0,
 42800000.0,
 0.0,
 44900000.0,
 45700000.0,
 45200000.0,
 35700000.0,
 25500000.0,
 29400000.0,
 27200000.0,
 3600000.0,
 35500000.0,
 16800000.0,
 37100000.0,
 25700000.0,
 35700000.0,
 37100000.0,
 32000000.0,
 18100000.0,
 13600000.0,
 27200000.0,
 33200000.000000004,
 54600000.0,
 37300000.0,
 61000000.0,
 45100000.0,
 47500000.0,
 54300000.0,
 72000000.0,
 48400000.0,
 47700000.0,
 33100000.0,
 41600000.0,
 33299999.999999996,
 53600000.0,
 33299999.999999996,
 35100000.0,
 0.0,
 35200000.0,
 28500000.0,
 0.0,
 40500000.0,
 51500000.0,
 42500000.0,
 32600000.0,
 32299999.999999996,
 40400000.0,
 31500000.0,
 37500000.0,
 45400000.0,
 0.0,
 45400000.0,
 43300000.0,
 49800000.0,
 0.0,
 48900000.0,
 39500000.0,
 38500000.0,
 23100000.0,
 39900000.0,
 30600000.0,
 48900000.0,
 36300000.0,
 46400000.0,
 36200000.0,
 37500000.0,
 56400000.0,
 25500000.0,
 35400000.0,
 27200000.0,
 24200000.0,
 33299999.999999996,
 30000000.0,
 28900000.0,
 29300000.0,
 36500000.0,
 39900000.0,
 31600000.0,
 36100000.0,
 19600000.0,
 0.0,
 26800000.0,
 39900000.0,
 37500000.0,
 0.0,
 28500000.0,
 36100000.0,
 45700000.0,
 25200000.0,
 24200000.0,
 33299999.999999996,
 25500000.0,
 43500000.0,
 15400000.0,
 29400000.0,
 27200000.0,
 22100000.0,
 18200000.0,
 7200000.0,
 27600000.0,
 25200000.0,
 24500000.0,
 29400000.0,
 25200000.0,
 17300000.0,
 22300000.0,
 29400000.0,
 17000000.0,
 20900000.0,
 19000000.0,
 9100000.0,
 16200000.0,
 11100000.0,
 33800000.0,
 7200000.0,
 21400000.0,
 15200000.0,
 0.0,
 73600000.0,
 43500000.0,
 33000000.0,
 49200000.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 43100000.0,
 28600000.0,
 29500000.0,
 39000000.0,
 33600000.0,
 35600000.0,
 42800000.0,
 35700000.0,
 44100000.0,
 39200000.0,
 31100000.0,
 42500000.0,
 17100000.0,
 39000000.0,
 33700000.0,
 31400000.0,
 0.0,
 26600000.0,
 35500000.0,
 35100000.0,
 35900000.0,
 35200000.0,
 30500000.0,
 22100000.0,
 0.0,
 46000000.0,
 43100000.0,
 20700000.0,
 42000000.0,
 39000000.0,
 36500000.0,
 38400000.0,
 32000000.0,
 33700000.0,
 33600000.0,
 0.0,
 22100000.0,
 31900000.0,
 25300000.0,
 32000000.0,
 34600000.0,
 31100000.0,
 36500000.0,
 37500000.0,
 27300000.0,
 40200000.0,
 32799999.999999996,
 11200000.0,
 29700000.0,
 31100000.0,
 26300000.0,
 32600000.0,
 30200000.0,
 31100000.0,
 0.0,
 30500000.0,
 36900000.0,
 25600000.0,
 33700000.0,
 29600000.0,
 35900000.0,
 25700000.0,
 24600000.0,
 23700000.0,
 27500000.0,
 0.0,
 28500000.0,
 25700000.0,
 23800000.0,
 31800000.0,
 21300000.0,
 34600000.0,
 18900000.0,
 29600000.0,
 24000000.0,
 25200000.0,
 25700000.0,
 23800000.0,
 0.0,
 25200000.0,
 27300000.0,
 24200000.0,
 32600000.0,
 30400000.0,
 26300000.0,
 7700000.0,
 19200000.0,
 24000000.0,
 24700000.0,
 14400000.0,
 31500000.0,
 20900000.0,
 7000000.0,
 15300000.0,
 10500000.0,
 16000000.0,
 6000000.0,
 18700000.0,
 27700000.0,
 13300000.0,
 26600000.0,
 15200000.0,
 18100000.0,
 22100000.0,
 20400000.0,
 23000000.0,
 15200000.0,
 29400000.0,
 7700000.0,
 22100000.0,
 32600000.0,
 13600000.0,
 22100000.0,
 7300000.0,
 20000000.0,
 28500000.0,
 15200000.0,
 17100000.0,
 18100000.0,
 24200000.0,
 10400000.0,
 13500000.0,
 13000000.0,
 10500000.0,
 9900000.0,
 0.0,
 16800000.0,
 0.0,
 0.0,
 0.0,
 30600000.0,
 0.0,
 35200000.0,
 47300000.0,
 30400000.0,
 25900000.0,
 36800000.0,
 34900000.0,
 32600000.0,
 32600000.0,
 35700000.0,
 40000000.0,
 34800000.0,
 33600000.0,
 30600000.0,
 33299999.999999996,
 21400000.0,
 36800000.0,
 36800000.0,
 30600000.0,
 34700000.0,
 37000000.0,
 29800000.0,
 33700000.0,
 41400000.0,
 36100000.0,
 24900000.0,
 27600000.0,
 18100000.0,
 23800000.0,
 23800000.0,
 19800000.0,
 22800000.0,
 38000000.0,
 35000000.0,
 30200000.0,
 32600000.0,
 34800000.0,
 37000000.0,
 24200000.0,
 25000000.0,
 27700000.0,
 32600000.0,
 31600000.0,
 20900000.0,
 27700000.0,
 32600000.0,
 33700000.0,
 0.0,
 31500000.0,
 16200000.0,
 24900000.0,
 0.0,
 36800000.0,
 37000000.0,
 28600000.0,
 23100000.0,
 26600000.0,
 30100000.0,
 27200000.0,
 27700000.0,
 30600000.0,
 36800000.0,
 30100000.0,
 21000000.0,
 24200000.0,
 22200000.0,
 25700000.0,
 11200000.0,
 22800000.0,
 0.0,
 30200000.0,
 14700000.0,
 21300000.0,
 29600000.0,
 31100000.0,
 26600000.0,
 22800000.0,
 19200000.0,
 28600000.0,
 21300000.0,
 0.0,
 31500000.0,
 28400000.0,
 21700000.0,
 21300000.0,
 18800000.0,
 20900000.0,
 16000000.0,
 26100000.0,
 27900000.0,
 23100000.0,
 22100000.0,
 21300000.0,
 23000000.0,
 22800000.0,
 29600000.0,
 29800000.0,
 24000000.0,
 22100000.0,
 20900000.0,
 31600000.0,
 23100000.0,
 17900000.0,
 22000000.0,
 21300000.0,
 19000000.0,
 19500000.0,
 30100000.0,
 15800000.0,
 19200000.0,
 26600000.0,
 25200000.0,
 17900000.0,
 27000000.0,
 29400000.0,
 27200000.0,
 15800000.0,
 24600000.0,
 22800000.0,
 16500000.0,
 24200000.0,
 18200000.0,
 22100000.0,
 30500000.0,
 27900000.0,
 26000000.0,
 27200000.0,
 16800000.0,
 25700000.0,
 13700000.0,
 17900000.0,
 21300000.0,
 20200000.0,
 21000000.0,
 21000000.0,
 19000000.0,
 16800000.0,
 17000000.0,
 18600000.0,
 18100000.0,
 0.0,
 12800000.0,
 12800000.0,
 22800000.0,
 22800000.0,
 20900000.0,
 6800000.0,
 21900000.0,
 12800000.0,
 21000000.0,
 11000000.0,
 7500000.0,
 17100000.0,
 22100000.0,
 15200000.0,
 20000000.0,
 16800000.0,
 19000000.0,
 11600000.0,
 8400000.0,
 8800000.0,
 16800000.0,
 25700000.0,
 15200000.0,
 9800000.0,
 13600000.0,
 9400000.0,
 2300000.0,
 15000000.0,
 4099999.9999999995,
 9400000.0,
 2200000.0,
 8800000.0,
 9200000.0,
 12400000.0,
 27200000.0,
 0.0,
 17100000.0,
 53500000.0,
 0.0,
 32600000.0,
 0.0,
 34500000.0,
 29500000.0,
 29700000.0,
 22800000.0,
 21600000.0,
 32600000.0,
 28300000.0,
 18000000.0,
 32200000.000000004,
 34100000.0,
 29900000.0,
 22100000.0,
 30400000.0,
 23800000.0,
 29500000.0,
 22400000.0,
 24000000.0,
 26400000.0,
 0.0,
 26800000.0,
 22800000.0,
 29400000.0,
 26100000.0,
 27600000.0,
 27300000.0,
 24000000.0,
 31500000.0,
 20800000.0,
 23700000.0,
 30500000.0,
 20700000.0,
 20700000.0,
 32000000.0,
 15300000.0,
 20700000.0,
 20700000.0,
 20000000.0,
 19000000.0,
 18000000.0,
 19000000.0,
 11700000.0,
 19000000.0,
 26100000.0,
 22700000.0,
 27600000.0,
 28600000.0,
 21700000.0,
 24000000.0,
 26700000.0,
 28400000.0,
 27300000.0,
 23100000.0,
 23800000.0,
 27700000.0,
 23100000.0,
 22200000.0,
 20700000.0,
 24900000.0,
 20900000.0,
 18500000.0,
 21300000.0,
 0.0,
 18900000.0,
 24700000.0,
 24700000.0,
 15800000.0,
 20700000.0,
 22700000.0,
 0.0,
 13600000.0,
 24900000.0,
 0.0,
 20100000.0,
 17000000.0,
 24000000.0,
 13000000.0,
 0.0,
 0.0,
 24700000.0,
 10500000.0,
 24700000.0,
 20000000.0,
 0.0,
 19300000.0,
 24700000.0,
 23700000.0,
 21800000.0,
 15800000.0,
 20400000.0,
 19800000.0,
 18900000.0,
 20400000.0,
 17900000.0,
 23100000.0,
 20500000.0,
 21300000.0,
 24700000.0,
 30500000.0,
 26600000.0,
 3600000.0,
 20700000.0,
 15300000.0,
 10500000.0,
 15200000.0,
 16200000.0,
 26100000.0,
 20700000.0,
 22200000.0,
 20700000.0,
 13300000.0,
 24900000.0,
 25700000.0,
 22100000.0,
 17100000.0,
 17100000.0,
 17000000.0,
 21000000.0,
 20900000.0,
 15200000.0,
 26100000.0,
 16800000.0,
 21700000.0,
 0.0,
 18700000.0,
 0.0,
 17800000.0,
 19000000.0,
 12800000.0,
 21000000.0,
 17100000.0,
 15400000.0,
 22100000.0,
 19000000.0,
 18600000.0,
 23700000.0,
 20800000.0,
 7700000.0,
 17900000.0,
 18600000.0,
 13000000.0,
 20700000.0,
 17000000.0,
 14300000.0,
 0.0,
 15300000.0,
 23700000.0,
 18900000.0,
 17900000.0,
 8600000.0,
 15800000.0,
 23100000.0,
 25700000.0,
 16500000.0,
 5900000.0,
 16200000.0,
 16200000.0,
 15200000.0,
 7200000.0,
 11700000.0,
 8300000.000000001,
 13600000.0,
 8300000.000000001,
 6800000.0,
 11100000.0,
 17900000.0,
 19000000.0,
 21000000.0,
 11100000.0,
 17900000.0,
 13700000.0,
 14500000.0,
 15300000.0,
 13700000.0,
 16200000.0,
 20000000.0,
 16800000.0,
 20700000.0,
 13600000.0,
 16200000.0,
 20000000.0,
 23700000.0,
 10400000.0,
 8500000.0,
 3600000.0,
 12000000.0,
 11900000.0,
 12800000.0,
 14500000.0,
 15300000.0,
 13700000.0,
 8400000.0,
 14400000.0,
 16200000.0,
 13500000.0,
 0.0,
 7200000.0,
 5200000.0,
 8500000.0,
 8199999.999999999,
 7800000.0,
 12100000.0,
 4000000.0,
 12600000.0,
 19000000.0,
 5200000.0,
 15300000.0,
 12600000.0,
 23700000.0,
 15300000.0,
 14800000.0,
 19800000.0,
 24600000.0,
 21300000.0,
 20400000.0,
 11700000.0,
 13300000.0,
 20400000.0,
 23100000.0,
 18800000.0,
 12400000.0,
 21300000.0,
 28600000.0,
 8199999.999999999,
 21300000.0,
 19000000.0,
 9000000.0,
 20800000.0,
 19000000.0,
 7300000.0,
 13600000.0,
 11800000.0,
 11100000.0,
 0.0,
 9900000.0,
 16200000.0,
 15200000.0,
 16200000.0,
 13700000.0,
 2400000.0,
 0.0,
 18800000.0,
 0.0,
 17900000.0,
 13200000.0,
 14300000.0,
 25300000.0,
 21200000.0,
 9100000.0,
 18700000.0,
 13200000.0,
 9400000.0,
 23700000.0,
 18900000.0,
 22800000.0,
 17800000.0,
 17100000.0,
 17600000.0,
 23700000.0,
 23000000.0,
 16200000.0,
 10500000.0,
 14500000.0,
 14300000.0,
 7700000.0,
 11700000.0,
 16200000.0,
 16200000.0,
 17000000.0,
 12800000.0,
 23100000.0,
 24700000.0,
 14300000.0,
 16200000.0,
 15000000.0,
 22800000.0,
 0.0,
 14300000.0,
 17100000.0,
 13500000.0,
 22800000.0,
 17600000.0,
 10500000.0,
 0.0,
 15100000.0,
 12600000.0,
 17000000.0,
 24200000.0,
 15300000.0,
 12400000.0,
 15800000.0,
 8800000.0,
 19700000.0,
 8600000.0,
 16600000.000000002,
 15800000.0,
 0.0,
 0.0,
 14700000.0,
 4700000.0,
 18800000.0,
 13300000.0,
 26800000.0,
 13000000.0,
 9400000.0,
 10400000.0,
 16200000.0,
 ...]

In [51]:
dfNew['Release Clause(€)'] = rcList
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,LB,RWB,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€)
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,0,0,4,4,5,72.0,1.70,103500000.0,560000.0,138400000.0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,0,0,4,5,5,83.0,1.87,63000000.0,220000.0,75900000.0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,0,0,3,1,3,87.0,1.88,120000000.0,125000.0,159400000.0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,0,0,5,4,4,70.0,1.81,129000000.0,370000.0,161000000.0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,0,0,5,5,5,68.0,1.75,132000000.0,270000.0,166500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,0,0,2,2,1,66.0,1.78,100000.0,1000.0,70000.0
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,0,0,2,2,1,65.0,1.75,130000.0,500000.0,165000.0
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,0,0,2,2,1,74.0,1.79,120000.0,500000.0,131000.0
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,0,3,2,1,69.0,1.75,100000.0,2000.0,88000.0
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,1,0,3,2,1,75.0,1.88,100000.0,1000.0,79000.0

Task 6 - Inspect the HITS column and ensure its float

In [52]:
df_musket.Hits.unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79', '49',
       '270', '511', '80', '128', '115', '156', '204', '143', '140',
       '152', '220', '134', '225', '94', '74', '135', '142', '50', '77',
       '40', '107', '193', '179', '34', '64', '453', '57', '81', '28',
       '78', '133', '43', '425', '88', '42', '36', '233', '376', '210',
       '444', '100', '263', '98', '29', '160', '39', '257', '6', '310',
       '138', '62', '293', '285', '362', '66', '69', '58', '21', '20',
       '131', '38', '406', '68', '108', '110', '93', '512', '443', '306',
       '352', '422', '585', '346', '178', '841', '76', '394', '72', '172',
       '44', '407', '230', '367', '295', '157', '243', '56', '111', '326',
       '679', '18', '92', '59', '25', '184', '53', '12', '90', '55', '73',
       '11', '566', '180', '83', '262', '17', '26', '31', '280', '359',
       '213', '297', '387', '480', '381', '677', '486', '8', '244', '129',
       '388', '275', '319', '2K', '52', '91', '421', '153', '27', '41',
       '222', '35', '102', '23', '30', '33', '146', '13', '19', '14',
       '106', '276', '568', '353', '47', '478', '249', '254', '369',
       '219', '565', '237', '227', '434', '375', '162', '605', '654', '3',
       '7', '9', '104', '114', '186', '446', '756', '22', '139', '500',
       '67', '147', '149', '16', '82', '54', '37', '15', '1.3K', '3K',
       '952', '5', '749', '541', '330', '393', '517', '770', '409', '170',
       '125', '283', '342', '363', '580', '105', '217', '24', '141', '10',
       '427', '158', '426', '4', '666', '181', '324', '979', '1.4K',
       '302', '751', '298', '411', '944', '2', '947', '292', '349', '621',
       '1', '2.8K', '338', '287', '261', '218', '1.8K', '240', '279',
       '229', '188', '315', '664', '613', '190', '706', '127', '462',
       '386', '695', '491', '167', '281', '250', '307', '95', '231',
       '174', '680', '633', '221', '348', '602', '183', '653', '195',
       '164', '151', '258', '8.4K', '343', '419', '655', '136', '399',
       '531', '357', '228', '385', '312', '340', '238', '487', '355',
       '499', '4.3K', '296', '515', '943', '1.2K', '903', '335', '191',
       '594', '267', '617', '516', '504', '331', '652', '410', '550',
       '473', '442', '344', '208', '1K', '2.5K', '273', '485', '826',
       '192', '405', '941', '477', '644', '303', '417', '6K', nan, 1.0,
       5.0, 9.0, 2.0, 21.0, 7.0, 3.0, 12.0, 6.0, 4.0, 8.0, 13.0, 11.0,
       31.0, 10.0, 17.0], dtype=object)

In [53]:
hitList = []
for val in df_musket.Hits:
    val =str(val)
    if 'K' in val:
        val=float(val[:-1])*1000
        hitList.append(val)
    elif val.isnumeric():
         hitList.append(float(val))
    # elif val.isdigit() or val.isalnum(): to trap other important information
    #     print(val)       
    else:
        hitList.append('nan')  # val.isalnum()
hitList

[771.0,
 562.0,
 150.0,
 207.0,
 595.0,
 248.0,
 246.0,
 120.0,
 1600.0,
 130.0,
 321.0,
 189.0,
 175.0,
 96.0,
 118.0,
 216.0,
 212.0,
 154.0,
 205.0,
 202.0,
 339.0,
 408.0,
 103.0,
 332.0,
 86.0,
 173.0,
 246.0,
 161.0,
 396.0,
 1100.0,
 433.0,
 242.0,
 206.0,
 177.0,
 1500.0,
 198.0,
 459.0,
 173.0,
 117.0,
 130.0,
 119.0,
 209.0,
 84.0,
 187.0,
 165.0,
 203.0,
 65.0,
 336.0,
 126.0,
 313.0,
 124.0,
 154.0,
 145.0,
 538.0,
 182.0,
 175.0,
 101.0,
 45.0,
 103.0,
 377.0,
 99.0,
 194.0,
 161.0,
 403.0,
 414.0,
 593.0,
 374.0,
 245.0,
 3200.0,
 266.0,
 299.0,
 309.0,
 215.0,
 265.0,
 211.0,
 112.0,
 203.0,
 337.0,
 70.0,
 159.0,
 688.0,
 116.0,
 63.0,
 144.0,
 123.0,
 71.0,
 224.0,
 113.0,
 175.0,
 130.0,
 168.0,
 61.0,
 89.0,
 137.0,
 278.0,
 75.0,
 148.0,
 176.0,
 197.0,
 264.0,
 214.0,
 182.0,
 247.0,
 402.0,
 440.0,
 1700.0,
 2300.0,
 171.0,
 320.0,
 266.0,
 211.0,
 203.0,
 657.0,
 87.0,
 259.0,
 200.0,
 255.0,
 113.0,
 171.0,
 253.0,
 182.0,
 196.0,
 60.0,
 161.0,
 97.0,
 85.0,
 169.0,
 256.0,
 132.0,
 239.0,
 65.0,
 166.0,
 99.0,
 121.0,
 144.0,
 109.0,
 32.0,
 46.0,
 122.0,
 48.0,
 527.0,
 199.0,
 459.0,
 282.0,
 657.0,
 121.0,
 51.0,
 1900.0,
 642.0,
 155.0,
 171.0,
 323.0,
 288.0,
 497.0,
 509.0,
 79.0,
 49.0,
 270.0,
 511.0,
 80.0,
 247.0,
 128.0,
 115.0,
 156.0,
 87.0,
 196.0,
 204.0,
 143.0,
 337.0,
 140.0,
 87.0,
 207.0,
 112.0,
 152.0,
 220.0,
 122.0,
 134.0,
 225.0,
 96.0,
 94.0,
 74.0,
 135.0,
 142.0,
 45.0,
 50.0,
 77.0,
 40.0,
 107.0,
 193.0,
 179.0,
 34.0,
 64.0,
 453.0,
 112.0,
 57.0,
 81.0,
 70.0,
 28.0,
 124.0,
 79.0,
 193.0,
 128.0,
 78.0,
 137.0,
 133.0,
 282.0,
 61.0,
 71.0,
 43.0,
 425.0,
 96.0,
 65.0,
 87.0,
 65.0,
 313.0,
 88.0,
 145.0,
 42.0,
 36.0,
 199.0,
 256.0,
 233.0,
 376.0,
 205.0,
 49.0,
 210.0,
 225.0,
 132.0,
 444.0,
 84.0,
 159.0,
 100.0,
 212.0,
 263.0,
 248.0,
 98.0,
 29.0,
 160.0,
 159.0,
 145.0,
 39.0,
 257.0,
 75.0,
 6.0,
 310.0,
 65.0,
 77.0,
 138.0,
 94.0,
 62.0,
 74.0,
 36.0,
 65.0,
 293.0,
 285.0,
 362.0,
 66.0,
 69.0,
 58.0,
 21.0,
 20.0,
 43.0,
 131.0,
 142.0,
 38.0,
 406.0,
 68.0,
 71.0,
 108.0,
 85.0,
 36.0,
 110.0,
 96.0,
 93.0,
 512.0,
 110.0,
 443.0,
 306.0,
 352.0,
 422.0,
 585.0,
 282.0,
 346.0,
 178.0,
 841.0,
 76.0,
 394.0,
 72.0,
 43.0,
 172.0,
 44.0,
 42.0,
 75.0,
 214.0,
 407.0,
 210.0,
 36.0,
 107.0,
 230.0,
 88.0,
 367.0,
 189.0,
 93.0,
 233.0,
 103.0,
 295.0,
 194.0,
 197.0,
 157.0,
 112.0,
 84.0,
 243.0,
 56.0,
 130.0,
 111.0,
 326.0,
 130.0,
 679.0,
 197.0,
 117.0,
 215.0,
 111.0,
 18.0,
 74.0,
 56.0,
 92.0,
 48.0,
 115.0,
 140.0,
 100.0,
 62.0,
 97.0,
 72.0,
 138.0,
 79.0,
 133.0,
 124.0,
 132.0,
 65.0,
 81.0,
 68.0,
 46.0,
 77.0,
 214.0,
 123.0,
 59.0,
 25.0,
 44.0,
 42.0,
 154.0,
 130.0,
 74.0,
 184.0,
 58.0,
 38.0,
 71.0,
 72.0,
 75.0,
 53.0,
 38.0,
 68.0,
 32.0,
 39.0,
 12.0,
 93.0,
 90.0,
 88.0,
 55.0,
 73.0,
 11.0,
 566.0,
 180.0,
 83.0,
 262.0,
 18.0,
 17.0,
 12.0,
 11.0,
 26.0,
 31.0,
 31.0,
 245.0,
 64.0,
 280.0,
 359.0,
 337.0,
 213.0,
 297.0,
 145.0,
 387.0,
 108.0,
 480.0,
 381.0,
 6.0,
 414.0,
 200.0,
 28.0,
 28.0,
 28.0,
 259.0,
 173.0,
 71.0,
 677.0,
 56.0,
 74.0,
 152.0,
 182.0,
 486.0,
 8.0,
 244.0,
 248.0,
 129.0,
 194.0,
 388.0,
 275.0,
 319.0,
 2000.0,
 52.0,
 113.0,
 48.0,
 91.0,
 165.0,
 93.0,
 130.0,
 421.0,
 71.0,
 142.0,
 155.0,
 48.0,
 69.0,
 84.0,
 40.0,
 134.0,
 55.0,
 180.0,
 79.0,
 42.0,
 224.0,
 60.0,
 153.0,
 89.0,
 68.0,
 86.0,
 90.0,
 27.0,
 58.0,
 103.0,
 41.0,
 79.0,
 52.0,
 107.0,
 55.0,
 222.0,
 35.0,
 90.0,
 102.0,
 23.0,
 42.0,
 39.0,
 71.0,
 30.0,
 46.0,
 30.0,
 40.0,
 109.0,
 53.0,
 46.0,
 33.0,
 52.0,
 99.0,
 113.0,
 100.0,
 129.0,
 46.0,
 48.0,
 40.0,
 21.0,
 100.0,
 108.0,
 79.0,
 96.0,
 29.0,
 88.0,
 45.0,
 55.0,
 38.0,
 23.0,
 21.0,
 34.0,
 75.0,
 90.0,
 193.0,
 39.0,
 46.0,
 146.0,
 40.0,
 87.0,
 64.0,
 55.0,
 42.0,
 64.0,
 18.0,
 72.0,
 84.0,
 42.0,
 40.0,
 13.0,
 19.0,
 6.0,
 21.0,
 14.0,
 106.0,
 276.0,
 568.0,
 527.0,
 353.0,
 47.0,
 478.0,
 265.0,
 249.0,
 89.0,
 254.0,
 369.0,
 113.0,
 219.0,
 565.0,
 204.0,
 237.0,
 173.0,
 227.0,
 434.0,
 375.0,
 160.0,
 162.0,
 162.0,
 605.0,
 654.0,
 75.0,
 42.0,
 3.0,
 20.0,
 7.0,
 9.0,
 32.0,
 1100.0,
 282.0,
 118.0,
 184.0,
 104.0,
 168.0,
 14.0,
 156.0,
 100.0,
 93.0,
 114.0,
 81.0,
 186.0,
 242.0,
 101.0,
 150.0,
 41.0,
 8.0,
 111.0,
 148.0,
 446.0,
 131.0,
 124.0,
 20.0,
 237.0,
 130.0,
 49.0,
 131.0,
 116.0,
 756.0,
 22.0,
 43.0,
 20.0,
 32.0,
 61.0,
 42.0,
 73.0,
 189.0,
 122.0,
 50.0,
 20.0,
 124.0,
 29.0,
 139.0,
 25.0,
 107.0,
 89.0,
 61.0,
 135.0,
 187.0,
 22.0,
 500.0,
 72.0,
 67.0,
 27.0,
 64.0,
 56.0,
 147.0,
 52.0,
 33.0,
 93.0,
 230.0,
 21.0,
 78.0,
 149.0,
 45.0,
 16.0,
 40.0,
 134.0,
 65.0,
 30.0,
 61.0,
 49.0,
 35.0,
 51.0,
 81.0,
 22.0,
 48.0,
 126.0,
 21.0,
 39.0,
 114.0,
 71.0,
 45.0,
 20.0,
 28.0,
 19.0,
 23.0,
 19.0,
 119.0,
 35.0,
 82.0,
 73.0,
 32.0,
 55.0,
 19.0,
 214.0,
 25.0,
 54.0,
 98.0,
 82.0,
 9.0,
 67.0,
 30.0,
 21.0,
 50.0,
 53.0,
 89.0,
 61.0,
 39.0,
 20.0,
 29.0,
 41.0,
 31.0,
 31.0,
 112.0,
 12.0,
 20.0,
 17.0,
 8.0,
 42.0,
 37.0,
 99.0,
 71.0,
 16.0,
 128.0,
 53.0,
 16.0,
 17.0,
 36.0,
 129.0,
 83.0,
 17.0,
 27.0,
 70.0,
 67.0,
 15.0,
 56.0,
 44.0,
 44.0,
 91.0,
 62.0,
 20.0,
 1300.0,
 9.0,
 52.0,
 3000.0,
 15.0,
 952.0,
 5.0,
 688.0,
 749.0,
 541.0,
 50.0,
 330.0,
 276.0,
 30.0,
 15.0,
 393.0,
 247.0,
 129.0,
 184.0,
 517.0,
 108.0,
 770.0,
 169.0,
 111.0,
 220.0,
 162.0,
 409.0,
 47.0,
 170.0,
 50.0,
 125.0,
 283.0,
 408.0,
 239.0,
 342.0,
 63.0,
 363.0,
 23.0,
 68.0,
 580.0,
 5.0,
 16.0,
 7.0,
 3.0,
 15.0,
 9.0,
 16.0,
 8.0,
 29.0,
 112.0,
 15.0,
 215.0,
 105.0,
 101.0,
 59.0,
 217.0,
 280.0,
 24.0,
 249.0,
 145.0,
 119.0,
 42.0,
 26.0,
 45.0,
 132.0,
 70.0,
 18.0,
 73.0,
 41.0,
 19.0,
 145.0,
 157.0,
 93.0,
 187.0,
 81.0,
 142.0,
 15.0,
 68.0,
 66.0,
 53.0,
 16.0,
 52.0,
 5.0,
 39.0,
 31.0,
 150.0,
 16.0,
 60.0,
 55.0,
 141.0,
 38.0,
 139.0,
 70.0,
 13.0,
 14.0,
 49.0,
 26.0,
 15.0,
 84.0,
 33.0,
 43.0,
 39.0,
 84.0,
 168.0,
 107.0,
 131.0,
 14.0,
 84.0,
 31.0,
 63.0,
 64.0,
 55.0,
 62.0,
 96.0,
 128.0,
 81.0,
 39.0,
 62.0,
 88.0,
 20.0,
 65.0,
 54.0,
 19.0,
 17.0,
 50.0,
 18.0,
 47.0,
 39.0,
 34.0,
 84.0,
 12.0,
 76.0,
 98.0,
 22.0,
 23.0,
 11.0,
 37.0,
 109.0,
 47.0,
 15.0,
 57.0,
 103.0,
 20.0,
 35.0,
 41.0,
 34.0,
 11.0,
 47.0,
 33.0,
 17.0,
 125.0,
 50.0,
 44.0,
 30.0,
 16.0,
 21.0,
 35.0,
 57.0,
 128.0,
 31.0,
 22.0,
 33.0,
 52.0,
 41.0,
 11.0,
 38.0,
 30.0,
 9.0,
 107.0,
 16.0,
 17.0,
 22.0,
 70.0,
 41.0,
 17.0,
 3.0,
 8.0,
 20.0,
 36.0,
 11.0,
 26.0,
 34.0,
 18.0,
 58.0,
 32.0,
 17.0,
 62.0,
 29.0,
 38.0,
 10.0,
 10.0,
 13.0,
 17.0,
 15.0,
 26.0,
 58.0,
 6.0,
 16.0,
 13.0,
 20.0,
 12.0,
 31.0,
 14.0,
 39.0,
 12.0,
 18.0,
 11.0,
 10.0,
 28.0,
 27.0,
 40.0,
 24.0,
 16.0,
 17.0,
 116.0,
 29.0,
 97.0,
 49.0,
 212.0,
 427.0,
 74.0,
 10.0,
 19.0,
 247.0,
 162.0,
 40.0,
 28.0,
 70.0,
 140.0,
 158.0,
 426.0,
 51.0,
 19.0,
 24.0,
 4.0,
 25.0,
 24.0,
 12.0,
 33.0,
 44.0,
 19.0,
 77.0,
 3.0,
 41.0,
 15.0,
 11.0,
 35.0,
 58.0,
 25.0,
 10.0,
 38.0,
 24.0,
 207.0,
 159.0,
 21.0,
 46.0,
 19.0,
 36.0,
 123.0,
 9.0,
 247.0,
 72.0,
 44.0,
 28.0,
 102.0,
 92.0,
 32.0,
 29.0,
 48.0,
 37.0,
 13.0,
 9.0,
 28.0,
 40.0,
 8.0,
 13.0,
 114.0,
 666.0,
 37.0,
 22.0,
 58.0,
 51.0,
 28.0,
 47.0,
 87.0,
 4.0,
 54.0,
 181.0,
 19.0,
 12.0,
 42.0,
 16.0,
 16.0,
 324.0,
 18.0,
 35.0,
 25.0,
 7.0,
 30.0,
 7.0,
 19.0,
 47.0,
 26.0,
 107.0,
 62.0,
 17.0,
 29.0,
 40.0,
 979.0,
 32.0,
 15.0,
 15.0,
 29.0,
 ...]

In [54]:
dfNew['Hits1'] = hitList
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,RWB,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,0,4,4,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,0,4,5,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,0,3,1,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,0,5,4,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,0,5,5,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,0,2,2,1,66.0,1.78,100000.0,1000.0,70000.0,nan
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,0,2,2,1,65.0,1.75,130000.0,500000.0,165000.0,nan
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,0,2,2,1,74.0,1.79,120000.0,500000.0,131000.0,nan
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,3,2,1,69.0,1.75,100000.0,2000.0,88000.0,nan
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,0,3,2,1,75.0,1.88,100000.0,1000.0,79000.0,nan

Task 7 - Create 5 new categorical columns for the Height, Weight, Release Clause, Value and Wage into
which you convert the respective values into clusters/labels as follows
a. Height: Bucket intervals of 0.10 m
b. Weight: Bucket intervals of 10 kg
c. Wage: bucket intervals of 50K
d. Value: bucket intervals of 50M
e. Release Clause: bucket intervals of 50M
Height, Weight, Wage, Value, Release Clause

In [55]:
# Binning for Height (in metres)
Upperbands = [] #taking upperbands
count = 1

while count <= max(dfNew['ht(m)'])/0.10:
    Upperbands.append(0.10*count)
    count += 1
Upperbands

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3,
 1.4000000000000001,
 1.5,
 1.6,
 1.7000000000000002,
 1.8,
 1.9000000000000001,
 2.0]

In [56]:
dfNew['ht(m)_bins']=pd.cut(x=dfNew['ht(m)'], bins=Upperbands)
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1,ht(m)_bins
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,4,4,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0,"(1.6, 1.7]"
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,4,5,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0,"(1.8, 1.9]"
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,3,1,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0,"(1.8, 1.9]"
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,5,4,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0,"(1.8, 1.9]"
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,5,5,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0,"(1.7, 1.8]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,2,2,1,66.0,1.78,100000.0,1000.0,70000.0,nan,"(1.7, 1.8]"
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,2,2,1,65.0,1.75,130000.0,500000.0,165000.0,nan,"(1.7, 1.8]"
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,2,2,1,74.0,1.79,120000.0,500000.0,131000.0,nan,"(1.7, 1.8]"
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,3,2,1,69.0,1.75,100000.0,2000.0,88000.0,nan,"(1.7, 1.8]"
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,3,2,1,75.0,1.88,100000.0,1000.0,79000.0,nan,"(1.8, 1.9]"

In [57]:
max(dfNew['wt(kg)'])

110.0

In [58]:
min(dfNew['wt(kg)'])

50.0

In [59]:
# Binning for Weight (in 10 kg)
Upperbands = [] #taking upperbands
count = 1

while count <= max(dfNew['wt(kg)'])/10:
    Upperbands.append(10*count)
    count += 1
Upperbands

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110]

In [60]:
dfNew['wt(kg)_bins']=pd.cut(x=dfNew['wt(kg)'], bins=Upperbands)
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1,ht(m)_bins,wt(kg)_bins
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,4,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0,"(1.6, 1.7]","(70, 80]"
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,5,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0,"(1.8, 1.9]","(80, 90]"
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,1,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0,"(1.8, 1.9]","(80, 90]"
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,4,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0,"(1.8, 1.9]","(60, 70]"
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,5,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0,"(1.7, 1.8]","(60, 70]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,2,1,66.0,1.78,100000.0,1000.0,70000.0,nan,"(1.7, 1.8]","(60, 70]"
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,2,1,65.0,1.75,130000.0,500000.0,165000.0,nan,"(1.7, 1.8]","(60, 70]"
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,2,1,74.0,1.79,120000.0,500000.0,131000.0,nan,"(1.7, 1.8]","(70, 80]"
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,2,1,69.0,1.75,100000.0,2000.0,88000.0,nan,"(1.7, 1.8]","(60, 70]"
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,2,1,75.0,1.88,100000.0,1000.0,79000.0,nan,"(1.8, 1.9]","(70, 80]"

In [61]:
# Binning for Wage (in 50K €)
Upperbands = [] #taking upperbands
count = 1

while count <= max(dfNew['Wage(€)'])/50000:
    Upperbands.append(50000*count)
    count += 1
Upperbands

[50000,
 100000,
 150000,
 200000,
 250000,
 300000,
 350000,
 400000,
 450000,
 500000,
 550000,
 600000,
 650000,
 700000,
 750000,
 800000,
 850000,
 900000,
 950000]

In [62]:
dfNew['Wage(€)_bins']=pd.cut(x=dfNew['Wage(€)'], bins=Upperbands)
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1,ht(m)_bins,wt(kg)_bins,Wage(€)_bins
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0,"(1.6, 1.7]","(70, 80]","(550000.0, 600000.0]"
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0,"(1.8, 1.9]","(80, 90]","(200000.0, 250000.0]"
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0,"(1.8, 1.9]","(80, 90]","(100000.0, 150000.0]"
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0,"(1.8, 1.9]","(60, 70]","(350000.0, 400000.0]"
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0,"(1.7, 1.8]","(60, 70]","(250000.0, 300000.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,1,66.0,1.78,100000.0,1000.0,70000.0,nan,"(1.7, 1.8]","(60, 70]",NaN
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,1,65.0,1.75,130000.0,500000.0,165000.0,nan,"(1.7, 1.8]","(60, 70]","(450000.0, 500000.0]"
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,1,74.0,1.79,120000.0,500000.0,131000.0,nan,"(1.7, 1.8]","(70, 80]","(450000.0, 500000.0]"
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,1,69.0,1.75,100000.0,2000.0,88000.0,nan,"(1.7, 1.8]","(60, 70]",NaN
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,1,75.0,1.88,100000.0,1000.0,79000.0,nan,"(1.8, 1.9]","(70, 80]",NaN

In [63]:
# Binning for Value (in 50M €)
Upperbands = [] #taking upperbands
count = 1

while count <= max(dfNew['Value(€)'])/50000000:
    Upperbands.append(50000000*count)
    count += 1
Upperbands

[50000000, 100000000, 150000000]

In [64]:
dfNew['Value(€)_bins']=pd.cut(x=dfNew['Value(€)'], bins=Upperbands)
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1,ht(m)_bins,wt(kg)_bins,Wage(€)_bins,Value(€)_bins
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,72.0,1.70,103500000.0,560000.0,138400000.0,771.0,"(1.6, 1.7]","(70, 80]","(550000.0, 600000.0]","(100000000.0, 150000000.0]"
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,83.0,1.87,63000000.0,220000.0,75900000.0,562.0,"(1.8, 1.9]","(80, 90]","(200000.0, 250000.0]","(50000000.0, 100000000.0]"
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,87.0,1.88,120000000.0,125000.0,159400000.0,150.0,"(1.8, 1.9]","(80, 90]","(100000.0, 150000.0]","(100000000.0, 150000000.0]"
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,70.0,1.81,129000000.0,370000.0,161000000.0,207.0,"(1.8, 1.9]","(60, 70]","(350000.0, 400000.0]","(100000000.0, 150000000.0]"
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,68.0,1.75,132000000.0,270000.0,166500000.0,595.0,"(1.7, 1.8]","(60, 70]","(250000.0, 300000.0]","(100000000.0, 150000000.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,66.0,1.78,100000.0,1000.0,70000.0,nan,"(1.7, 1.8]","(60, 70]",NaN,NaN
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,65.0,1.75,130000.0,500000.0,165000.0,nan,"(1.7, 1.8]","(60, 70]","(450000.0, 500000.0]",NaN
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,74.0,1.79,120000.0,500000.0,131000.0,nan,"(1.7, 1.8]","(70, 80]","(450000.0, 500000.0]",NaN
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,69.0,1.75,100000.0,2000.0,88000.0,nan,"(1.7, 1.8]","(60, 70]",NaN,NaN
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,75.0,1.88,100000.0,1000.0,79000.0,nan,"(1.8, 1.9]","(70, 80]",NaN,NaN

In [65]:
# Binning for Release Clause (in 50M €)
Upperbands = [] #taking upperbands
count = 1

while count <= max(dfNew['Release Clause(€)'])/50000000:
    Upperbands.append(50000000*count)
    count += 1
Upperbands

[50000000, 100000000, 150000000, 200000000]

In [66]:
dfNew['Release Clause(€)_bins']=pd.cut(x=dfNew['Release Clause(€)'], bins=Upperbands)
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,ht(m),Value(€),Wage(€),Release Clause(€),Hits1,ht(m)_bins,wt(kg)_bins,Wage(€)_bins,Value(€)_bins,Release Clause(€)_bins
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,1.70,103500000.0,560000.0,138400000.0,771.0,"(1.6, 1.7]","(70, 80]","(550000.0, 600000.0]","(100000000.0, 150000000.0]","(100000000.0, 150000000.0]"
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,1.87,63000000.0,220000.0,75900000.0,562.0,"(1.8, 1.9]","(80, 90]","(200000.0, 250000.0]","(50000000.0, 100000000.0]","(50000000.0, 100000000.0]"
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,1.88,120000000.0,125000.0,159400000.0,150.0,"(1.8, 1.9]","(80, 90]","(100000.0, 150000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]"
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,1.81,129000000.0,370000.0,161000000.0,207.0,"(1.8, 1.9]","(60, 70]","(350000.0, 400000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]"
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,1.75,132000000.0,270000.0,166500000.0,595.0,"(1.7, 1.8]","(60, 70]","(250000.0, 300000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,1.78,100000.0,1000.0,70000.0,nan,"(1.7, 1.8]","(60, 70]",NaN,NaN,NaN
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,1.75,130000.0,500000.0,165000.0,nan,"(1.7, 1.8]","(60, 70]","(450000.0, 500000.0]",NaN,NaN
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,1.79,120000.0,500000.0,131000.0,nan,"(1.7, 1.8]","(70, 80]","(450000.0, 500000.0]",NaN,NaN
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,1.75,100000.0,2000.0,88000.0,nan,"(1.7, 1.8]","(60, 70]",NaN,NaN,NaN
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,1.88,100000.0,1000.0,79000.0,nan,"(1.8, 1.9]","(70, 80]",NaN,NaN,NaN

Select input features for an outcome feature of HITS

In [67]:
dfNew.Dribbling.unique() # Checking unique values in Dribbling

array(['96', '88', '12', '95', '85', '90', '27', '92', '21', '70', '91',
       '69', '13', '30', '87', '65', '79', '83', '23', '80', '18', '93',
       '77', '63', '76', '16', '59', '81', '11', '84', '10', '75', '78',
       '55', '15', '86', '66', '67', '28', '57', '64', '82', '62', '19',
       '53', '72', '50', '26', '43', '89', '73', '20', '14', '68', '71',
       '74', '22', '54', '56', '61', '9', '24', '60', '25', '8', '17',
       '47', '58', '46', '42', '51', '52', '49', '44', '35', '48', '39',
       '29', '40', '70_', '45', nan, '34', '31', '33', '38', '41', '32',
       '7', '37', '36', '5', '6', 64, 46, 65, 61, 57, 60, 71, 19, 41, 18,
       63, 70, 74, 62, 58, 12, 67, 52, 26, 50, 13, 32, 33, 14, 75, 49, 51,
       76, 16, 36, 59, 34, 68, 66, 72, 17, 54, 44, 73, 42, 56, 55, 37, 69,
       40, 30, 47, 24, 11, 15, 45, 35, 39, 38, 6, 7, 53, 43, 48, 10, 20,
       29, 9, 8, 28, 5, 31, 25, 22, 27, 23, 77, 21], dtype=object)

In [68]:
dribList = [] 
for val in dfNew.Dribbling.values:
    val = str(val)
    if '_' in val:
        val=float(val[:-1])
        dribList.append(val)
    elif val.isnumeric():
         dribList.append(float(val))
    else:
        dribList.append(val) 
dribList

[96.0,
 88.0,
 12.0,
 88.0,
 95.0,
 85.0,
 90.0,
 27.0,
 92.0,
 21.0,
 70.0,
 91.0,
 69.0,
 13.0,
 30.0,
 87.0,
 65.0,
 88.0,
 90.0,
 79.0,
 83.0,
 91.0,
 23.0,
 80.0,
 18.0,
 69.0,
 93.0,
 80.0,
 87.0,
 92.0,
 77.0,
 92.0,
 80.0,
 63.0,
 85.0,
 76.0,
 88.0,
 90.0,
 16.0,
 59.0,
 81.0,
 80.0,
 11.0,
 88.0,
 85.0,
 84.0,
 10.0,
 83.0,
 75.0,
 18.0,
 78.0,
 55.0,
 90.0,
 87.0,
 77.0,
 63.0,
 69.0,
 15.0,
 86.0,
 87.0,
 81.0,
 78.0,
 76.0,
 86.0,
 85.0,
 86.0,
 66.0,
 67.0,
 87.0,
 28.0,
 87.0,
 88.0,
 83.0,
 57.0,
 64.0,
 90.0,
 82.0,
 84.0,
 82.0,
 76.0,
 87.0,
 90.0,
 62.0,
 67.0,
 80.0,
 16.0,
 78.0,
 80.0,
 90.0,
 79.0,
 77.0,
 19.0,
 69.0,
 88.0,
 86.0,
 53.0,
 85.0,
 86.0,
 85.0,
 72.0,
 50.0,
 26.0,
 88.0,
 85.0,
 87.0,
 75.0,
 82.0,
 88.0,
 84.0,
 87.0,
 43.0,
 87.0,
 89.0,
 57.0,
 82.0,
 81.0,
 84.0,
 87.0,
 73.0,
 84.0,
 81.0,
 78.0,
 12.0,
 88.0,
 82.0,
 83.0,
 92.0,
 77.0,
 76.0,
 89.0,
 87.0,
 92.0,
 66.0,
 76.0,
 77.0,
 67.0,
 15.0,
 12.0,
 79.0,
 20.0,
 75.0,
 84.0,
 84.0,
 80.0,
 89.0,
 86.0,
 85.0,
 82.0,
 78.0,
 88.0,
 87.0,
 87.0,
 67.0,
 86.0,
 76.0,
 18.0,
 19.0,
 65.0,
 79.0,
 81.0,
 86.0,
 88.0,
 88.0,
 14.0,
 85.0,
 79.0,
 84.0,
 85.0,
 68.0,
 83.0,
 79.0,
 64.0,
 79.0,
 84.0,
 79.0,
 79.0,
 88.0,
 82.0,
 71.0,
 84.0,
 76.0,
 74.0,
 78.0,
 15.0,
 79.0,
 69.0,
 22.0,
 84.0,
 90.0,
 54.0,
 10.0,
 87.0,
 89.0,
 81.0,
 14.0,
 65.0,
 84.0,
 10.0,
 82.0,
 72.0,
 82.0,
 76.0,
 76.0,
 83.0,
 89.0,
 80.0,
 83.0,
 70.0,
 19.0,
 80.0,
 84.0,
 82.0,
 80.0,
 82.0,
 65.0,
 50.0,
 82.0,
 12.0,
 56.0,
 85.0,
 82.0,
 85.0,
 79.0,
 76.0,
 16.0,
 78.0,
 84.0,
 86.0,
 78.0,
 86.0,
 83.0,
 22.0,
 84.0,
 10.0,
 82.0,
 61.0,
 13.0,
 71.0,
 82.0,
 87.0,
 14.0,
 85.0,
 14.0,
 9.0,
 71.0,
 75.0,
 15.0,
 81.0,
 12.0,
 80.0,
 19.0,
 19.0,
 24.0,
 86.0,
 75.0,
 83.0,
 60.0,
 83.0,
 86.0,
 19.0,
 15.0,
 71.0,
 26.0,
 81.0,
 59.0,
 82.0,
 86.0,
 78.0,
 88.0,
 78.0,
 25.0,
 80.0,
 64.0,
 79.0,
 85.0,
 82.0,
 79.0,
 57.0,
 87.0,
 82.0,
 83.0,
 81.0,
 84.0,
 76.0,
 85.0,
 77.0,
 84.0,
 78.0,
 84.0,
 77.0,
 75.0,
 77.0,
 60.0,
 78.0,
 86.0,
 74.0,
 8.0,
 65.0,
 60.0,
 78.0,
 78.0,
 78.0,
 83.0,
 81.0,
 87.0,
 87.0,
 77.0,
 81.0,
 63.0,
 76.0,
 83.0,
 88.0,
 15.0,
 84.0,
 13.0,
 75.0,
 78.0,
 82.0,
 83.0,
 71.0,
 68.0,
 74.0,
 17.0,
 84.0,
 64.0,
 85.0,
 13.0,
 60.0,
 76.0,
 14.0,
 47.0,
 82.0,
 74.0,
 77.0,
 87.0,
 79.0,
 87.0,
 74.0,
 79.0,
 78.0,
 81.0,
 12.0,
 84.0,
 75.0,
 74.0,
 14.0,
 83.0,
 85.0,
 58.0,
 90.0,
 85.0,
 78.0,
 84.0,
 86.0,
 87.0,
 82.0,
 80.0,
 61.0,
 87.0,
 54.0,
 81.0,
 12.0,
 14.0,
 10.0,
 87.0,
 76.0,
 58.0,
 16.0,
 76.0,
 60.0,
 88.0,
 72.0,
 19.0,
 80.0,
 9.0,
 77.0,
 75.0,
 82.0,
 74.0,
 56.0,
 79.0,
 88.0,
 75.0,
 86.0,
 86.0,
 13.0,
 65.0,
 70.0,
 12.0,
 79.0,
 69.0,
 79.0,
 80.0,
 47.0,
 85.0,
 79.0,
 82.0,
 75.0,
 78.0,
 84.0,
 66.0,
 53.0,
 73.0,
 19.0,
 76.0,
 83.0,
 83.0,
 91.0,
 14.0,
 84.0,
 83.0,
 79.0,
 86.0,
 71.0,
 81.0,
 71.0,
 82.0,
 82.0,
 76.0,
 16.0,
 85.0,
 76.0,
 79.0,
 87.0,
 85.0,
 72.0,
 86.0,
 78.0,
 19.0,
 81.0,
 81.0,
 82.0,
 64.0,
 85.0,
 84.0,
 84.0,
 53.0,
 85.0,
 74.0,
 83.0,
 66.0,
 80.0,
 75.0,
 59.0,
 11.0,
 54.0,
 87.0,
 85.0,
 80.0,
 63.0,
 69.0,
 76.0,
 77.0,
 74.0,
 61.0,
 77.0,
 78.0,
 13.0,
 75.0,
 78.0,
 73.0,
 83.0,
 68.0,
 76.0,
 79.0,
 70.0,
 77.0,
 70.0,
 75.0,
 76.0,
 85.0,
 66.0,
 78.0,
 67.0,
 85.0,
 73.0,
 12.0,
 58.0,
 46.0,
 75.0,
 68.0,
 80.0,
 12.0,
 68.0,
 78.0,
 68.0,
 83.0,
 16.0,
 80.0,
 71.0,
 85.0,
 50.0,
 78.0,
 76.0,
 88.0,
 80.0,
 85.0,
 73.0,
 89.0,
 42.0,
 82.0,
 15.0,
 86.0,
 77.0,
 83.0,
 79.0,
 18.0,
 78.0,
 77.0,
 78.0,
 76.0,
 78.0,
 77.0,
 83.0,
 84.0,
 51.0,
 8.0,
 67.0,
 74.0,
 83.0,
 70.0,
 72.0,
 78.0,
 82.0,
 77.0,
 77.0,
 81.0,
 71.0,
 81.0,
 83.0,
 67.0,
 68.0,
 78.0,
 76.0,
 70.0,
 78.0,
 70.0,
 81.0,
 82.0,
 18.0,
 72.0,
 75.0,
 68.0,
 76.0,
 68.0,
 85.0,
 80.0,
 78.0,
 79.0,
 77.0,
 79.0,
 64.0,
 74.0,
 79.0,
 84.0,
 76.0,
 60.0,
 59.0,
 79.0,
 78.0,
 73.0,
 76.0,
 74.0,
 77.0,
 76.0,
 82.0,
 67.0,
 60.0,
 80.0,
 74.0,
 76.0,
 79.0,
 81.0,
 92.0,
 74.0,
 86.0,
 72.0,
 62.0,
 83.0,
 81.0,
 75.0,
 66.0,
 81.0,
 80.0,
 74.0,
 66.0,
 82.0,
 55.0,
 17.0,
 73.0,
 78.0,
 18.0,
 81.0,
 84.0,
 79.0,
 13.0,
 85.0,
 83.0,
 70.0,
 51.0,
 18.0,
 69.0,
 76.0,
 78.0,
 80.0,
 85.0,
 12.0,
 79.0,
 78.0,
 78.0,
 64.0,
 62.0,
 75.0,
 52.0,
 78.0,
 78.0,
 85.0,
 49.0,
 15.0,
 81.0,
 78.0,
 78.0,
 82.0,
 80.0,
 79.0,
 86.0,
 77.0,
 65.0,
 12.0,
 82.0,
 19.0,
 81.0,
 78.0,
 74.0,
 79.0,
 76.0,
 84.0,
 76.0,
 67.0,
 70.0,
 62.0,
 84.0,
 62.0,
 78.0,
 79.0,
 75.0,
 59.0,
 59.0,
 69.0,
 77.0,
 80.0,
 70.0,
 73.0,
 13.0,
 74.0,
 83.0,
 78.0,
 87.0,
 75.0,
 83.0,
 80.0,
 63.0,
 75.0,
 67.0,
 77.0,
 73.0,
 69.0,
 76.0,
 77.0,
 80.0,
 80.0,
 70.0,
 23.0,
 74.0,
 72.0,
 58.0,
 81.0,
 12.0,
 62.0,
 14.0,
 13.0,
 58.0,
 10.0,
 10.0,
 84.0,
 78.0,
 78.0,
 84.0,
 82.0,
 72.0,
 85.0,
 44.0,
 78.0,
 76.0,
 72.0,
 61.0,
 16.0,
 30.0,
 73.0,
 81.0,
 78.0,
 84.0,
 64.0,
 80.0,
 35.0,
 68.0,
 85.0,
 79.0,
 69.0,
 82.0,
 79.0,
 81.0,
 14.0,
 84.0,
 69.0,
 83.0,
 48.0,
 82.0,
 49.0,
 82.0,
 72.0,
 69.0,
 82.0,
 83.0,
 82.0,
 68.0,
 83.0,
 72.0,
 78.0,
 81.0,
 80.0,
 76.0,
 51.0,
 44.0,
 75.0,
 71.0,
 73.0,
 79.0,
 77.0,
 68.0,
 76.0,
 78.0,
 86.0,
 75.0,
 81.0,
 75.0,
 16.0,
 81.0,
 16.0,
 81.0,
 76.0,
 75.0,
 78.0,
 13.0,
 79.0,
 77.0,
 71.0,
 75.0,
 67.0,
 79.0,
 77.0,
 62.0,
 62.0,
 79.0,
 85.0,
 82.0,
 55.0,
 73.0,
 77.0,
 77.0,
 76.0,
 74.0,
 75.0,
 49.0,
 79.0,
 76.0,
 84.0,
 77.0,
 72.0,
 62.0,
 79.0,
 65.0,
 75.0,
 82.0,
 75.0,
 72.0,
 79.0,
 79.0,
 76.0,
 75.0,
 69.0,
 82.0,
 83.0,
 13.0,
 75.0,
 72.0,
 69.0,
 64.0,
 68.0,
 76.0,
 76.0,
 75.0,
 64.0,
 11.0,
 82.0,
 81.0,
 76.0,
 74.0,
 79.0,
 58.0,
 76.0,
 84.0,
 73.0,
 82.0,
 83.0,
 55.0,
 78.0,
 71.0,
 16.0,
 13.0,
 83.0,
 55.0,
 80.0,
 75.0,
 78.0,
 81.0,
 80.0,
 73.0,
 65.0,
 58.0,
 16.0,
 77.0,
 71.0,
 55.0,
 65.0,
 79.0,
 53.0,
 83.0,
 80.0,
 82.0,
 75.0,
 65.0,
 17.0,
 75.0,
 80.0,
 81.0,
 73.0,
 46.0,
 66.0,
 72.0,
 76.0,
 16.0,
 80.0,
 76.0,
 70.0,
 66.0,
 83.0,
 82.0,
 75.0,
 79.0,
 76.0,
 13.0,
 42.0,
 78.0,
 54.0,
 74.0,
 19.0,
 77.0,
 66.0,
 81.0,
 53.0,
 75.0,
 70.0,
 77.0,
 83.0,
 80.0,
 80.0,
 24.0,
 79.0,
 82.0,
 74.0,
 65.0,
 63.0,
 66.0,
 63.0,
 73.0,
 77.0,
 81.0,
 80.0,
 74.0,
 78.0,
 72.0,
 80.0,
 73.0,
 14.0,
 58.0,
 79.0,
 82.0,
 76.0,
 80.0,
 17.0,
 77.0,
 82.0,
 76.0,
 71.0,
 77.0,
 74.0,
 78.0,
 14.0,
 76.0,
 78.0,
 67.0,
 75.0,
 39.0,
 85.0,
 85.0,
 74.0,
 79.0,
 85.0,
 81.0,
 72.0,
 75.0,
 77.0,
 67.0,
 29.0,
 71.0,
 80.0,
 18.0,
 78.0,
 72.0,
 62.0,
 40.0,
 14.0,
 76.0,
 82.0,
 78.0,
 73.0,
 70.0,
 85.0,
 61.0,
 82.0,
 79.0,
 20.0,
 78.0,
 15.0,
 68.0,
 75.0,
 69.0,
 80.0,
 81.0,
 27.0,
 84.0,
 19.0,
 79.0,
 61.0,
 80.0,
 66.0,
 15.0,
 18.0,
 72.0,
 81.0,
 74.0,
 73.0,
 78.0,
 70.0,
 71.0,
 77.0,
 20.0,
 59.0,
 54.0,
 76.0,
 79.0,
 69.0,
 64.0,
 82.0,
 42.0,
 72.0,
 62.0,
 73.0,
 82.0,
 65.0,
 80.0,
 81.0,
 71.0,
 51.0,
 86.0,
 10.0,
 16.0,
 83.0,
 45.0,
 77.0,
 76.0,
 83.0,
 74.0,
 74.0,
 80.0,
 71.0,
 16.0,
 72.0,
 77.0,
 ...]

In [69]:
dfNew['Dribbling1'] = dribList
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,Value(€),Wage(€),Release Clause(€),Hits1,ht(m)_bins,wt(kg)_bins,Wage(€)_bins,Value(€)_bins,Release Clause(€)_bins,Dribbling1
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,103500000.0,560000.0,138400000.0,771.0,"(1.6, 1.7]","(70, 80]","(550000.0, 600000.0]","(100000000.0, 150000000.0]","(100000000.0, 150000000.0]",96.0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,63000000.0,220000.0,75900000.0,562.0,"(1.8, 1.9]","(80, 90]","(200000.0, 250000.0]","(50000000.0, 100000000.0]","(50000000.0, 100000000.0]",88.0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,120000000.0,125000.0,159400000.0,150.0,"(1.8, 1.9]","(80, 90]","(100000.0, 150000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]",12.0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,129000000.0,370000.0,161000000.0,207.0,"(1.8, 1.9]","(60, 70]","(350000.0, 400000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]",88.0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,132000000.0,270000.0,166500000.0,595.0,"(1.7, 1.8]","(60, 70]","(250000.0, 300000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]",95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,100000.0,1000.0,70000.0,nan,"(1.7, 1.8]","(60, 70]",NaN,NaN,NaN,27.0
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,130000.0,500000.0,165000.0,nan,"(1.7, 1.8]","(60, 70]","(450000.0, 500000.0]",NaN,NaN,46.0
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,120000.0,500000.0,131000.0,nan,"(1.7, 1.8]","(70, 80]","(450000.0, 500000.0]",NaN,NaN,43.0
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,100000.0,2000.0,88000.0,nan,"(1.7, 1.8]","(60, 70]",NaN,NaN,NaN,51.0
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,100000.0,1000.0,79000.0,nan,"(1.8, 1.9]","(70, 80]",NaN,NaN,NaN,40.0

In [70]:
dfNew['Short Passing'].unique()

array(['91', '82', '43', '94', '87', '84', '45', '83', '61', '79', '85',
       '33', '55', '86', '57', '81', '42', '74', '93', '88', '30', '65',
       '89', '77', '32', '50', '80', '78', '90', '69', '40', '92', '75',
       '73', '34', '76', '35', '70', '37', '23', '44', '38', '48', '26',
       '60', '25', '46', '28', '24', '36', '51', '17', '18', '39', '71',
       '67', '27', '72', '66', '20', '31', '68', '29', '11', '64', '62',
       nan, '41', '63', '19', '54', '16', '69_', '22', '49', '59', '14',
       '58', '15', '21', '52', '56', '53', '12', '47', '13', 58, 65, 70,
       67, 66, 57, 72, 37, 26, 60, 64, 55, 56, 59, 68, 21, 74, 42, 63, 62,
       47, 22, 52, 15, 12, 73, 61, 54, 71, 25, 28, 27, 31, 69, 50, 75, 29,
       36, 41, 32, 53, 48, 30, 11, 35, 16, 51, 18, 43, 19, 34, 33, 23, 38,
       20, 13, 39, 49, 24, 46, 17, 8, 14, 45, 44, 40, 76, 7], dtype=object)

In [71]:
shpasList = [] 
for val in dfNew['Short Passing'].values:
    val = str(val)
    if '_' in val:
        val=float(val[:-1])
        shpasList.append(val)
    elif val.isnumeric():
         shpasList.append(float(val))
    else:
        shpasList.append(val) 
shpasList

[91.0,
 82.0,
 43.0,
 94.0,
 87.0,
 84.0,
 84.0,
 45.0,
 83.0,
 61.0,
 79.0,
 85.0,
 84.0,
 33.0,
 55.0,
 86.0,
 82.0,
 83.0,
 84.0,
 85.0,
 87.0,
 87.0,
 57.0,
 81.0,
 42.0,
 74.0,
 85.0,
 93.0,
 84.0,
 88.0,
 85.0,
 86.0,
 82.0,
 82.0,
 88.0,
 85.0,
 83.0,
 87.0,
 30.0,
 65.0,
 89.0,
 77.0,
 32.0,
 83.0,
 91.0,
 83.0,
 50.0,
 80.0,
 84.0,
 50.0,
 83.0,
 78.0,
 90.0,
 86.0,
 69.0,
 81.0,
 82.0,
 40.0,
 92.0,
 86.0,
 84.0,
 86.0,
 85.0,
 85.0,
 81.0,
 84.0,
 75.0,
 73.0,
 81.0,
 34.0,
 79.0,
 81.0,
 86.0,
 78.0,
 82.0,
 80.0,
 83.0,
 78.0,
 92.0,
 76.0,
 90.0,
 83.0,
 79.0,
 80.0,
 87.0,
 50.0,
 79.0,
 81.0,
 89.0,
 78.0,
 90.0,
 35.0,
 77.0,
 82.0,
 90.0,
 79.0,
 88.0,
 90.0,
 85.0,
 79.0,
 70.0,
 33.0,
 84.0,
 81.0,
 78.0,
 74.0,
 83.0,
 78.0,
 81.0,
 88.0,
 78.0,
 87.0,
 80.0,
 73.0,
 84.0,
 85.0,
 87.0,
 82.0,
 78.0,
 81.0,
 83.0,
 81.0,
 37.0,
 86.0,
 80.0,
 85.0,
 84.0,
 85.0,
 81.0,
 79.0,
 79.0,
 83.0,
 73.0,
 86.0,
 82.0,
 78.0,
 23.0,
 44.0,
 90.0,
 34.0,
 75.0,
 81.0,
 81.0,
 80.0,
 78.0,
 82.0,
 83.0,
 74.0,
 83.0,
 84.0,
 81.0,
 84.0,
 78.0,
 83.0,
 82.0,
 38.0,
 48.0,
 76.0,
 85.0,
 79.0,
 77.0,
 77.0,
 74.0,
 26.0,
 75.0,
 82.0,
 83.0,
 81.0,
 75.0,
 82.0,
 83.0,
 78.0,
 89.0,
 83.0,
 83.0,
 75.0,
 90.0,
 76.0,
 83.0,
 85.0,
 80.0,
 80.0,
 84.0,
 32.0,
 85.0,
 77.0,
 38.0,
 79.0,
 75.0,
 60.0,
 30.0,
 84.0,
 82.0,
 86.0,
 35.0,
 75.0,
 88.0,
 25.0,
 82.0,
 82.0,
 84.0,
 81.0,
 77.0,
 85.0,
 81.0,
 80.0,
 85.0,
 77.0,
 46.0,
 78.0,
 81.0,
 87.0,
 75.0,
 85.0,
 79.0,
 75.0,
 83.0,
 28.0,
 74.0,
 83.0,
 84.0,
 74.0,
 84.0,
 86.0,
 24.0,
 80.0,
 81.0,
 76.0,
 79.0,
 79.0,
 79.0,
 36.0,
 80.0,
 51.0,
 84.0,
 78.0,
 28.0,
 77.0,
 84.0,
 77.0,
 32.0,
 81.0,
 17.0,
 18.0,
 78.0,
 84.0,
 32.0,
 81.0,
 48.0,
 82.0,
 36.0,
 33.0,
 37.0,
 83.0,
 83.0,
 78.0,
 80.0,
 83.0,
 78.0,
 30.0,
 39.0,
 78.0,
 37.0,
 84.0,
 74.0,
 88.0,
 84.0,
 85.0,
 80.0,
 82.0,
 44.0,
 78.0,
 77.0,
 79.0,
 85.0,
 77.0,
 81.0,
 73.0,
 79.0,
 80.0,
 77.0,
 76.0,
 74.0,
 69.0,
 77.0,
 82.0,
 77.0,
 71.0,
 85.0,
 78.0,
 73.0,
 81.0,
 67.0,
 76.0,
 77.0,
 80.0,
 40.0,
 76.0,
 79.0,
 80.0,
 78.0,
 84.0,
 79.0,
 84.0,
 85.0,
 75.0,
 80.0,
 74.0,
 74.0,
 76.0,
 82.0,
 81.0,
 26.0,
 81.0,
 27.0,
 72.0,
 84.0,
 80.0,
 77.0,
 78.0,
 78.0,
 76.0,
 42.0,
 80.0,
 72.0,
 84.0,
 26.0,
 75.0,
 66.0,
 55.0,
 71.0,
 78.0,
 75.0,
 76.0,
 84.0,
 80.0,
 79.0,
 78.0,
 81.0,
 78.0,
 82.0,
 50.0,
 83.0,
 80.0,
 74.0,
 37.0,
 81.0,
 84.0,
 78.0,
 81.0,
 90.0,
 83.0,
 85.0,
 76.0,
 80.0,
 83.0,
 83.0,
 77.0,
 77.0,
 75.0,
 84.0,
 33.0,
 20.0,
 31.0,
 83.0,
 81.0,
 73.0,
 37.0,
 75.0,
 67.0,
 72.0,
 73.0,
 46.0,
 80.0,
 18.0,
 78.0,
 78.0,
 79.0,
 68.0,
 74.0,
 80.0,
 84.0,
 79.0,
 78.0,
 82.0,
 32.0,
 76.0,
 70.0,
 29.0,
 81.0,
 80.0,
 78.0,
 73.0,
 66.0,
 74.0,
 83.0,
 79.0,
 69.0,
 73.0,
 73.0,
 77.0,
 73.0,
 73.0,
 34.0,
 76.0,
 82.0,
 81.0,
 76.0,
 28.0,
 72.0,
 82.0,
 83.0,
 77.0,
 74.0,
 73.0,
 79.0,
 79.0,
 83.0,
 82.0,
 31.0,
 84.0,
 81.0,
 79.0,
 75.0,
 81.0,
 81.0,
 79.0,
 68.0,
 37.0,
 78.0,
 82.0,
 77.0,
 69.0,
 82.0,
 83.0,
 84.0,
 72.0,
 80.0,
 76.0,
 81.0,
 85.0,
 84.0,
 75.0,
 78.0,
 17.0,
 70.0,
 77.0,
 80.0,
 75.0,
 77.0,
 80.0,
 77.0,
 77.0,
 78.0,
 74.0,
 75.0,
 81.0,
 40.0,
 78.0,
 81.0,
 76.0,
 80.0,
 78.0,
 78.0,
 74.0,
 79.0,
 85.0,
 79.0,
 80.0,
 77.0,
 78.0,
 78.0,
 82.0,
 83.0,
 78.0,
 77.0,
 34.0,
 71.0,
 78.0,
 65.0,
 77.0,
 80.0,
 44.0,
 75.0,
 82.0,
 72.0,
 84.0,
 39.0,
 82.0,
 78.0,
 76.0,
 67.0,
 75.0,
 80.0,
 80.0,
 83.0,
 81.0,
 79.0,
 85.0,
 74.0,
 79.0,
 23.0,
 80.0,
 84.0,
 83.0,
 79.0,
 11.0,
 78.0,
 80.0,
 71.0,
 76.0,
 81.0,
 68.0,
 78.0,
 73.0,
 75.0,
 26.0,
 75.0,
 74.0,
 75.0,
 80.0,
 79.0,
 82.0,
 77.0,
 82.0,
 80.0,
 83.0,
 72.0,
 78.0,
 73.0,
 79.0,
 79.0,
 81.0,
 77.0,
 82.0,
 72.0,
 67.0,
 82.0,
 74.0,
 11.0,
 78.0,
 78.0,
 75.0,
 76.0,
 75.0,
 76.0,
 69.0,
 79.0,
 71.0,
 86.0,
 65.0,
 65.0,
 78.0,
 81.0,
 79.0,
 76.0,
 67.0,
 78.0,
 82.0,
 76.0,
 72.0,
 81.0,
 77.0,
 78.0,
 70.0,
 80.0,
 73.0,
 78.0,
 72.0,
 86.0,
 81.0,
 77.0,
 84.0,
 72.0,
 68.0,
 77.0,
 84.0,
 64.0,
 77.0,
 77.0,
 72.0,
 80.0,
 81.0,
 75.0,
 72.0,
 79.0,
 77.0,
 73.0,
 30.0,
 77.0,
 83.0,
 31.0,
 77.0,
 85.0,
 80.0,
 20.0,
 75.0,
 82.0,
 81.0,
 70.0,
 25.0,
 77.0,
 82.0,
 73.0,
 84.0,
 83.0,
 27.0,
 76.0,
 82.0,
 81.0,
 80.0,
 80.0,
 85.0,
 69.0,
 75.0,
 75.0,
 73.0,
 73.0,
 26.0,
 80.0,
 85.0,
 75.0,
 79.0,
 79.0,
 77.0,
 85.0,
 85.0,
 81.0,
 28.0,
 76.0,
 38.0,
 85.0,
 75.0,
 79.0,
 78.0,
 81.0,
 80.0,
 74.0,
 82.0,
 79.0,
 81.0,
 79.0,
 72.0,
 82.0,
 77.0,
 78.0,
 65.0,
 62.0,
 82.0,
 68.0,
 79.0,
 'nan',
 77.0,
 41.0,
 77.0,
 75.0,
 83.0,
 80.0,
 78.0,
 82.0,
 78.0,
 78.0,
 80.0,
 68.0,
 77.0,
 81.0,
 75.0,
 75.0,
 72.0,
 84.0,
 82.0,
 84.0,
 43.0,
 79.0,
 69.0,
 63.0,
 81.0,
 36.0,
 76.0,
 36.0,
 35.0,
 79.0,
 31.0,
 19.0,
 'nan',
 78.0,
 78.0,
 73.0,
 74.0,
 75.0,
 71.0,
 68.0,
 83.0,
 76.0,
 77.0,
 80.0,
 44.0,
 40.0,
 78.0,
 76.0,
 74.0,
 75.0,
 77.0,
 71.0,
 75.0,
 81.0,
 74.0,
 80.0,
 75.0,
 79.0,
 83.0,
 79.0,
 54.0,
 76.0,
 66.0,
 72.0,
 78.0,
 78.0,
 73.0,
 69.0,
 69.0,
 75.0,
 77.0,
 79.0,
 79.0,
 75.0,
 69.0,
 69.0,
 85.0,
 78.0,
 85.0,
 76.0,
 71.0,
 68.0,
 73.0,
 77.0,
 66.0,
 80.0,
 76.0,
 77.0,
 75.0,
 85.0,
 74.0,
 73.0,
 75.0,
 78.0,
 29.0,
 72.0,
 28.0,
 70.0,
 75.0,
 64.0,
 69.0,
 32.0,
 78.0,
 77.0,
 68.0,
 79.0,
 77.0,
 72.0,
 72.0,
 74.0,
 63.0,
 75.0,
 72.0,
 74.0,
 70.0,
 70.0,
 84.0,
 75.0,
 74.0,
 80.0,
 78.0,
 73.0,
 79.0,
 80.0,
 84.0,
 81.0,
 80.0,
 71.0,
 78.0,
 64.0,
 78.0,
 76.0,
 74.0,
 75.0,
 77.0,
 74.0,
 75.0,
 67.0,
 77.0,
 63.0,
 82.0,
 31.0,
 78.0,
 77.0,
 66.0,
 72.0,
 79.0,
 81.0,
 77.0,
 73.0,
 70.0,
 32.0,
 75.0,
 76.0,
 78.0,
 74.0,
 79.0,
 80.0,
 82.0,
 75.0,
 71.0,
 79.0,
 76.0,
 72.0,
 62.0,
 74.0,
 38.0,
 45.0,
 77.0,
 67.0,
 81.0,
 76.0,
 83.0,
 74.0,
 77.0,
 69.0,
 75.0,
 65.0,
 36.0,
 79.0,
 80.0,
 69.0,
 75.0,
 77.0,
 64.0,
 83.0,
 77.0,
 76.0,
 83.0,
 71.0,
 32.0,
 75.0,
 78.0,
 72.0,
 77.0,
 63.0,
 73.0,
 69.0,
 76.0,
 39.0,
 73.0,
 75.0,
 82.0,
 71.0,
 78.0,
 79.0,
 70.0,
 75.0,
 84.0,
 29.0,
 70.0,
 69.0,
 64.0,
 76.0,
 16.0,
 69.0,
 67.0,
 75.0,
 75.0,
 73.0,
 80.0,
 70.0,
 80.0,
 80.0,
 78.0,
 35.0,
 76.0,
 77.0,
 81.0,
 69.0,
 76.0,
 74.0,
 72.0,
 78.0,
 79.0,
 76.0,
 79.0,
 77.0,
 76.0,
 77.0,
 83.0,
 80.0,
 35.0,
 68.0,
 81.0,
 76.0,
 76.0,
 80.0,
 29.0,
 75.0,
 78.0,
 75.0,
 77.0,
 76.0,
 80.0,
 80.0,
 32.0,
 76.0,
 79.0,
 75.0,
 72.0,
 69.0,
 80.0,
 70.0,
 80.0,
 75.0,
 70.0,
 76.0,
 70.0,
 75.0,
 81.0,
 80.0,
 46.0,
 71.0,
 82.0,
 24.0,
 75.0,
 75.0,
 80.0,
 63.0,
 23.0,
 80.0,
 75.0,
 77.0,
 79.0,
 73.0,
 67.0,
 70.0,
 71.0,
 70.0,
 29.0,
 68.0,
 25.0,
 74.0,
 75.0,
 72.0,
 80.0,
 74.0,
 45.0,
 70.0,
 29.0,
 80.0,
 68.0,
 77.0,
 81.0,
 37.0,
 22.0,
 72.0,
 78.0,
 77.0,
 76.0,
 74.0,
 73.0,
 79.0,
 77.0,
 30.0,
 70.0,
 65.0,
 73.0,
 73.0,
 73.0,
 77.0,
 81.0,
 73.0,
 75.0,
 70.0,
 74.0,
 72.0,
 75.0,
 79.0,
 83.0,
 73.0,
 76.0,
 77.0,
 29.0,
 25.0,
 82.0,
 62.0,
 70.0,
 73.0,
 65.0,
 77.0,
 78.0,
 79.0,
 75.0,
 23.0,
 73.0,
 77.0,
 ...]

In [72]:
dfNew['Short Passing1'] = shpasList
dfNew

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,Wage(€),Release Clause(€),Hits1,ht(m)_bins,wt(kg)_bins,Wage(€)_bins,Value(€)_bins,Release Clause(€)_bins,Dribbling1,Short Passing1
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93.0,93.0,\n\n\n\nFC Barcelona,...,560000.0,138400000.0,771.0,"(1.6, 1.7]","(70, 80]","(550000.0, 600000.0]","(100000000.0, 150000000.0]","(100000000.0, 150000000.0]",96.0,91.0
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92.0,92.0,\n\n\n\nJuventus,...,220000.0,75900000.0,562.0,"(1.8, 1.9]","(80, 90]","(200000.0, 250000.0]","(50000000.0, 100000000.0]","(50000000.0, 100000000.0]",88.0,82.0
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91.0,93.0,\n\n\n\nAtlético Madrid,...,125000.0,159400000.0,150.0,"(1.8, 1.9]","(80, 90]","(100000.0, 150000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]",12.0,43.0
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91.0,91.0,\n\n\n\nManchester City,...,370000.0,161000000.0,207.0,"(1.8, 1.9]","(60, 70]","(350000.0, 400000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]",88.0,94.0
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91.0,91.0,\n\n\n\nParis Saint-Germain,...,270000.0,166500000.0,595.0,"(1.7, 1.8]","(60, 70]","(250000.0, 300000.0]","(100000000.0, 150000000.0]","(150000000.0, 200000000.0]",95.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47.0,55.0,\n\n\n\nWuhan Zall,...,1000.0,70000.0,nan,"(1.7, 1.8]","(60, 70]",NaN,NaN,NaN,27.0,26.0
19017,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47.0,67.0,\n\n\n\nOldham Athletic,...,500000.0,165000.0,nan,"(1.7, 1.8]","(60, 70]","(450000.0, 500000.0]",NaN,NaN,46.0,56.0
19018,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47.0,65.0,\n\n\n\nDerry City,...,500000.0,131000.0,nan,"(1.7, 1.8]","(70, 80]","(450000.0, 500000.0]",NaN,NaN,43.0,54.0
19019,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47.0,57.0,\n\n\n\nDalian YiFang FC,...,2000.0,88000.0,nan,"(1.7, 1.8]","(60, 70]",NaN,NaN,NaN,51.0,42.0
19020,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47.0,57.0,\n\n\n\nDalian YiFang FC,...,1000.0,79000.0,nan,"(1.8, 1.9]","(70, 80]",NaN,NaN,NaN,40.0,45.0

A. BONUS: Build a prediction model to predict the number of Hits of each payer

In [73]:
# removing unwanted columns

In [74]:
list(dfNew.columns)

['ID',
 'Name',
 'LongName',
 'photoUrl',
 'playerUrl',
 'Nationality',
 'Age',
 '↓OVA',
 'POT',
 'Club',
 'Contract',
 'Positions',
 'Height',
 'Weight',
 'Preferred Foot',
 'BOV',
 'Best Position',
 'Joined',
 'Loan Date End',
 'Value',
 'Wage',
 'Release Clause',
 'Attacking',
 'Crossing',
 'Finishing',
 'Heading Accuracy',
 'Short Passing',
 'Volleys',
 'Skill',
 'Dribbling',
 'Curve',
 'FK Accuracy',
 'Long Passing',
 'Ball Control',
 'Movement',
 'Acceleration',
 'Sprint Speed',
 'Agility',
 'Reactions',
 'Balance',
 'Power',
 'Shot Power',
 'Jumping',
 'Stamina',
 'Strength',
 'Long Shots',
 'Mentality',
 'Aggression',
 'Interceptions',
 'Positioning',
 'Vision',
 'Penalties',
 'Composure',
 'Defending',
 'Marking',
 'Standing Tackle',
 'Sliding Tackle',
 'Goalkeeping',
 'GK Diving',
 'GK Handling',
 'GK Kicking',
 'GK Positioning',
 'GK Reflexes',
 'Total Stats',
 'Base Stats',
 'W/F',
 'SM',
 'A/W',
 'D/W',
 'IR',
 'PAC',
 'SHO',
 'PAS',
 'DRI',
 'DEF',
 'PHY',
 'Hits',
 'PlayerName',
 'PlayerStatus',
 'RW',
 'CF',
 'CM',
 'CDM',
 'LWB',
 'GK',
 'RM',
 'RB',
 'CB',
 'CAM',
 'ST',
 'LW',
 'LM',
 'LB',
 'RWB',
 'W/F1',
 'SM1',
 'IR1',
 'wt(kg)',
 'ht(m)',
 'Value(€)',
 'Wage(€)',
 'Release Clause(€)',
 'Hits1',
 'ht(m)_bins',
 'wt(kg)_bins',
 'Wage(€)_bins',
 'Value(€)_bins',
 'Release Clause(€)_bins',
 'Dribbling1',
 'Short Passing1']

In [75]:
refCols = [
 'Age',
 '↓OVA',
 'POT',
 'Preferred Foot',
 'BOV',
 'Best Position',
 'Attacking',
 'Crossing',
 'Dribbling1',
 'Short Passing1',
 'Finishing',
 'Heading Accuracy',
 'Volleys',
 'Skill',
 'Curve',
 'FK Accuracy',
 'Long Passing',
 'Ball Control',
 'Movement',
 'Acceleration',
 'Sprint Speed',
 'Agility',
 'Reactions',
 'Balance',
 'Power',
 'Shot Power',
 'Jumping',
 'Stamina',
 'Strength',
 'Long Shots',
 'Mentality',
 'Aggression',
 'Interceptions',
 'Positioning',
 'Vision',
 'Penalties',
 'Composure',
 'Defending',
 'Marking',
 'Standing Tackle',
 'Sliding Tackle',
 'Goalkeeping',
 'GK Diving',
 'GK Handling',
 'GK Kicking',
 'GK Positioning',
 'GK Reflexes',
 'Total Stats',
 'Base Stats',
 'A/W',
 'D/W',
 'PAC',
 'SHO',
 'PAS',
 'DRI',
 'DEF',
 'PHY',
 'PlayerName',
 'PlayerStatus',
 'LB',
 'LW',
 'RM',
 'CF',
 'ST',
 'GK',
 'RW',
 'LM',
 'RWB',
 'LWB',
 'CAM',
 'CDM',
 'CB',
 'RB',
 'CM',
 'W/F1',
 'SM1',
 'IR1',
 'wt(kg)',
 'ht(m)',
 'Value(€)',
 'Wage(€)',
 'Release Clause(€)',
 'Hits1']

In [76]:
dfNew1=dfNew[refCols]
dfNew1

,Age,↓OVA,POT,Preferred Foot,BOV,Best Position,Attacking,Crossing,Dribbling1,Short Passing1,...,CM,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1
0,33,93.0,93.0,Left,93,RW,429.0,85.0,96.0,91.0,...,0,4,4,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0
1,35,92.0,92.0,Right,92,ST,437.0,84.0,88.0,82.0,...,0,4,5,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0
2,27,91.0,93.0,Right,91,GK,95.0,13.0,12.0,43.0,...,0,3,1,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0
3,29,91.0,91.0,Right,91,CAM,407.0,94.0,88.0,94.0,...,1,5,4,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0
4,28,91.0,91.0,Right,91,LW,408.0,85.0,95.0,87.0,...,0,5,5,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,21,47.0,55.0,Right,49,CB,145.0,23.0,27.0,26.0,...,0,2,2,1,66.0,1.78,100000.0,1000.0,70000.0,nan
19017,17,47.0,67.0,Right,51,CAM,211.0,38.0,46.0,56.0,...,1,2,2,1,65.0,1.75,130000.0,500000.0,165000.0,nan
19018,18,47.0,65.0,Right,49,CAM,200.0,30.0,43.0,54.0,...,1,2,2,1,74.0,1.79,120000.0,500000.0,131000.0,nan
19019,20,47.0,57.0,Right,48,ST,215.0,45.0,51.0,42.0,...,0,3,2,1,69.0,1.75,100000.0,2000.0,88000.0,nan
19020,21,47.0,57.0,Left,50,LB,163.0,40.0,40.0,45.0,...,0,3,2,1,75.0,1.88,100000.0,1000.0,79000.0,nan

In [77]:
 #Inspect all columns that are categorical for mis-labeling

In [78]:
dfNew1['Preferred Foot'].unique() #checking mis-labeling for Preferred Foot

array(['Left', 'Right'], dtype=object)

In [79]:
#Converting clean Preferred Foot categorical outcome to numeric

dfNew1['Preferred Foot'] = dfNew1['Preferred Foot'].replace(['Left','Right'], [0,1])

C:\Users\User\AppData\Local\Temp/ipykernel_14680/21504310.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfNew1['Preferred Foot'] = dfNew1['Preferred Foot'].replace(['Left','Right'], [0,1])

In [80]:
dfNew1['Best Position'].unique()

array(['RW', 'ST', 'GK', 'CAM', 'LW', 'CB', 'CDM', 'CF', 'CM', 'RB', 'LB',
       'LM', 'RM', 'LWB', 'RWB'], dtype=object)

In [81]:
#Converting clean Best Position categorical outcome to numeric

dfNew1['Best Position'] = dfNew1['Best Position'].replace(['RW', 'ST', 'GK', 'CAM', 'LW', 'CB', 'CDM', 'CF', 'CM', 'RB', 'LB',
       'LM', 'RM', 'LWB', 'RWB'], [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])

C:\Users\User\AppData\Local\Temp/ipykernel_14680/786935646.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfNew1['Best Position'] = dfNew1['Best Position'].replace(['RW', 'ST', 'GK', 'CAM', 'LW', 'CB', 'CDM', 'CF', 'CM', 'RB', 'LB',

In [82]:
dfNew1['A/W'].unique()# checking the uniqueness of A/W

array(['Medium', 'High', 'Low'], dtype=object)

In [83]:
# Converting A/W to numeric

dfNew1['A/W'] = dfNew1['A/W'].replace(['Medium','High','Low'], [1,2,0])

C:\Users\User\AppData\Local\Temp/ipykernel_14680/384833140.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfNew1['A/W'] = dfNew1['A/W'].replace(['Medium','High','Low'], [1,2,0])

In [84]:
dfNew1['D/W'].unique()# checking the uniqueness of D/W

array(['Low', 'Medium', 'High', nan], dtype=object)

In [85]:
# Converting D/W to numeric

dfNew1['D/W'] = dfNew1['D/W'].replace(['Low','Medium','High'], [0,1,2])

C:\Users\User\AppData\Local\Temp/ipykernel_14680/2777092262.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfNew1['D/W'] = dfNew1['D/W'].replace(['Low','Medium','High'], [0,1,2])

In [86]:
dfNew1['PlayerStatus'].unique()# checking the uniqueness of PlayerStatus

array(['Active', 'On Loan', 'Free'], dtype=object)

In [87]:
dfNew1['PlayerStatus'] = dfNew1['PlayerStatus'].replace(['Active','On Loan','Free'], [0,1,2])

C:\Users\User\AppData\Local\Temp/ipykernel_14680/2992839949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfNew1['PlayerStatus'] = dfNew1['PlayerStatus'].replace(['Active','On Loan','Free'], [0,1,2])

In [88]:
dfNew1['Hits1'].unique()# checking the uniqueness of Hits1

array([771.0, 562.0, 150.0, 207.0, 595.0, 248.0, 246.0, 120.0, 1600.0,
       130.0, 321.0, 189.0, 175.0, 96.0, 118.0, 216.0, 212.0, 154.0,
       205.0, 202.0, 339.0, 408.0, 103.0, 332.0, 86.0, 173.0, 161.0,
       396.0, 1100.0, 433.0, 242.0, 206.0, 177.0, 1500.0, 198.0, 459.0,
       117.0, 119.0, 209.0, 84.0, 187.0, 165.0, 203.0, 65.0, 336.0, 126.0,
       313.0, 124.0, 145.0, 538.0, 182.0, 101.0, 45.0, 377.0, 99.0, 194.0,
       403.0, 414.0, 593.0, 374.0, 245.0, 3200.0, 266.0, 299.0, 309.0,
       215.0, 265.0, 211.0, 112.0, 337.0, 70.0, 159.0, 688.0, 116.0, 63.0,
       144.0, 123.0, 71.0, 224.0, 113.0, 168.0, 61.0, 89.0, 137.0, 278.0,
       75.0, 148.0, 176.0, 197.0, 264.0, 214.0, 247.0, 402.0, 440.0,
       1700.0, 2300.0, 171.0, 320.0, 657.0, 87.0, 259.0, 200.0, 255.0,
       253.0, 196.0, 60.0, 97.0, 85.0, 169.0, 256.0, 132.0, 239.0, 166.0,
       121.0, 109.0, 32.0, 46.0, 122.0, 48.0, 527.0, 199.0, 282.0, 51.0,
       1900.0, 642.0, 155.0, 323.0, 288.0, 497.0, 509.0, 79.0, 49.0,
       270.0, 511.0, 80.0, 128.0, 115.0, 156.0, 204.0, 143.0, 140.0,
       152.0, 220.0, 134.0, 225.0, 94.0, 74.0, 135.0, 142.0, 50.0, 77.0,
       40.0, 107.0, 193.0, 179.0, 34.0, 64.0, 453.0, 57.0, 81.0, 28.0,
       78.0, 133.0, 43.0, 425.0, 88.0, 42.0, 36.0, 233.0, 376.0, 210.0,
       444.0, 100.0, 263.0, 98.0, 29.0, 160.0, 39.0, 257.0, 6.0, 310.0,
       138.0, 62.0, 293.0, 285.0, 362.0, 66.0, 69.0, 58.0, 21.0, 20.0,
       131.0, 38.0, 406.0, 68.0, 108.0, 110.0, 93.0, 512.0, 443.0, 306.0,
       352.0, 422.0, 585.0, 346.0, 178.0, 841.0, 76.0, 394.0, 72.0, 172.0,
       44.0, 407.0, 230.0, 367.0, 295.0, 157.0, 243.0, 56.0, 111.0, 326.0,
       679.0, 18.0, 92.0, 59.0, 25.0, 184.0, 53.0, 12.0, 90.0, 55.0, 73.0,
       11.0, 566.0, 180.0, 83.0, 262.0, 17.0, 26.0, 31.0, 280.0, 359.0,
       213.0, 297.0, 387.0, 480.0, 381.0, 677.0, 486.0, 8.0, 244.0, 129.0,
       388.0, 275.0, 319.0, 2000.0, 52.0, 91.0, 421.0, 153.0, 27.0, 41.0,
       222.0, 35.0, 102.0, 23.0, 30.0, 33.0, 146.0, 13.0, 19.0, 14.0,
       106.0, 276.0, 568.0, 353.0, 47.0, 478.0, 249.0, 254.0, 369.0,
       219.0, 565.0, 237.0, 227.0, 434.0, 375.0, 162.0, 605.0, 654.0, 3.0,
       7.0, 9.0, 104.0, 114.0, 186.0, 446.0, 756.0, 22.0, 139.0, 500.0,
       67.0, 147.0, 149.0, 16.0, 82.0, 54.0, 37.0, 15.0, 1300.0, 3000.0,
       952.0, 5.0, 749.0, 541.0, 330.0, 393.0, 517.0, 770.0, 409.0, 170.0,
       125.0, 283.0, 342.0, 363.0, 580.0, 105.0, 217.0, 24.0, 141.0, 10.0,
       427.0, 158.0, 426.0, 4.0, 666.0, 181.0, 324.0, 979.0, 1400.0,
       302.0, 751.0, 298.0, 411.0, 944.0, 2.0, 947.0, 292.0, 349.0, 621.0,
       1.0, 2800.0, 338.0, 287.0, 261.0, 218.0, 1800.0, 240.0, 279.0,
       229.0, 188.0, 315.0, 664.0, 613.0, 190.0, 706.0, 127.0, 462.0,
       386.0, 695.0, 491.0, 167.0, 281.0, 250.0, 307.0, 95.0, 231.0,
       174.0, 680.0, 633.0, 221.0, 348.0, 602.0, 183.0, 653.0, 195.0,
       164.0, 151.0, 258.0, 8400.0, 343.0, 419.0, 655.0, 136.0, 399.0,
       531.0, 357.0, 228.0, 385.0, 312.0, 340.0, 238.0, 487.0, 355.0,
       499.0, 4300.0, 296.0, 515.0, 943.0, 1200.0, 903.0, 335.0, 191.0,
       594.0, 267.0, 617.0, 516.0, 504.0, 331.0, 652.0, 410.0, 550.0,
       473.0, 442.0, 344.0, 208.0, 1000.0, 2500.0, 273.0, 485.0, 826.0,
       192.0, 405.0, 941.0, 477.0, 644.0, 303.0, 417.0, 6000.0, 'nan'],
      dtype=object)

In [89]:
# Inspect data for missing values

dfNew1.isna()

,Age,↓OVA,POT,Preferred Foot,BOV,Best Position,Attacking,Crossing,Dribbling1,Short Passing1,...,CM,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19017,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19018,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19019,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19020,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [90]:
dfNew1.isna().sum()

Age                  0
↓OVA                 2
POT                  1
Preferred Foot       0
BOV                  0
                    ..
ht(m)                0
Value(€)             0
Wage(€)              0
Release Clause(€)    0
Hits1                0
Length: 83, dtype: int64

In [91]:
df_musket = dfNew1.dropna() # dropping all missing values or rows with missing values

In [92]:
df_musket.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18915 entries, 0 to 19020
Data columns (total 83 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                18915 non-null  int64
 1   ↓OVA               18915 non-null  float64
 2   POT                18915 non-null  float64
 3   Preferred Foot     18915 non-null  int64
 4   BOV                18915 non-null  int64
 5   Best Position      18915 non-null  int64
 6   Attacking          18915 non-null  float64
 7   Crossing           18915 non-null  float64
 8   Dribbling1         18915 non-null  object
 9   Short Passing1     18915 non-null  object
 10  Finishing          18915 non-null  float64
 11  Heading Accuracy   18915 non-null  float64
 12  Volleys            18915 non-null  float64
 13  Skill              18915 non-null  float64
 14  Curve              18915 non-null  float64
 15  FK Accuracy        18915 non-null  float64
 16  Long Passing       18915 non-null  float64
 17  Ball Control       18915 non-null  float64
 18  Movement           18915 non-null  float64
 19  Acceleration       18915 non-null  float64
 20  Sprint Speed       18915 non-null  float64
 21  Agility            18915 non-null  float64
 22  Reactions          18915 non-null  float64
 23  Balance            18915 non-null  float64
 24  Power              18915 non-null  float64
 25  Shot Power         18915 non-null  float64
 26  Jumping            18915 non-null  float64
 27  Stamina            18915 non-null  float64
 28  Strength           18915 non-null  float64
 29  Long Shots         18915 non-null  float64
 30  Mentality          18915 non-null  float64
 31  Aggression         18915 non-null  int64
 32  Interceptions      18915 non-null  float64
 33  Positioning        18915 non-null  float64
 34  Vision             18915 non-null  int64
 35  Penalties          18915 non-null  float64
 36  Composure          18915 non-null  float64
 37  Defending          18915 non-null  float64
 38  Marking            18915 non-null  float64
 39  Standing Tackle    18915 non-null  float64
 40  Sliding Tackle     18915 non-null  float64
 41  Goalkeeping        18915 non-null  float64
 42  GK Diving          18915 non-null  float64
 43  GK Handling        18915 non-null  float64
 44  GK Kicking         18915 non-null  float64
 45  GK Positioning     18915 non-null  float64
 46  GK Reflexes        18915 non-null  int64
 47  Total Stats        18915 non-null  float64
 48  Base Stats         18915 non-null  int64
 49  A/W                18915 non-null  int64
 50  D/W                18915 non-null  float64
 51  PAC                18915 non-null  float64
 52  SHO                18915 non-null  float64
 53  PAS                18915 non-null  float64
 54  DRI                18915 non-null  float64
 55  DEF                18915 non-null  float64
 56  PHY                18915 non-null  float64
 57  PlayerName         18915 non-null  object
 58  PlayerStatus       18915 non-null  int64
 59  LB                 18915 non-null  int64
 60  LW                 18915 non-null  int64
 61  RM                 18915 non-null  int64
 62  CF                 18915 non-null  int64
 63  ST                 18915 non-null  int64
 64  GK                 18915 non-null  int64
 65  RW                 18915 non-null  int64
 66  LM                 18915 non-null  int64
 67  RWB                18915 non-null  int64
 68  LWB                18915 non-null  int64
 69  CAM                18915 non-null  int64
 70  CDM                18915 non-null  int64
 71  CB                 18915 non-null  int64
 72  RB                 18915 non-null  int64
 73  CM                 18915 non-null  int64
 74  W/F1               18915 non-null  int64
 75  SM1                18915 non-null  int64
 76  IR1                18915 non-null  int64
 77  wt(kg)             18915 non-null  float64
 78  ht(m)              18915 non-null  float64
 79  Value(€)           18915 non-null  float64
 80  Wage(€)            18915 non-null  float64
 81  Release Clause(€)  18915 non-null  float64
 82  Hits1              18915 non-null  object
dtypes: float64(51), int64(28), object(4)
memory usage: 12.1+ MB

In [93]:
dribList = [] # Converting dribbling to float
for val in df_musket.Dribbling1.values:
    val = float(val)
    dribList.append(val)
dribList

[96.0,
 88.0,
 12.0,
 88.0,
 95.0,
 85.0,
 90.0,
 27.0,
 92.0,
 21.0,
 70.0,
 91.0,
 69.0,
 13.0,
 30.0,
 87.0,
 65.0,
 88.0,
 90.0,
 79.0,
 83.0,
 91.0,
 23.0,
 80.0,
 18.0,
 69.0,
 93.0,
 80.0,
 87.0,
 92.0,
 77.0,
 92.0,
 80.0,
 63.0,
 85.0,
 76.0,
 88.0,
 90.0,
 16.0,
 59.0,
 81.0,
 80.0,
 11.0,
 88.0,
 85.0,
 84.0,
 10.0,
 83.0,
 75.0,
 18.0,
 78.0,
 55.0,
 90.0,
 87.0,
 77.0,
 63.0,
 69.0,
 15.0,
 86.0,
 87.0,
 81.0,
 78.0,
 76.0,
 86.0,
 85.0,
 86.0,
 66.0,
 67.0,
 87.0,
 28.0,
 87.0,
 88.0,
 83.0,
 57.0,
 64.0,
 90.0,
 82.0,
 84.0,
 82.0,
 76.0,
 87.0,
 90.0,
 62.0,
 67.0,
 80.0,
 16.0,
 78.0,
 80.0,
 90.0,
 79.0,
 77.0,
 19.0,
 69.0,
 88.0,
 86.0,
 53.0,
 85.0,
 86.0,
 85.0,
 72.0,
 50.0,
 26.0,
 88.0,
 85.0,
 87.0,
 75.0,
 82.0,
 88.0,
 84.0,
 87.0,
 43.0,
 87.0,
 89.0,
 57.0,
 82.0,
 81.0,
 84.0,
 87.0,
 73.0,
 84.0,
 81.0,
 78.0,
 12.0,
 88.0,
 82.0,
 83.0,
 92.0,
 77.0,
 76.0,
 89.0,
 87.0,
 92.0,
 66.0,
 76.0,
 77.0,
 67.0,
 15.0,
 12.0,
 79.0,
 20.0,
 75.0,
 84.0,
 84.0,
 80.0,
 89.0,
 86.0,
 85.0,
 82.0,
 78.0,
 88.0,
 87.0,
 87.0,
 67.0,
 86.0,
 76.0,
 18.0,
 19.0,
 65.0,
 79.0,
 81.0,
 86.0,
 88.0,
 88.0,
 14.0,
 85.0,
 79.0,
 84.0,
 85.0,
 68.0,
 83.0,
 79.0,
 64.0,
 79.0,
 84.0,
 79.0,
 79.0,
 88.0,
 82.0,
 71.0,
 84.0,
 76.0,
 74.0,
 78.0,
 15.0,
 79.0,
 69.0,
 22.0,
 84.0,
 90.0,
 54.0,
 10.0,
 87.0,
 89.0,
 81.0,
 14.0,
 65.0,
 84.0,
 10.0,
 82.0,
 72.0,
 82.0,
 76.0,
 76.0,
 83.0,
 89.0,
 80.0,
 83.0,
 70.0,
 19.0,
 80.0,
 84.0,
 82.0,
 80.0,
 82.0,
 65.0,
 50.0,
 82.0,
 12.0,
 56.0,
 85.0,
 82.0,
 85.0,
 79.0,
 76.0,
 78.0,
 84.0,
 86.0,
 78.0,
 86.0,
 22.0,
 84.0,
 10.0,
 82.0,
 61.0,
 13.0,
 71.0,
 82.0,
 87.0,
 14.0,
 85.0,
 14.0,
 9.0,
 71.0,
 75.0,
 15.0,
 81.0,
 12.0,
 80.0,
 19.0,
 19.0,
 24.0,
 86.0,
 75.0,
 83.0,
 60.0,
 83.0,
 86.0,
 19.0,
 15.0,
 71.0,
 26.0,
 81.0,
 59.0,
 82.0,
 86.0,
 78.0,
 88.0,
 78.0,
 25.0,
 64.0,
 79.0,
 85.0,
 82.0,
 79.0,
 57.0,
 87.0,
 82.0,
 83.0,
 81.0,
 84.0,
 76.0,
 85.0,
 84.0,
 78.0,
 84.0,
 77.0,
 75.0,
 77.0,
 60.0,
 78.0,
 86.0,
 74.0,
 8.0,
 65.0,
 60.0,
 78.0,
 78.0,
 78.0,
 83.0,
 81.0,
 87.0,
 87.0,
 77.0,
 81.0,
 63.0,
 76.0,
 83.0,
 88.0,
 15.0,
 84.0,
 13.0,
 75.0,
 78.0,
 82.0,
 83.0,
 71.0,
 68.0,
 74.0,
 17.0,
 84.0,
 64.0,
 85.0,
 13.0,
 60.0,
 76.0,
 14.0,
 47.0,
 82.0,
 74.0,
 77.0,
 79.0,
 87.0,
 74.0,
 79.0,
 78.0,
 81.0,
 12.0,
 84.0,
 75.0,
 74.0,
 14.0,
 83.0,
 58.0,
 90.0,
 85.0,
 78.0,
 84.0,
 86.0,
 87.0,
 82.0,
 80.0,
 61.0,
 87.0,
 54.0,
 81.0,
 12.0,
 14.0,
 10.0,
 87.0,
 58.0,
 16.0,
 76.0,
 60.0,
 88.0,
 72.0,
 19.0,
 80.0,
 9.0,
 77.0,
 75.0,
 82.0,
 56.0,
 79.0,
 88.0,
 75.0,
 86.0,
 86.0,
 13.0,
 65.0,
 70.0,
 12.0,
 79.0,
 69.0,
 79.0,
 80.0,
 47.0,
 85.0,
 79.0,
 75.0,
 78.0,
 53.0,
 73.0,
 19.0,
 83.0,
 83.0,
 91.0,
 14.0,
 84.0,
 83.0,
 79.0,
 86.0,
 71.0,
 81.0,
 71.0,
 82.0,
 82.0,
 76.0,
 16.0,
 85.0,
 76.0,
 79.0,
 85.0,
 72.0,
 86.0,
 78.0,
 19.0,
 81.0,
 81.0,
 82.0,
 64.0,
 85.0,
 84.0,
 84.0,
 53.0,
 85.0,
 74.0,
 83.0,
 80.0,
 75.0,
 59.0,
 11.0,
 54.0,
 87.0,
 85.0,
 80.0,
 63.0,
 69.0,
 76.0,
 77.0,
 74.0,
 61.0,
 77.0,
 13.0,
 75.0,
 78.0,
 73.0,
 83.0,
 68.0,
 76.0,
 79.0,
 70.0,
 77.0,
 70.0,
 75.0,
 76.0,
 85.0,
 66.0,
 78.0,
 67.0,
 73.0,
 12.0,
 58.0,
 46.0,
 75.0,
 68.0,
 80.0,
 12.0,
 68.0,
 78.0,
 68.0,
 83.0,
 16.0,
 80.0,
 71.0,
 85.0,
 50.0,
 78.0,
 76.0,
 88.0,
 80.0,
 85.0,
 73.0,
 89.0,
 86.0,
 79.0,
 18.0,
 77.0,
 78.0,
 76.0,
 78.0,
 77.0,
 84.0,
 8.0,
 74.0,
 83.0,
 78.0,
 82.0,
 77.0,
 77.0,
 81.0,
 71.0,
 81.0,
 83.0,
 67.0,
 68.0,
 78.0,
 76.0,
 70.0,
 78.0,
 70.0,
 81.0,
 82.0,
 18.0,
 72.0,
 75.0,
 68.0,
 76.0,
 68.0,
 85.0,
 80.0,
 78.0,
 79.0,
 77.0,
 79.0,
 64.0,
 74.0,
 79.0,
 84.0,
 76.0,
 60.0,
 59.0,
 79.0,
 78.0,
 73.0,
 76.0,
 74.0,
 77.0,
 76.0,
 82.0,
 67.0,
 60.0,
 80.0,
 74.0,
 76.0,
 79.0,
 81.0,
 92.0,
 72.0,
 62.0,
 81.0,
 75.0,
 66.0,
 81.0,
 66.0,
 82.0,
 55.0,
 73.0,
 78.0,
 18.0,
 81.0,
 84.0,
 79.0,
 13.0,
 85.0,
 83.0,
 70.0,
 51.0,
 18.0,
 69.0,
 78.0,
 85.0,
 12.0,
 79.0,
 78.0,
 78.0,
 64.0,
 62.0,
 75.0,
 52.0,
 78.0,
 78.0,
 85.0,
 49.0,
 15.0,
 81.0,
 78.0,
 78.0,
 82.0,
 80.0,
 79.0,
 86.0,
 77.0,
 65.0,
 12.0,
 82.0,
 19.0,
 81.0,
 78.0,
 74.0,
 79.0,
 84.0,
 76.0,
 67.0,
 70.0,
 62.0,
 84.0,
 62.0,
 78.0,
 79.0,
 75.0,
 59.0,
 59.0,
 69.0,
 77.0,
 80.0,
 70.0,
 13.0,
 74.0,
 83.0,
 78.0,
 87.0,
 75.0,
 83.0,
 80.0,
 63.0,
 75.0,
 67.0,
 77.0,
 73.0,
 69.0,
 77.0,
 80.0,
 80.0,
 70.0,
 23.0,
 74.0,
 72.0,
 58.0,
 81.0,
 12.0,
 62.0,
 14.0,
 13.0,
 58.0,
 10.0,
 10.0,
 84.0,
 78.0,
 78.0,
 84.0,
 82.0,
 72.0,
 85.0,
 44.0,
 78.0,
 76.0,
 72.0,
 61.0,
 16.0,
 30.0,
 73.0,
 81.0,
 78.0,
 84.0,
 64.0,
 80.0,
 35.0,
 68.0,
 85.0,
 79.0,
 69.0,
 82.0,
 79.0,
 81.0,
 14.0,
 84.0,
 69.0,
 83.0,
 48.0,
 82.0,
 49.0,
 82.0,
 72.0,
 69.0,
 82.0,
 83.0,
 82.0,
 68.0,
 83.0,
 72.0,
 78.0,
 81.0,
 80.0,
 76.0,
 51.0,
 44.0,
 75.0,
 71.0,
 79.0,
 77.0,
 68.0,
 76.0,
 78.0,
 86.0,
 75.0,
 81.0,
 75.0,
 16.0,
 81.0,
 16.0,
 81.0,
 76.0,
 75.0,
 78.0,
 13.0,
 79.0,
 77.0,
 71.0,
 75.0,
 67.0,
 79.0,
 77.0,
 62.0,
 62.0,
 79.0,
 85.0,
 82.0,
 55.0,
 73.0,
 77.0,
 77.0,
 76.0,
 74.0,
 49.0,
 79.0,
 76.0,
 84.0,
 77.0,
 72.0,
 62.0,
 79.0,
 65.0,
 75.0,
 82.0,
 75.0,
 72.0,
 79.0,
 79.0,
 76.0,
 75.0,
 82.0,
 83.0,
 13.0,
 75.0,
 72.0,
 69.0,
 64.0,
 68.0,
 76.0,
 76.0,
 75.0,
 64.0,
 11.0,
 82.0,
 81.0,
 76.0,
 74.0,
 79.0,
 58.0,
 76.0,
 84.0,
 73.0,
 82.0,
 83.0,
 55.0,
 78.0,
 71.0,
 16.0,
 13.0,
 83.0,
 55.0,
 80.0,
 75.0,
 78.0,
 81.0,
 73.0,
 65.0,
 58.0,
 16.0,
 77.0,
 71.0,
 55.0,
 65.0,
 79.0,
 53.0,
 83.0,
 80.0,
 82.0,
 75.0,
 65.0,
 17.0,
 75.0,
 81.0,
 73.0,
 46.0,
 66.0,
 72.0,
 76.0,
 16.0,
 80.0,
 76.0,
 70.0,
 66.0,
 83.0,
 82.0,
 75.0,
 79.0,
 76.0,
 13.0,
 78.0,
 54.0,
 74.0,
 19.0,
 77.0,
 66.0,
 81.0,
 53.0,
 75.0,
 70.0,
 77.0,
 83.0,
 80.0,
 80.0,
 24.0,
 79.0,
 82.0,
 65.0,
 63.0,
 66.0,
 63.0,
 73.0,
 77.0,
 81.0,
 80.0,
 74.0,
 78.0,
 72.0,
 80.0,
 73.0,
 14.0,
 58.0,
 79.0,
 82.0,
 80.0,
 17.0,
 77.0,
 82.0,
 76.0,
 71.0,
 77.0,
 74.0,
 78.0,
 14.0,
 76.0,
 78.0,
 67.0,
 75.0,
 39.0,
 85.0,
 85.0,
 74.0,
 79.0,
 85.0,
 81.0,
 72.0,
 75.0,
 77.0,
 67.0,
 29.0,
 71.0,
 80.0,
 18.0,
 78.0,
 72.0,
 62.0,
 40.0,
 14.0,
 76.0,
 82.0,
 78.0,
 73.0,
 70.0,
 85.0,
 61.0,
 82.0,
 79.0,
 20.0,
 78.0,
 15.0,
 68.0,
 75.0,
 69.0,
 80.0,
 81.0,
 27.0,
 84.0,
 19.0,
 79.0,
 61.0,
 80.0,
 66.0,
 15.0,
 18.0,
 72.0,
 81.0,
 74.0,
 73.0,
 78.0,
 70.0,
 71.0,
 77.0,
 20.0,
 59.0,
 54.0,
 76.0,
 79.0,
 69.0,
 64.0,
 82.0,
 42.0,
 72.0,
 62.0,
 73.0,
 82.0,
 65.0,
 80.0,
 81.0,
 71.0,
 51.0,
 86.0,
 10.0,
 16.0,
 83.0,
 45.0,
 77.0,
 76.0,
 83.0,
 74.0,
 74.0,
 80.0,
 71.0,
 16.0,
 72.0,
 77.0,
 85.0,
 62.0,
 73.0,
 80.0,
 77.0,
 20.0,
 82.0,
 69.0,
 70.0,
 84.0,
 76.0,
 79.0,
 79.0,
 45.0,
 74.0,
 78.0,
 56.0,
 80.0,
 82.0,
 56.0,
 71.0,
 17.0,
 83.0,
 73.0,
 73.0,
 84.0,
 77.0,
 81.0,
 79.0,
 66.0,
 83.0,
 85.0,
 78.0,
 77.0,
 74.0,
 14.0,
 44.0,
 75.0,
 16.0,
 87.0,
 71.0,
 75.0,
 15.0,
 79.0,
 76.0,
 57.0,
 ...]

In [94]:
df_musket['Dribbling'] = dribList
df_musket

C:\Users\User\AppData\Local\Temp/ipykernel_14680/2610424009.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_musket['Dribbling'] = dribList

,Age,↓OVA,POT,Preferred Foot,BOV,Best Position,Attacking,Crossing,Dribbling1,Short Passing1,...,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1,Dribbling
0,33,93.0,93.0,0,93,0,429.0,85.0,96.0,91.0,...,4,4,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0,96.0
1,35,92.0,92.0,1,92,1,437.0,84.0,88.0,82.0,...,4,5,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0,88.0
2,27,91.0,93.0,1,91,2,95.0,13.0,12.0,43.0,...,3,1,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0,12.0
3,29,91.0,91.0,1,91,3,407.0,94.0,88.0,94.0,...,5,4,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0,88.0
4,28,91.0,91.0,1,91,4,408.0,85.0,95.0,87.0,...,5,5,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,21,47.0,55.0,1,49,5,145.0,23.0,27.0,26.0,...,2,2,1,66.0,1.78,100000.0,1000.0,70000.0,nan,27.0
19017,17,47.0,67.0,1,51,3,211.0,38.0,46.0,56.0,...,2,2,1,65.0,1.75,130000.0,500000.0,165000.0,nan,46.0
19018,18,47.0,65.0,1,49,3,200.0,30.0,43.0,54.0,...,2,2,1,74.0,1.79,120000.0,500000.0,131000.0,nan,43.0
19019,20,47.0,57.0,1,48,1,215.0,45.0,51.0,42.0,...,3,2,1,69.0,1.75,100000.0,2000.0,88000.0,nan,51.0
19020,21,47.0,57.0,0,50,10,163.0,40.0,40.0,45.0,...,3,2,1,75.0,1.88,100000.0,1000.0,79000.0,nan,40.0

In [95]:
shpasList = [] # Converting Short Passing to float
for val in df_musket['Short Passing1'].values:
    val = float(val)
    shpasList.append(val)
shpasList

[91.0,
 82.0,
 43.0,
 94.0,
 87.0,
 84.0,
 84.0,
 45.0,
 83.0,
 61.0,
 79.0,
 85.0,
 84.0,
 33.0,
 55.0,
 86.0,
 82.0,
 83.0,
 84.0,
 85.0,
 87.0,
 87.0,
 57.0,
 81.0,
 42.0,
 74.0,
 85.0,
 93.0,
 84.0,
 88.0,
 85.0,
 86.0,
 82.0,
 82.0,
 88.0,
 85.0,
 83.0,
 87.0,
 30.0,
 65.0,
 89.0,
 77.0,
 32.0,
 83.0,
 91.0,
 83.0,
 50.0,
 80.0,
 84.0,
 50.0,
 83.0,
 78.0,
 90.0,
 86.0,
 69.0,
 81.0,
 82.0,
 40.0,
 92.0,
 86.0,
 84.0,
 86.0,
 85.0,
 85.0,
 81.0,
 84.0,
 75.0,
 73.0,
 81.0,
 34.0,
 79.0,
 81.0,
 86.0,
 78.0,
 82.0,
 80.0,
 83.0,
 78.0,
 92.0,
 76.0,
 90.0,
 83.0,
 79.0,
 80.0,
 87.0,
 50.0,
 79.0,
 81.0,
 89.0,
 78.0,
 90.0,
 35.0,
 77.0,
 82.0,
 90.0,
 79.0,
 88.0,
 90.0,
 85.0,
 79.0,
 70.0,
 33.0,
 84.0,
 81.0,
 78.0,
 74.0,
 83.0,
 78.0,
 81.0,
 88.0,
 78.0,
 87.0,
 80.0,
 73.0,
 84.0,
 85.0,
 87.0,
 82.0,
 78.0,
 81.0,
 83.0,
 81.0,
 37.0,
 86.0,
 80.0,
 85.0,
 84.0,
 85.0,
 81.0,
 79.0,
 79.0,
 83.0,
 73.0,
 86.0,
 82.0,
 78.0,
 23.0,
 44.0,
 90.0,
 34.0,
 75.0,
 81.0,
 81.0,
 80.0,
 78.0,
 82.0,
 83.0,
 74.0,
 83.0,
 84.0,
 81.0,
 84.0,
 78.0,
 83.0,
 82.0,
 38.0,
 48.0,
 76.0,
 85.0,
 79.0,
 77.0,
 77.0,
 74.0,
 26.0,
 75.0,
 82.0,
 83.0,
 81.0,
 75.0,
 82.0,
 83.0,
 78.0,
 89.0,
 83.0,
 83.0,
 75.0,
 90.0,
 76.0,
 83.0,
 85.0,
 80.0,
 80.0,
 84.0,
 32.0,
 85.0,
 77.0,
 38.0,
 79.0,
 75.0,
 60.0,
 30.0,
 84.0,
 82.0,
 86.0,
 35.0,
 75.0,
 88.0,
 25.0,
 82.0,
 82.0,
 84.0,
 81.0,
 77.0,
 85.0,
 81.0,
 80.0,
 85.0,
 77.0,
 46.0,
 78.0,
 81.0,
 87.0,
 75.0,
 85.0,
 79.0,
 75.0,
 83.0,
 28.0,
 74.0,
 83.0,
 84.0,
 74.0,
 84.0,
 86.0,
 80.0,
 81.0,
 76.0,
 79.0,
 79.0,
 36.0,
 80.0,
 51.0,
 84.0,
 78.0,
 28.0,
 77.0,
 84.0,
 77.0,
 32.0,
 81.0,
 17.0,
 18.0,
 78.0,
 84.0,
 32.0,
 81.0,
 48.0,
 82.0,
 36.0,
 33.0,
 37.0,
 83.0,
 83.0,
 78.0,
 80.0,
 83.0,
 78.0,
 30.0,
 39.0,
 78.0,
 37.0,
 84.0,
 74.0,
 88.0,
 84.0,
 85.0,
 80.0,
 82.0,
 44.0,
 77.0,
 79.0,
 85.0,
 77.0,
 81.0,
 73.0,
 79.0,
 80.0,
 77.0,
 76.0,
 74.0,
 69.0,
 77.0,
 77.0,
 71.0,
 85.0,
 78.0,
 73.0,
 81.0,
 67.0,
 76.0,
 77.0,
 80.0,
 40.0,
 76.0,
 79.0,
 80.0,
 78.0,
 84.0,
 79.0,
 84.0,
 85.0,
 75.0,
 80.0,
 74.0,
 74.0,
 76.0,
 82.0,
 81.0,
 26.0,
 81.0,
 27.0,
 72.0,
 84.0,
 80.0,
 77.0,
 78.0,
 78.0,
 76.0,
 42.0,
 80.0,
 72.0,
 84.0,
 26.0,
 75.0,
 66.0,
 55.0,
 71.0,
 78.0,
 75.0,
 76.0,
 80.0,
 79.0,
 78.0,
 81.0,
 78.0,
 82.0,
 50.0,
 83.0,
 80.0,
 74.0,
 37.0,
 81.0,
 78.0,
 81.0,
 90.0,
 83.0,
 85.0,
 76.0,
 80.0,
 83.0,
 83.0,
 77.0,
 77.0,
 75.0,
 84.0,
 33.0,
 20.0,
 31.0,
 83.0,
 73.0,
 37.0,
 75.0,
 67.0,
 72.0,
 73.0,
 46.0,
 80.0,
 18.0,
 78.0,
 78.0,
 79.0,
 74.0,
 80.0,
 84.0,
 79.0,
 78.0,
 82.0,
 32.0,
 76.0,
 70.0,
 29.0,
 81.0,
 80.0,
 78.0,
 73.0,
 66.0,
 74.0,
 83.0,
 69.0,
 73.0,
 73.0,
 73.0,
 34.0,
 82.0,
 81.0,
 76.0,
 28.0,
 72.0,
 82.0,
 83.0,
 77.0,
 74.0,
 73.0,
 79.0,
 79.0,
 83.0,
 82.0,
 31.0,
 84.0,
 81.0,
 79.0,
 81.0,
 81.0,
 79.0,
 68.0,
 37.0,
 78.0,
 82.0,
 77.0,
 69.0,
 82.0,
 83.0,
 84.0,
 72.0,
 80.0,
 76.0,
 81.0,
 84.0,
 75.0,
 78.0,
 17.0,
 70.0,
 77.0,
 80.0,
 75.0,
 77.0,
 80.0,
 77.0,
 77.0,
 78.0,
 74.0,
 75.0,
 40.0,
 78.0,
 81.0,
 76.0,
 80.0,
 78.0,
 78.0,
 74.0,
 79.0,
 85.0,
 79.0,
 80.0,
 77.0,
 78.0,
 78.0,
 82.0,
 83.0,
 77.0,
 34.0,
 71.0,
 78.0,
 65.0,
 77.0,
 80.0,
 44.0,
 75.0,
 82.0,
 72.0,
 84.0,
 39.0,
 82.0,
 78.0,
 76.0,
 67.0,
 75.0,
 80.0,
 80.0,
 83.0,
 81.0,
 79.0,
 85.0,
 80.0,
 79.0,
 11.0,
 80.0,
 71.0,
 76.0,
 81.0,
 68.0,
 73.0,
 26.0,
 74.0,
 75.0,
 82.0,
 77.0,
 82.0,
 80.0,
 83.0,
 72.0,
 78.0,
 73.0,
 79.0,
 79.0,
 81.0,
 77.0,
 82.0,
 72.0,
 67.0,
 82.0,
 74.0,
 11.0,
 78.0,
 78.0,
 75.0,
 76.0,
 75.0,
 76.0,
 69.0,
 79.0,
 71.0,
 86.0,
 65.0,
 65.0,
 78.0,
 81.0,
 79.0,
 76.0,
 67.0,
 78.0,
 82.0,
 76.0,
 72.0,
 81.0,
 77.0,
 78.0,
 70.0,
 80.0,
 73.0,
 78.0,
 72.0,
 86.0,
 81.0,
 77.0,
 84.0,
 72.0,
 84.0,
 64.0,
 77.0,
 72.0,
 80.0,
 81.0,
 79.0,
 77.0,
 73.0,
 77.0,
 83.0,
 31.0,
 77.0,
 85.0,
 80.0,
 20.0,
 75.0,
 82.0,
 81.0,
 70.0,
 25.0,
 77.0,
 73.0,
 83.0,
 27.0,
 76.0,
 82.0,
 81.0,
 80.0,
 80.0,
 85.0,
 69.0,
 75.0,
 75.0,
 73.0,
 73.0,
 26.0,
 80.0,
 85.0,
 75.0,
 79.0,
 79.0,
 77.0,
 85.0,
 85.0,
 81.0,
 28.0,
 76.0,
 38.0,
 85.0,
 75.0,
 79.0,
 78.0,
 80.0,
 74.0,
 82.0,
 79.0,
 81.0,
 79.0,
 72.0,
 82.0,
 77.0,
 78.0,
 65.0,
 62.0,
 82.0,
 68.0,
 79.0,
 nan,
 41.0,
 77.0,
 75.0,
 83.0,
 80.0,
 78.0,
 82.0,
 78.0,
 78.0,
 80.0,
 68.0,
 77.0,
 81.0,
 75.0,
 72.0,
 84.0,
 82.0,
 84.0,
 43.0,
 79.0,
 69.0,
 63.0,
 81.0,
 36.0,
 76.0,
 36.0,
 35.0,
 79.0,
 31.0,
 19.0,
 nan,
 78.0,
 78.0,
 73.0,
 74.0,
 75.0,
 71.0,
 68.0,
 83.0,
 76.0,
 77.0,
 80.0,
 44.0,
 40.0,
 78.0,
 76.0,
 74.0,
 75.0,
 77.0,
 71.0,
 75.0,
 81.0,
 74.0,
 80.0,
 75.0,
 79.0,
 83.0,
 79.0,
 54.0,
 76.0,
 66.0,
 72.0,
 78.0,
 78.0,
 73.0,
 69.0,
 69.0,
 75.0,
 77.0,
 79.0,
 79.0,
 75.0,
 69.0,
 69.0,
 85.0,
 78.0,
 85.0,
 76.0,
 71.0,
 68.0,
 73.0,
 77.0,
 80.0,
 76.0,
 77.0,
 75.0,
 85.0,
 74.0,
 73.0,
 75.0,
 78.0,
 29.0,
 72.0,
 28.0,
 70.0,
 75.0,
 64.0,
 69.0,
 32.0,
 78.0,
 77.0,
 68.0,
 79.0,
 77.0,
 72.0,
 72.0,
 74.0,
 63.0,
 75.0,
 72.0,
 74.0,
 70.0,
 70.0,
 84.0,
 75.0,
 74.0,
 80.0,
 73.0,
 79.0,
 80.0,
 84.0,
 81.0,
 80.0,
 71.0,
 78.0,
 64.0,
 78.0,
 76.0,
 74.0,
 75.0,
 77.0,
 74.0,
 75.0,
 67.0,
 63.0,
 82.0,
 31.0,
 78.0,
 77.0,
 66.0,
 72.0,
 79.0,
 81.0,
 77.0,
 73.0,
 70.0,
 32.0,
 75.0,
 76.0,
 78.0,
 74.0,
 79.0,
 80.0,
 82.0,
 75.0,
 71.0,
 79.0,
 76.0,
 72.0,
 62.0,
 74.0,
 38.0,
 45.0,
 77.0,
 67.0,
 81.0,
 76.0,
 83.0,
 74.0,
 69.0,
 75.0,
 65.0,
 36.0,
 79.0,
 80.0,
 69.0,
 75.0,
 77.0,
 64.0,
 83.0,
 77.0,
 76.0,
 83.0,
 71.0,
 32.0,
 75.0,
 72.0,
 77.0,
 63.0,
 73.0,
 69.0,
 76.0,
 39.0,
 73.0,
 75.0,
 82.0,
 71.0,
 78.0,
 79.0,
 70.0,
 75.0,
 84.0,
 29.0,
 69.0,
 64.0,
 76.0,
 16.0,
 69.0,
 67.0,
 75.0,
 75.0,
 73.0,
 80.0,
 70.0,
 80.0,
 80.0,
 78.0,
 35.0,
 76.0,
 77.0,
 69.0,
 76.0,
 74.0,
 72.0,
 78.0,
 79.0,
 76.0,
 79.0,
 77.0,
 76.0,
 77.0,
 83.0,
 80.0,
 35.0,
 68.0,
 81.0,
 76.0,
 80.0,
 29.0,
 75.0,
 78.0,
 75.0,
 77.0,
 76.0,
 80.0,
 80.0,
 32.0,
 76.0,
 79.0,
 75.0,
 72.0,
 69.0,
 80.0,
 70.0,
 80.0,
 75.0,
 70.0,
 76.0,
 70.0,
 75.0,
 81.0,
 80.0,
 46.0,
 71.0,
 82.0,
 24.0,
 75.0,
 75.0,
 80.0,
 63.0,
 23.0,
 80.0,
 75.0,
 77.0,
 79.0,
 73.0,
 67.0,
 70.0,
 71.0,
 70.0,
 29.0,
 68.0,
 25.0,
 74.0,
 75.0,
 72.0,
 80.0,
 74.0,
 45.0,
 70.0,
 29.0,
 80.0,
 68.0,
 77.0,
 81.0,
 37.0,
 22.0,
 72.0,
 78.0,
 77.0,
 76.0,
 74.0,
 73.0,
 79.0,
 77.0,
 30.0,
 70.0,
 65.0,
 73.0,
 73.0,
 73.0,
 77.0,
 81.0,
 73.0,
 75.0,
 70.0,
 74.0,
 72.0,
 75.0,
 79.0,
 83.0,
 73.0,
 76.0,
 77.0,
 29.0,
 25.0,
 82.0,
 62.0,
 70.0,
 73.0,
 65.0,
 77.0,
 78.0,
 79.0,
 75.0,
 23.0,
 73.0,
 77.0,
 73.0,
 75.0,
 83.0,
 82.0,
 85.0,
 49.0,
 78.0,
 65.0,
 68.0,
 73.0,
 80.0,
 73.0,
 72.0,
 67.0,
 69.0,
 71.0,
 60.0,
 75.0,
 73.0,
 75.0,
 70.0,
 33.0,
 81.0,
 80.0,
 77.0,
 80.0,
 77.0,
 74.0,
 69.0,
 74.0,
 80.0,
 74.0,
 76.0,
 79.0,
 76.0,
 nan,
 64.0,
 68.0,
 26.0,
 69.0,
 80.0,
 76.0,
 27.0,
 76.0,
 73.0,
 77.0,
 ...]

In [96]:
df_musket['Short Passing'] = shpasList
df_musket

C:\Users\User\AppData\Local\Temp/ipykernel_14680/231938227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_musket['Short Passing'] = shpasList

,Age,↓OVA,POT,Preferred Foot,BOV,Best Position,Attacking,Crossing,Dribbling1,Short Passing1,...,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1,Dribbling,Short Passing
0,33,93.0,93.0,0,93,0,429.0,85.0,96.0,91.0,...,4,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0,96.0,91.0
1,35,92.0,92.0,1,92,1,437.0,84.0,88.0,82.0,...,5,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0,88.0,82.0
2,27,91.0,93.0,1,91,2,95.0,13.0,12.0,43.0,...,1,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0,12.0,43.0
3,29,91.0,91.0,1,91,3,407.0,94.0,88.0,94.0,...,4,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0,88.0,94.0
4,28,91.0,91.0,1,91,4,408.0,85.0,95.0,87.0,...,5,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0,95.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,21,47.0,55.0,1,49,5,145.0,23.0,27.0,26.0,...,2,1,66.0,1.78,100000.0,1000.0,70000.0,nan,27.0,26.0
19017,17,47.0,67.0,1,51,3,211.0,38.0,46.0,56.0,...,2,1,65.0,1.75,130000.0,500000.0,165000.0,nan,46.0,56.0
19018,18,47.0,65.0,1,49,3,200.0,30.0,43.0,54.0,...,2,1,74.0,1.79,120000.0,500000.0,131000.0,nan,43.0,54.0
19019,20,47.0,57.0,1,48,1,215.0,45.0,51.0,42.0,...,2,1,69.0,1.75,100000.0,2000.0,88000.0,nan,51.0,42.0
19020,21,47.0,57.0,0,50,10,163.0,40.0,40.0,45.0,...,2,1,75.0,1.88,100000.0,1000.0,79000.0,nan,40.0,45.0

In [97]:
hitList = [] # Converting Hits to float
for val in df_musket.Hits1.values:
    val =float(val)
    hitList.append(val)
hitList

[771.0,
 562.0,
 150.0,
 207.0,
 595.0,
 248.0,
 246.0,
 120.0,
 1600.0,
 130.0,
 321.0,
 189.0,
 175.0,
 96.0,
 118.0,
 216.0,
 212.0,
 154.0,
 205.0,
 202.0,
 339.0,
 408.0,
 103.0,
 332.0,
 86.0,
 173.0,
 246.0,
 161.0,
 396.0,
 1100.0,
 433.0,
 242.0,
 206.0,
 177.0,
 1500.0,
 198.0,
 459.0,
 173.0,
 117.0,
 130.0,
 119.0,
 209.0,
 84.0,
 187.0,
 165.0,
 203.0,
 65.0,
 336.0,
 126.0,
 313.0,
 124.0,
 154.0,
 145.0,
 538.0,
 182.0,
 175.0,
 101.0,
 45.0,
 103.0,
 377.0,
 99.0,
 194.0,
 161.0,
 403.0,
 414.0,
 593.0,
 374.0,
 245.0,
 3200.0,
 266.0,
 299.0,
 309.0,
 215.0,
 265.0,
 211.0,
 112.0,
 203.0,
 337.0,
 70.0,
 159.0,
 688.0,
 116.0,
 63.0,
 144.0,
 123.0,
 71.0,
 224.0,
 113.0,
 175.0,
 130.0,
 168.0,
 61.0,
 89.0,
 137.0,
 278.0,
 75.0,
 148.0,
 176.0,
 197.0,
 264.0,
 214.0,
 182.0,
 247.0,
 402.0,
 440.0,
 1700.0,
 2300.0,
 171.0,
 320.0,
 266.0,
 211.0,
 203.0,
 657.0,
 87.0,
 259.0,
 200.0,
 255.0,
 113.0,
 171.0,
 253.0,
 182.0,
 196.0,
 60.0,
 161.0,
 97.0,
 85.0,
 169.0,
 256.0,
 132.0,
 239.0,
 65.0,
 166.0,
 99.0,
 121.0,
 144.0,
 109.0,
 32.0,
 46.0,
 122.0,
 48.0,
 527.0,
 199.0,
 459.0,
 282.0,
 657.0,
 121.0,
 51.0,
 1900.0,
 642.0,
 155.0,
 171.0,
 323.0,
 288.0,
 497.0,
 509.0,
 79.0,
 49.0,
 270.0,
 511.0,
 80.0,
 247.0,
 128.0,
 115.0,
 156.0,
 87.0,
 196.0,
 204.0,
 143.0,
 337.0,
 140.0,
 87.0,
 207.0,
 112.0,
 152.0,
 220.0,
 122.0,
 134.0,
 225.0,
 96.0,
 94.0,
 74.0,
 135.0,
 142.0,
 45.0,
 50.0,
 77.0,
 40.0,
 107.0,
 193.0,
 179.0,
 34.0,
 64.0,
 453.0,
 112.0,
 57.0,
 81.0,
 70.0,
 28.0,
 124.0,
 79.0,
 193.0,
 128.0,
 78.0,
 137.0,
 133.0,
 282.0,
 61.0,
 71.0,
 43.0,
 425.0,
 96.0,
 65.0,
 87.0,
 65.0,
 313.0,
 88.0,
 145.0,
 42.0,
 36.0,
 199.0,
 256.0,
 233.0,
 376.0,
 205.0,
 210.0,
 225.0,
 132.0,
 444.0,
 84.0,
 100.0,
 212.0,
 263.0,
 248.0,
 98.0,
 29.0,
 160.0,
 159.0,
 145.0,
 39.0,
 257.0,
 75.0,
 6.0,
 310.0,
 65.0,
 77.0,
 138.0,
 94.0,
 62.0,
 74.0,
 36.0,
 65.0,
 293.0,
 285.0,
 362.0,
 66.0,
 69.0,
 58.0,
 21.0,
 20.0,
 43.0,
 131.0,
 142.0,
 38.0,
 406.0,
 68.0,
 71.0,
 108.0,
 85.0,
 36.0,
 96.0,
 93.0,
 512.0,
 110.0,
 443.0,
 306.0,
 352.0,
 422.0,
 585.0,
 282.0,
 346.0,
 178.0,
 841.0,
 394.0,
 72.0,
 43.0,
 172.0,
 44.0,
 42.0,
 75.0,
 214.0,
 407.0,
 210.0,
 36.0,
 107.0,
 230.0,
 88.0,
 367.0,
 189.0,
 93.0,
 233.0,
 103.0,
 295.0,
 194.0,
 197.0,
 157.0,
 112.0,
 84.0,
 243.0,
 56.0,
 130.0,
 111.0,
 326.0,
 130.0,
 679.0,
 197.0,
 117.0,
 215.0,
 111.0,
 18.0,
 74.0,
 56.0,
 92.0,
 48.0,
 115.0,
 140.0,
 100.0,
 62.0,
 97.0,
 72.0,
 138.0,
 133.0,
 124.0,
 132.0,
 65.0,
 81.0,
 68.0,
 46.0,
 77.0,
 214.0,
 123.0,
 59.0,
 25.0,
 42.0,
 154.0,
 130.0,
 74.0,
 184.0,
 58.0,
 38.0,
 71.0,
 72.0,
 75.0,
 53.0,
 38.0,
 68.0,
 32.0,
 39.0,
 12.0,
 93.0,
 88.0,
 55.0,
 73.0,
 11.0,
 566.0,
 180.0,
 83.0,
 262.0,
 18.0,
 17.0,
 12.0,
 11.0,
 31.0,
 31.0,
 245.0,
 64.0,
 280.0,
 359.0,
 337.0,
 213.0,
 297.0,
 145.0,
 387.0,
 108.0,
 480.0,
 381.0,
 6.0,
 414.0,
 200.0,
 28.0,
 28.0,
 71.0,
 677.0,
 56.0,
 152.0,
 182.0,
 486.0,
 8.0,
 244.0,
 248.0,
 129.0,
 194.0,
 388.0,
 275.0,
 319.0,
 2000.0,
 52.0,
 113.0,
 48.0,
 91.0,
 165.0,
 93.0,
 421.0,
 71.0,
 142.0,
 155.0,
 48.0,
 69.0,
 84.0,
 40.0,
 134.0,
 55.0,
 180.0,
 79.0,
 42.0,
 224.0,
 60.0,
 153.0,
 68.0,
 86.0,
 90.0,
 27.0,
 58.0,
 103.0,
 41.0,
 79.0,
 52.0,
 107.0,
 55.0,
 222.0,
 35.0,
 90.0,
 102.0,
 42.0,
 39.0,
 71.0,
 30.0,
 46.0,
 30.0,
 40.0,
 109.0,
 53.0,
 46.0,
 33.0,
 52.0,
 99.0,
 113.0,
 100.0,
 129.0,
 46.0,
 40.0,
 21.0,
 100.0,
 108.0,
 79.0,
 96.0,
 29.0,
 88.0,
 45.0,
 55.0,
 38.0,
 23.0,
 21.0,
 34.0,
 75.0,
 90.0,
 193.0,
 39.0,
 46.0,
 146.0,
 40.0,
 87.0,
 64.0,
 55.0,
 72.0,
 40.0,
 13.0,
 6.0,
 21.0,
 14.0,
 106.0,
 276.0,
 527.0,
 47.0,
 265.0,
 249.0,
 369.0,
 113.0,
 219.0,
 565.0,
 204.0,
 237.0,
 173.0,
 227.0,
 434.0,
 375.0,
 160.0,
 162.0,
 162.0,
 605.0,
 654.0,
 75.0,
 42.0,
 3.0,
 20.0,
 7.0,
 9.0,
 32.0,
 1100.0,
 282.0,
 118.0,
 184.0,
 104.0,
 168.0,
 14.0,
 156.0,
 100.0,
 93.0,
 114.0,
 81.0,
 186.0,
 242.0,
 101.0,
 150.0,
 41.0,
 8.0,
 111.0,
 148.0,
 446.0,
 131.0,
 124.0,
 20.0,
 237.0,
 130.0,
 49.0,
 131.0,
 116.0,
 756.0,
 20.0,
 32.0,
 42.0,
 73.0,
 189.0,
 122.0,
 124.0,
 29.0,
 139.0,
 107.0,
 89.0,
 61.0,
 135.0,
 187.0,
 22.0,
 500.0,
 72.0,
 67.0,
 27.0,
 64.0,
 56.0,
 147.0,
 33.0,
 230.0,
 21.0,
 78.0,
 149.0,
 45.0,
 16.0,
 40.0,
 134.0,
 65.0,
 30.0,
 61.0,
 49.0,
 35.0,
 51.0,
 81.0,
 22.0,
 48.0,
 126.0,
 21.0,
 39.0,
 114.0,
 71.0,
 45.0,
 20.0,
 28.0,
 19.0,
 23.0,
 19.0,
 119.0,
 35.0,
 73.0,
 32.0,
 55.0,
 19.0,
 214.0,
 25.0,
 54.0,
 98.0,
 82.0,
 9.0,
 67.0,
 30.0,
 21.0,
 50.0,
 53.0,
 89.0,
 39.0,
 20.0,
 29.0,
 41.0,
 31.0,
 31.0,
 112.0,
 12.0,
 20.0,
 17.0,
 8.0,
 42.0,
 37.0,
 99.0,
 16.0,
 128.0,
 53.0,
 16.0,
 17.0,
 36.0,
 129.0,
 83.0,
 17.0,
 27.0,
 70.0,
 67.0,
 15.0,
 56.0,
 44.0,
 44.0,
 91.0,
 62.0,
 20.0,
 1300.0,
 9.0,
 52.0,
 3000.0,
 15.0,
 952.0,
 5.0,
 688.0,
 749.0,
 541.0,
 50.0,
 330.0,
 276.0,
 30.0,
 15.0,
 393.0,
 247.0,
 129.0,
 184.0,
 517.0,
 108.0,
 770.0,
 169.0,
 111.0,
 220.0,
 162.0,
 409.0,
 47.0,
 170.0,
 50.0,
 125.0,
 283.0,
 408.0,
 239.0,
 342.0,
 63.0,
 363.0,
 23.0,
 68.0,
 580.0,
 5.0,
 16.0,
 7.0,
 3.0,
 15.0,
 9.0,
 16.0,
 8.0,
 29.0,
 15.0,
 215.0,
 105.0,
 101.0,
 59.0,
 217.0,
 280.0,
 24.0,
 249.0,
 145.0,
 119.0,
 42.0,
 26.0,
 45.0,
 132.0,
 70.0,
 18.0,
 73.0,
 41.0,
 19.0,
 145.0,
 157.0,
 93.0,
 187.0,
 81.0,
 142.0,
 15.0,
 68.0,
 66.0,
 53.0,
 16.0,
 52.0,
 5.0,
 39.0,
 31.0,
 16.0,
 60.0,
 55.0,
 141.0,
 38.0,
 139.0,
 70.0,
 13.0,
 14.0,
 49.0,
 26.0,
 15.0,
 84.0,
 33.0,
 43.0,
 39.0,
 84.0,
 107.0,
 131.0,
 14.0,
 84.0,
 31.0,
 63.0,
 64.0,
 55.0,
 62.0,
 96.0,
 128.0,
 81.0,
 39.0,
 62.0,
 88.0,
 20.0,
 65.0,
 54.0,
 19.0,
 17.0,
 50.0,
 18.0,
 47.0,
 39.0,
 34.0,
 84.0,
 12.0,
 76.0,
 98.0,
 22.0,
 23.0,
 11.0,
 37.0,
 109.0,
 47.0,
 57.0,
 103.0,
 20.0,
 35.0,
 41.0,
 34.0,
 11.0,
 47.0,
 33.0,
 17.0,
 125.0,
 50.0,
 44.0,
 30.0,
 16.0,
 21.0,
 35.0,
 128.0,
 31.0,
 22.0,
 33.0,
 52.0,
 41.0,
 11.0,
 38.0,
 30.0,
 9.0,
 107.0,
 16.0,
 17.0,
 22.0,
 70.0,
 41.0,
 17.0,
 8.0,
 20.0,
 36.0,
 11.0,
 26.0,
 34.0,
 18.0,
 58.0,
 32.0,
 17.0,
 62.0,
 29.0,
 38.0,
 10.0,
 10.0,
 13.0,
 17.0,
 26.0,
 58.0,
 6.0,
 16.0,
 13.0,
 20.0,
 12.0,
 31.0,
 14.0,
 39.0,
 12.0,
 18.0,
 11.0,
 10.0,
 28.0,
 27.0,
 40.0,
 16.0,
 17.0,
 116.0,
 29.0,
 97.0,
 49.0,
 212.0,
 427.0,
 74.0,
 10.0,
 19.0,
 247.0,
 162.0,
 40.0,
 28.0,
 70.0,
 140.0,
 158.0,
 426.0,
 51.0,
 19.0,
 24.0,
 4.0,
 25.0,
 24.0,
 12.0,
 33.0,
 44.0,
 19.0,
 77.0,
 3.0,
 41.0,
 15.0,
 11.0,
 35.0,
 58.0,
 25.0,
 10.0,
 38.0,
 24.0,
 207.0,
 159.0,
 21.0,
 46.0,
 19.0,
 36.0,
 123.0,
 9.0,
 247.0,
 72.0,
 44.0,
 28.0,
 102.0,
 92.0,
 32.0,
 29.0,
 48.0,
 37.0,
 13.0,
 9.0,
 28.0,
 40.0,
 8.0,
 13.0,
 114.0,
 666.0,
 37.0,
 22.0,
 58.0,
 51.0,
 28.0,
 47.0,
 87.0,
 4.0,
 54.0,
 181.0,
 19.0,
 12.0,
 42.0,
 16.0,
 16.0,
 324.0,
 18.0,
 35.0,
 25.0,
 7.0,
 30.0,
 7.0,
 19.0,
 47.0,
 26.0,
 107.0,
 62.0,
 17.0,
 29.0,
 40.0,
 979.0,
 32.0,
 15.0,
 15.0,
 29.0,
 394.0,
 25.0,
 19.0,
 39.0,
 19.0,
 64.0,
 23.0,
 55.0,
 165.0,
 19.0,
 64.0,
 1400.0,
 112.0,
 41.0,
 29.0,
 21.0,
 38.0,
 38.0,
 31.0,
 40.0,
 16.0,
 14.0,
 75.0,
 38.0,
 31.0,
 110.0,
 217.0,
 87.0,
 51.0,
 29.0,
 145.0,
 68.0,
 5.0,
 302.0,
 88.0,
 36.0,
 28.0,
 22.0,
 36.0,
 161.0,
 20.0,
 22.0,
 15.0,
 751.0,
 116.0,
 35.0,
 ...]

In [98]:
df_musket['Hits'] = hitList
df_musket

C:\Users\User\AppData\Local\Temp/ipykernel_14680/2860936469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_musket['Hits'] = hitList

,Age,↓OVA,POT,Preferred Foot,BOV,Best Position,Attacking,Crossing,Dribbling1,Short Passing1,...,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits1,Dribbling,Short Passing,Hits
0,33,93.0,93.0,0,93,0,429.0,85.0,96.0,91.0,...,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0,96.0,91.0,771.0
1,35,92.0,92.0,1,92,1,437.0,84.0,88.0,82.0,...,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0,88.0,82.0,562.0
2,27,91.0,93.0,1,91,2,95.0,13.0,12.0,43.0,...,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0,12.0,43.0,150.0
3,29,91.0,91.0,1,91,3,407.0,94.0,88.0,94.0,...,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0,88.0,94.0,207.0
4,28,91.0,91.0,1,91,4,408.0,85.0,95.0,87.0,...,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0,95.0,87.0,595.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,21,47.0,55.0,1,49,5,145.0,23.0,27.0,26.0,...,1,66.0,1.78,100000.0,1000.0,70000.0,nan,27.0,26.0,NaN
19017,17,47.0,67.0,1,51,3,211.0,38.0,46.0,56.0,...,1,65.0,1.75,130000.0,500000.0,165000.0,nan,46.0,56.0,NaN
19018,18,47.0,65.0,1,49,3,200.0,30.0,43.0,54.0,...,1,74.0,1.79,120000.0,500000.0,131000.0,nan,43.0,54.0,NaN
19019,20,47.0,57.0,1,48,1,215.0,45.0,51.0,42.0,...,1,69.0,1.75,100000.0,2000.0,88000.0,nan,51.0,42.0,NaN
19020,21,47.0,57.0,0,50,10,163.0,40.0,40.0,45.0,...,1,75.0,1.88,100000.0,1000.0,79000.0,nan,40.0,45.0,NaN

In [99]:
list(df_musket.columns)

['Age',
 '↓OVA',
 'POT',
 'Preferred Foot',
 'BOV',
 'Best Position',
 'Attacking',
 'Crossing',
 'Dribbling1',
 'Short Passing1',
 'Finishing',
 'Heading Accuracy',
 'Volleys',
 'Skill',
 'Curve',
 'FK Accuracy',
 'Long Passing',
 'Ball Control',
 'Movement',
 'Acceleration',
 'Sprint Speed',
 'Agility',
 'Reactions',
 'Balance',
 'Power',
 'Shot Power',
 'Jumping',
 'Stamina',
 'Strength',
 'Long Shots',
 'Mentality',
 'Aggression',
 'Interceptions',
 'Positioning',
 'Vision',
 'Penalties',
 'Composure',
 'Defending',
 'Marking',
 'Standing Tackle',
 'Sliding Tackle',
 'Goalkeeping',
 'GK Diving',
 'GK Handling',
 'GK Kicking',
 'GK Positioning',
 'GK Reflexes',
 'Total Stats',
 'Base Stats',
 'A/W',
 'D/W',
 'PAC',
 'SHO',
 'PAS',
 'DRI',
 'DEF',
 'PHY',
 'PlayerName',
 'PlayerStatus',
 'LB',
 'LW',
 'RM',
 'CF',
 'ST',
 'GK',
 'RW',
 'LM',
 'RWB',
 'LWB',
 'CAM',
 'CDM',
 'CB',
 'RB',
 'CM',
 'W/F1',
 'SM1',
 'IR1',
 'wt(kg)',
 'ht(m)',
 'Value(€)',
 'Wage(€)',
 'Release Clause(€)',
 'Hits1',
 'Dribbling',
 'Short Passing',
 'Hits']

In [100]:
# Removing unwanted columns
refCols1 = ['Age',
 '↓OVA',
 'POT',
 'Preferred Foot',
 'BOV',
 'Best Position',
 'Attacking',
 'Crossing',
 'Finishing',
 'Heading Accuracy',
 'Short Passing',
 'Dribbling',
 'Volleys',
 'Skill',
 'Curve',
 'FK Accuracy',
 'Long Passing',
 'Ball Control',
 'Movement',
 'Acceleration',
 'Sprint Speed',
 'Agility',
 'Reactions',
 'Balance',
 'Power',
 'Shot Power',
 'Jumping',
 'Stamina',
 'Strength',
 'Long Shots',
 'Mentality',
 'Aggression',
 'Interceptions',
 'Positioning',
 'Vision',
 'Penalties',
 'Composure',
 'Defending',
 'Marking',
 'Standing Tackle',
 'Sliding Tackle',
 'Goalkeeping',
 'GK Diving',
 'GK Handling',
 'GK Kicking',
 'GK Positioning',
 'GK Reflexes',
 'Total Stats',
 'Base Stats',
 'A/W',
 'D/W',
 'PAC',
 'SHO',
 'PAS',
 'DRI',
 'DEF',
 'PHY',
 'PlayerStatus',
 'LB',
 'LW',
 'RM',
 'CF',
 'ST',
 'GK',
 'RW',
 'LM',
 'RWB',
 'LWB',
 'CAM',
 'CDM',
 'CB',
 'RB',
 'CM',
 'W/F1',
 'SM1',
 'IR1',
 'wt(kg)',
 'ht(m)',
 'Value(€)',
 'Wage(€)',
 'Release Clause(€)',
 'Hits']

In [101]:
df_musket=df_musket[refCols1]
df_musket

,Age,↓OVA,POT,Preferred Foot,BOV,Best Position,Attacking,Crossing,Finishing,Heading Accuracy,...,CM,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits
0,33,93.0,93.0,0,93,0,429.0,85.0,95.0,70.0,...,0,4,4,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0
1,35,92.0,92.0,1,92,1,437.0,84.0,95.0,90.0,...,0,4,5,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0
2,27,91.0,93.0,1,91,2,95.0,13.0,11.0,15.0,...,0,3,1,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0
3,29,91.0,91.0,1,91,3,407.0,94.0,82.0,55.0,...,1,5,4,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0
4,28,91.0,91.0,1,91,4,408.0,85.0,87.0,62.0,...,0,5,5,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19016,21,47.0,55.0,1,49,5,145.0,23.0,26.0,43.0,...,0,2,2,1,66.0,1.78,100000.0,1000.0,70000.0,NaN
19017,17,47.0,67.0,1,51,3,211.0,38.0,42.0,40.0,...,1,2,2,1,65.0,1.75,130000.0,500000.0,165000.0,NaN
19018,18,47.0,65.0,1,49,3,200.0,30.0,34.0,43.0,...,1,2,2,1,74.0,1.79,120000.0,500000.0,131000.0,NaN
19019,20,47.0,57.0,1,48,1,215.0,45.0,52.0,34.0,...,0,3,2,1,69.0,1.75,100000.0,2000.0,88000.0,NaN
19020,21,47.0,57.0,0,50,10,163.0,40.0,18.0,40.0,...,0,3,2,1,75.0,1.88,100000.0,1000.0,79000.0,NaN

In [102]:
df_musket.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18915 entries, 0 to 19020
Data columns (total 82 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                18915 non-null  int64
 1   ↓OVA               18915 non-null  float64
 2   POT                18915 non-null  float64
 3   Preferred Foot     18915 non-null  int64
 4   BOV                18915 non-null  int64
 5   Best Position      18915 non-null  int64
 6   Attacking          18915 non-null  float64
 7   Crossing           18915 non-null  float64
 8   Finishing          18915 non-null  float64
 9   Heading Accuracy   18915 non-null  float64
 10  Short Passing      18910 non-null  float64
 11  Dribbling          18915 non-null  float64
 12  Volleys            18915 non-null  float64
 13  Skill              18915 non-null  float64
 14  Curve              18915 non-null  float64
 15  FK Accuracy        18915 non-null  float64
 16  Long Passing       18915 non-null  float64
 17  Ball Control       18915 non-null  float64
 18  Movement           18915 non-null  float64
 19  Acceleration       18915 non-null  float64
 20  Sprint Speed       18915 non-null  float64
 21  Agility            18915 non-null  float64
 22  Reactions          18915 non-null  float64
 23  Balance            18915 non-null  float64
 24  Power              18915 non-null  float64
 25  Shot Power         18915 non-null  float64
 26  Jumping            18915 non-null  float64
 27  Stamina            18915 non-null  float64
 28  Strength           18915 non-null  float64
 29  Long Shots         18915 non-null  float64
 30  Mentality          18915 non-null  float64
 31  Aggression         18915 non-null  int64
 32  Interceptions      18915 non-null  float64
 33  Positioning        18915 non-null  float64
 34  Vision             18915 non-null  int64
 35  Penalties          18915 non-null  float64
 36  Composure          18915 non-null  float64
 37  Defending          18915 non-null  float64
 38  Marking            18915 non-null  float64
 39  Standing Tackle    18915 non-null  float64
 40  Sliding Tackle     18915 non-null  float64
 41  Goalkeeping        18915 non-null  float64
 42  GK Diving          18915 non-null  float64
 43  GK Handling        18915 non-null  float64
 44  GK Kicking         18915 non-null  float64
 45  GK Positioning     18915 non-null  float64
 46  GK Reflexes        18915 non-null  int64
 47  Total Stats        18915 non-null  float64
 48  Base Stats         18915 non-null  int64
 49  A/W                18915 non-null  int64
 50  D/W                18915 non-null  float64
 51  PAC                18915 non-null  float64
 52  SHO                18915 non-null  float64
 53  PAS                18915 non-null  float64
 54  DRI                18915 non-null  float64
 55  DEF                18915 non-null  float64
 56  PHY                18915 non-null  float64
 57  PlayerStatus       18915 non-null  int64
 58  LB                 18915 non-null  int64
 59  LW                 18915 non-null  int64
 60  RM                 18915 non-null  int64
 61  CF                 18915 non-null  int64
 62  ST                 18915 non-null  int64
 63  GK                 18915 non-null  int64
 64  RW                 18915 non-null  int64
 65  LM                 18915 non-null  int64
 66  RWB                18915 non-null  int64
 67  LWB                18915 non-null  int64
 68  CAM                18915 non-null  int64
 69  CDM                18915 non-null  int64
 70  CB                 18915 non-null  int64
 71  RB                 18915 non-null  int64
 72  CM                 18915 non-null  int64
 73  W/F1               18915 non-null  int64
 74  SM1                18915 non-null  int64
 75  IR1                18915 non-null  int64
 76  wt(kg)             18915 non-null  float64
 77  ht(m)              18915 non-null  float64
 78  Value(€)           18915 non-null  float64
 79  Wage(€)            18915 non-null  float64
 80  Release Clause(€)  18915 non-null  float64
 81  Hits               16280 non-null  float64
dtypes: float64(54), int64(28)
memory usage: 12.0 MB

In [103]:
df_musket.Hits.unique

<bound method Series.unique of 0        771.0
1        562.0
2        150.0
3        207.0
4        595.0
         ...
19016      NaN
19017      NaN
19018      NaN
19019      NaN
19020      NaN
Name: Hits, Length: 18915, dtype: float64>

In [104]:
df_musket.isna().sum()

Age                     0
↓OVA                    0
POT                     0
Preferred Foot          0
BOV                     0
                     ...
ht(m)                   0
Value(€)                0
Wage(€)                 0
Release Clause(€)       0
Hits                 2635
Length: 82, dtype: int64

In [105]:
df_musket = df_musket.dropna() # dropping all rows with missing values affected by the Hits column
df_musket

,Age,↓OVA,POT,Preferred Foot,BOV,Best Position,Attacking,Crossing,Finishing,Heading Accuracy,...,CM,W/F1,SM1,IR1,wt(kg),ht(m),Value(€),Wage(€),Release Clause(€),Hits
0,33,93.0,93.0,0,93,0,429.0,85.0,95.0,70.0,...,0,4,4,5,72.0,1.70,103500000.0,560000.0,138400000.0,771.0
1,35,92.0,92.0,1,92,1,437.0,84.0,95.0,90.0,...,0,4,5,5,83.0,1.87,63000000.0,220000.0,75900000.0,562.0
2,27,91.0,93.0,1,91,2,95.0,13.0,11.0,15.0,...,0,3,1,3,87.0,1.88,120000000.0,125000.0,159400000.0,150.0
3,29,91.0,91.0,1,91,3,407.0,94.0,82.0,55.0,...,1,5,4,4,70.0,1.81,129000000.0,370000.0,161000000.0,207.0
4,28,91.0,91.0,1,91,4,408.0,85.0,87.0,62.0,...,0,5,5,5,68.0,1.75,132000000.0,270000.0,166500000.0,595.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16379,28,58.0,58.0,0,59,3,258.0,54.0,53.0,44.0,...,1,4,3,1,78.0,1.75,200000.0,500000.0,202000.0,3.0
16380,18,58.0,74.0,1,60,5,202.0,32.0,26.0,63.0,...,0,3,2,1,78.0,1.95,475000.0,1000.0,581000.0,1.0
16381,24,58.0,64.0,0,58,2,108.0,15.0,19.0,22.0,...,0,3,1,1,78.0,1.93,250000.0,1000.0,0.0,5.0
16382,17,58.0,75.0,1,59,12,256.0,51.0,59.0,43.0,...,0,3,2,1,70.0,1.77,500000.0,500000.0,494000.0,3.0
16383,20,58.0,75.0,0,60,1,230.0,31.0,60.0,55.0,...,0,3,2,1,80.0,1.88,550000.0,5000.0,722000.0,4.0

In [106]:
df_musket.info() #checking that all useful features are numeric

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16275 entries, 0 to 16383
Data columns (total 82 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                16275 non-null  int64
 1   ↓OVA               16275 non-null  float64
 2   POT                16275 non-null  float64
 3   Preferred Foot     16275 non-null  int64
 4   BOV                16275 non-null  int64
 5   Best Position      16275 non-null  int64
 6   Attacking          16275 non-null  float64
 7   Crossing           16275 non-null  float64
 8   Finishing          16275 non-null  float64
 9   Heading Accuracy   16275 non-null  float64
 10  Short Passing      16275 non-null  float64
 11  Dribbling          16275 non-null  float64
 12  Volleys            16275 non-null  float64
 13  Skill              16275 non-null  float64
 14  Curve              16275 non-null  float64
 15  FK Accuracy        16275 non-null  float64
 16  Long Passing       16275 non-null  float64
 17  Ball Control       16275 non-null  float64
 18  Movement           16275 non-null  float64
 19  Acceleration       16275 non-null  float64
 20  Sprint Speed       16275 non-null  float64
 21  Agility            16275 non-null  float64
 22  Reactions          16275 non-null  float64
 23  Balance            16275 non-null  float64
 24  Power              16275 non-null  float64
 25  Shot Power         16275 non-null  float64
 26  Jumping            16275 non-null  float64
 27  Stamina            16275 non-null  float64
 28  Strength           16275 non-null  float64
 29  Long Shots         16275 non-null  float64
 30  Mentality          16275 non-null  float64
 31  Aggression         16275 non-null  int64
 32  Interceptions      16275 non-null  float64
 33  Positioning        16275 non-null  float64
 34  Vision             16275 non-null  int64
 35  Penalties          16275 non-null  float64
 36  Composure          16275 non-null  float64
 37  Defending          16275 non-null  float64
 38  Marking            16275 non-null  float64
 39  Standing Tackle    16275 non-null  float64
 40  Sliding Tackle     16275 non-null  float64
 41  Goalkeeping        16275 non-null  float64
 42  GK Diving          16275 non-null  float64
 43  GK Handling        16275 non-null  float64
 44  GK Kicking         16275 non-null  float64
 45  GK Positioning     16275 non-null  float64
 46  GK Reflexes        16275 non-null  int64
 47  Total Stats        16275 non-null  float64
 48  Base Stats         16275 non-null  int64
 49  A/W                16275 non-null  int64
 50  D/W                16275 non-null  float64
 51  PAC                16275 non-null  float64
 52  SHO                16275 non-null  float64
 53  PAS                16275 non-null  float64
 54  DRI                16275 non-null  float64
 55  DEF                16275 non-null  float64
 56  PHY                16275 non-null  float64
 57  PlayerStatus       16275 non-null  int64
 58  LB                 16275 non-null  int64
 59  LW                 16275 non-null  int64
 60  RM                 16275 non-null  int64
 61  CF                 16275 non-null  int64
 62  ST                 16275 non-null  int64
 63  GK                 16275 non-null  int64
 64  RW                 16275 non-null  int64
 65  LM                 16275 non-null  int64
 66  RWB                16275 non-null  int64
 67  LWB                16275 non-null  int64
 68  CAM                16275 non-null  int64
 69  CDM                16275 non-null  int64
 70  CB                 16275 non-null  int64
 71  RB                 16275 non-null  int64
 72  CM                 16275 non-null  int64
 73  W/F1               16275 non-null  int64
 74  SM1                16275 non-null  int64
 75  IR1                16275 non-null  int64
 76  wt(kg)             16275 non-null  float64
 77  ht(m)              16275 non-null  float64
 78  Value(€)           16275 non-null  float64
 79  Wage(€)            16275 non-null  float64
 80  Release Clause(€)  16275 non-null  float64
 81  Hits               16275 non-null  float64
dtypes: float64(54), int64(28)
memory usage: 10.3 MB

Feature Transformation to inspect for the following

Varying SCALES across the features in our data
Inspecting the standard error in each feature and across our features

In [107]:
df_musket.describe().T # Conducting general inspection of the behavior of the data

,count,mean,std,min,25%,50%,75%,max
Age,16275.0,2.590919e+01,4.498397e+00,16.00,22.00,26.00,29.00,5.300000e+01
↓OVA,16275.0,6.743926e+01,5.618754e+00,58.00,63.00,67.00,71.00,9.300000e+01
POT,16275.0,7.182046e+01,5.872793e+00,58.00,68.00,72.00,76.00,9.500000e+01
Preferred Foot,16275.0,7.520737e-01,4.318221e-01,0.00,1.00,1.00,1.00,1.000000e+00
BOV,16275.0,6.838353e+01,5.497718e+00,58.00,64.00,68.00,72.00,9.300000e+01
...,...,...,...,...,...,...,...,...
ht(m),16275.0,1.812851e+00,6.843749e-02,1.55,1.76,1.81,1.86,2.060000e+00
Value(€),16275.0,3.214714e+06,8.153420e+06,0.00,625000.00,1200000.00,2300000.00,1.855000e+08
Wage(€),16275.0,9.611035e+04,2.198580e+05,0.00,2000.00,6000.00,23000.00,9.500000e+05
Release Clause(€),16275.0,4.464620e+06,1.034136e+07,0.00,634000.00,1200000.00,3500000.00,2.031000e+08
Hits,16275.0,2.620344e+01,1.285157e+02,1.00,2.00,5.00,15.00,8.400000e+03

In [108]:
!pip install sklearn

Requirement already satisfied: sklearn in c:\users\user\anaconda3\lib\site-packages (0.0.post1)

In [109]:
df_musket.columns

Index(['Age', '↓OVA', 'POT', 'Preferred Foot', 'BOV', 'Best Position',
       'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy',
       'Short Passing', 'Dribbling', 'Volleys', 'Skill', 'Curve',
       'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'A/W', 'D/W', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY',
       'PlayerStatus', 'LB', 'LW', 'RM', 'CF', 'ST', 'GK', 'RW', 'LM', 'RWB',
       'LWB', 'CAM', 'CDM', 'CB', 'RB', 'CM', 'W/F1', 'SM1', 'IR1', 'wt(kg)',
       'ht(m)', 'Value(€)', 'Wage(€)', 'Release Clause(€)', 'Hits'],
      dtype='object')

In [110]:
# Using univariate feature selection process
# influencing the outcome using chi-square test

In [133]:
from sklearn.preprocessing import Normalizer 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# convert dataframe to array

dfArr = df_musket.values
X = dfArr[:,:-1]
Y = dfArr[:,-1]

norm = Normalizer().fit(X) # Normalizing the data
normalizedX= norm.transform(X)
test = SelectKBest(score_func=chi2, k=20)
fit = test.fit(normalizedX,Y)
features = fit.transform(normalizedX)

In [134]:
fit.scores_

array([2.22084649e+00, 6.55011442e+00, 6.86005674e+00, 7.01274921e-02,
       6.60930740e+00, 6.85461429e-01, 2.77394459e+01, 5.97885440e+00,
       5.34115380e+00, 5.76498380e+00, 6.57279281e+00, 6.69828136e+00,
       4.75110698e+00, 2.96768980e+01, 5.92657687e+00, 4.96966508e+00,
       6.03805062e+00, 6.57402591e+00, 3.28272861e+01, 6.74661474e+00,
       6.54784411e+00, 6.95082461e+00, 6.25809711e+00, 6.66160742e+00,
       2.94336502e+01, 5.70545005e+00, 6.01081413e+00, 6.91204718e+00,
       6.09469744e+00, 5.47558387e+00, 2.86050116e+01, 6.35858950e+00,
       5.98392470e+00, 6.22514913e+00, 5.89567534e+00, 5.05482223e+00,
       6.32185474e+00, 1.79758047e+01, 6.14403950e+00, 5.99353558e+00,
       5.91122777e+00, 1.08535165e+01, 2.26740446e+00, 2.15769329e+00,
       2.14232847e+00, 2.16609060e+00, 2.23190529e+00, 1.66479417e+02,
       3.53907889e+01, 1.35824788e-01, 1.28387341e-01, 6.63226456e+00,
       5.17629658e+00, 5.86057772e+00, 6.43455721e+00, 5.69821001e+00,
       6.22587369e+00, 2.00951962e-01, 1.06490160e-01, 1.69366420e-01,
       4.96730516e-02, 7.94718978e-02, 5.90914138e-02, 3.69618837e-02,
       5.48133623e-02, 9.77668858e-02, 1.70223510e-02, 1.08197281e-01,
       8.22001096e-02, 1.05519787e-01, 4.34897193e-02, 2.44609532e-02,
       1.14118963e-01, 3.10171950e-01, 2.82028196e-01, 1.19805481e-01,
       6.52224959e+00, 1.60213579e-01, 2.35796564e+01, 6.67183461e+02,
       3.26791275e+01])

In [135]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression ()
res = model.fit(normalizedX,Y)
score = res.score(normalizedX,Y)
score

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.1480798771121352

In [ ]:
# Using Recursive Feature Elimination - To Moderateg and mediate characteristics of variables

In [126]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

model = LogisticRegression ()

dfArr = df_musket.values
X = dfArr[:,:-1]
Y = dfArr[:,-1]

norm = Normalizer().fit(X) # Normalizing the data
normalizedX= norm.transform(X)
rfe = RFE(model, n_features_to_select=2)
fit = rfe.fit(normalizedX,Y)
fit.support_
fit.ranking_

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

KeyboardInterrupt: